//! GENERATED by tools/gen_anim_defs.ps1 from the decompiled 26.2
//! AnimationDefinitions - do not edit by hand; re-run the script.
//! Rotations are radians, positions model px with the vanilla posVec
//! y-negation baked in. Scale channels are omitted (unsupported).

use crate::mobs::{KfChannel, KfDef, KfFrame, KfTarget};

/// FROG_WALK (C:\Users\valtteri\AppData\Roaming\EwoClient\rewo\26.2\decompiled\net\minecraft\client\animation\definitions\FrogAnimation.java | 9 channels, 0 scale skipped)
pub static FROG_WALK: KfDef = KfDef {
    length: 1.25,
    looping: true,
    channels: &[
        KfChannel {
            part: "left_arm",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, -0.0872664626, 0.0], catmullrom: false },
                KfFrame { t: 0.2917, v: [0.130899694, -0.046600291, -0.130899694], catmullrom: false },
                KfFrame { t: 0.625, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.7917, v: [0.392699082, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.125, v: [-0.785398163, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.25, v: [0.0, -0.0872664626, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_arm",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, -0.1, -2.0], catmullrom: false },
                KfFrame { t: 0.2917, v: [-0.5, 0.25, -0.13], catmullrom: false },
                KfFrame { t: 0.625, v: [-0.5, -0.1, 2.0], catmullrom: false },
                KfFrame { t: 0.9583, v: [0.5, -1.0, -0.11], catmullrom: false },
                KfFrame { t: 1.25, v: [0.0, -0.1, -2.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_arm",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.392699082, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.4583, v: [-0.785398163, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.625, v: [0.0, 0.0872664626, 0.0], catmullrom: false },
                KfFrame { t: 0.9583, v: [0.130899694, 0.0406661716, 0.130899694], catmullrom: false },
                KfFrame { t: 1.25, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_arm",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.5, -0.1, 2.0], catmullrom: false },
                KfFrame { t: 0.2917, v: [-0.5, -1.0, 0.12], catmullrom: false },
                KfFrame { t: 0.625, v: [0.0, -0.1, -2.0], catmullrom: false },
                KfFrame { t: 0.9583, v: [0.5, 0.25, -0.13], catmullrom: false },
                KfFrame { t: 1.25, v: [0.5, -0.1, 2.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.1667, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.2917, v: [0.785398163, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.625, v: [-0.785398163, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.7917, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.25, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, -0.1, 1.2], catmullrom: false },
                KfFrame { t: 0.1667, v: [0.0, -0.1, 2.0], catmullrom: false },
                KfFrame { t: 0.4583, v: [0.0, -2.0, 1.06], catmullrom: false },
                KfFrame { t: 0.7917, v: [0.0, -0.1, -1.0], catmullrom: false },
                KfFrame { t: 1.25, v: [0.0, -0.1, 1.2], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [-0.589048623, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.0417, v: [-0.785398163, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.1667, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.7917, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.9583, v: [0.785398163, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.25, v: [-0.589048623, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, -1.14, 0.11], catmullrom: false },
                KfFrame { t: 0.1667, v: [0.0, -0.1, -1.0], catmullrom: false },
                KfFrame { t: 0.7917, v: [0.0, -0.1, 2.0], catmullrom: false },
                KfFrame { t: 1.125, v: [0.0, -2.0, 0.95], catmullrom: false },
                KfFrame { t: 1.25, v: [0.0, -1.14, 0.11], catmullrom: false },
            ],
        },
        KfChannel {
            part: "body",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0872664626, 0.0], catmullrom: false },
                KfFrame { t: 0.2917, v: [-0.130899694, 0.00575958653, 0.130899694], catmullrom: false },
                KfFrame { t: 0.625, v: [0.0, -0.0872664626, 0.0], catmullrom: false },
                KfFrame { t: 0.9583, v: [-0.130899694, 0.00575958653, -0.130899694], catmullrom: false },
                KfFrame { t: 1.25, v: [0.0, 0.0872664626, 0.0], catmullrom: false },
            ],
        },
    ],
};

/// CAMEL_WALK (C:\Users\valtteri\AppData\Roaming\EwoClient\rewo\26.2\decompiled\net\minecraft\client\animation\definitions\CamelAnimation.java | 13 channels, 0 scale skipped)
pub static CAMEL_WALK: KfDef = KfDef {
    length: 1.5,
    looping: true,
    channels: &[
        KfChannel {
            part: "root",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0436332313], catmullrom: true },
                KfFrame { t: 1.0, v: [0.0, 0.0, -0.0436332313], catmullrom: true },
                KfFrame { t: 1.5, v: [0.0, 0.0, 0.0436332313], catmullrom: true },
            ],
        },
        KfChannel {
            part: "head",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0436332313, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.375, v: [-0.0436332313, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.75, v: [0.0436332313, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.125, v: [-0.0436332313, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.5, v: [0.0436332313, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "right_front_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.392699082, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.75, v: [-0.392699082, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.5, v: [0.392699082, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "right_front_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.4583, v: [0.0, -4.0, 0.0], catmullrom: true },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.5, v: [0.0, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "left_front_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [-0.392699082, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.75, v: [0.392699082, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.5, v: [-0.392699082, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "left_front_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.2083, v: [0.0, -4.0, 0.0], catmullrom: true },
                KfFrame { t: 1.5, v: [0.0, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "left_hind_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [-0.356047167, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.75, v: [0.392699082, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.375, v: [-0.392699082, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.5, v: [-0.356047167, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_hind_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.21, 0.0], catmullrom: true },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.0833, v: [0.0, -4.0, 0.0], catmullrom: true },
                KfFrame { t: 1.375, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.5, v: [0.0, 0.21, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_hind_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.392699082, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.625, v: [-0.392699082, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.5, v: [0.392699082, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "right_hind_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.375, v: [0.0, -4.0, 0.0], catmullrom: true },
                KfFrame { t: 0.625, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.5, v: [0.0, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "left_ear",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.375, v: [0.0, 0.0, -0.392699082], catmullrom: true },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.125, v: [0.0, 0.0, -0.392699082], catmullrom: true },
                KfFrame { t: 1.5, v: [0.0, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "right_ear",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.375, v: [0.0, 0.0, 0.392699082], catmullrom: true },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.125, v: [0.0, 0.0, 0.392699082], catmullrom: true },
                KfFrame { t: 1.5, v: [0.0, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "tail",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.278223285, -0.146975224, 0.365489748], catmullrom: true },
                KfFrame { t: 0.75, v: [0.278223285, 0.146975224, -0.365489748], catmullrom: true },
                KfFrame { t: 1.5, v: [0.278223285, -0.146975224, 0.365489748], catmullrom: true },
            ],
        },
    ],
};

/// SNIFFER_WALK (C:\Users\valtteri\AppData\Roaming\EwoClient\rewo\26.2\decompiled\net\minecraft\client\animation\definitions\SnifferAnimation.java | 17 channels, 0 scale skipped)
pub static SNIFFER_WALK: KfDef = KfDef {
    length: 2.0,
    looping: true,
    channels: &[
        KfChannel {
            part: "right_front_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5833, v: [0.610865238, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [-0.610865238, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.1667, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_front_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 3.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, -4.0, -1.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.1667, v: [0.0, 0.0, -1.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.0, 0.0, 3.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_mid_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [-0.122173048, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.1667, v: [-0.610865238, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.3333, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.1667, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.75, v: [0.610865238, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 2.0, v: [-0.122173048, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_mid_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, -2.67, -0.67], catmullrom: false },
                KfFrame { t: 0.1667, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.3333, v: [0.0, 0.0, -2.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 0.0, 2.0], catmullrom: false },
                KfFrame { t: 1.1667, v: [0.0, 0.0, 3.0], catmullrom: false },
                KfFrame { t: 1.9167, v: [0.0, -4.0, -1.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.0, -2.67, -0.67], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_hind_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5833, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.436332313, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.1667, v: [0.610865238, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.5833, v: [-0.610865238, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.75, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_hind_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 0.5833, v: [0.0, 0.0, 2.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, -2.22, 0.78], catmullrom: false },
                KfFrame { t: 1.3333, v: [0.0, -4.0, -1.0], catmullrom: false },
                KfFrame { t: 1.5833, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.75, v: [0.0, 0.0, -2.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.0, 0.0, -0.5], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_front_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [-0.610865238, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.1667, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.5833, v: [0.610865238, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 2.0, v: [-0.610865238, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_front_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.1667, v: [0.0, 0.0, -1.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 0.0, 3.0], catmullrom: false },
                KfFrame { t: 1.75, v: [0.0, -4.0, -1.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_mid_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.1667, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.610865238, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.1667, v: [-0.610865238, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.3333, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_mid_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 2.0], catmullrom: false },
                KfFrame { t: 0.1667, v: [0.0, 0.0, 3.0], catmullrom: false },
                KfFrame { t: 0.9167, v: [0.0, -4.0, -1.0], catmullrom: false },
                KfFrame { t: 1.1667, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.3333, v: [0.0, 0.0, -2.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.0, 0.0, 2.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_hind_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.436332313, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.1667, v: [0.610865238, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5833, v: [-0.610865238, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.5833, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.436332313, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_hind_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, -2.22, 0.78], catmullrom: false },
                KfFrame { t: 0.3333, v: [0.0, -4.0, -1.0], catmullrom: false },
                KfFrame { t: 0.5833, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, -2.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 1.5833, v: [0.0, 0.0, 2.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.0, -2.22, 0.78], catmullrom: false },
            ],
        },
        KfChannel {
            part: "body",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0174532925, 0.0, -0.0436332313], catmullrom: false },
                KfFrame { t: 0.5, v: [-0.0174532925, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0174532925, 0.0, 0.0436332313], catmullrom: false },
                KfFrame { t: 1.5, v: [-0.0174532925, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.0174532925, 0.0, -0.0436332313], catmullrom: false },
            ],
        },
        KfChannel {
            part: "body",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.2083, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.375, v: [0.0, 1.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.2083, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.375, v: [0.0, 1.0, 0.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "head",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.130899694, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.1667, v: [0.157079633, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.875, v: [-0.0174532925, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.25, v: [0.122173048, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.75, v: [0.0872664626, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 2.0, v: [0.130899694, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "left_ear",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, -0.0436332313], catmullrom: true },
                KfFrame { t: 0.5, v: [0.0, 0.0, -0.130899694], catmullrom: true },
                KfFrame { t: 1.0, v: [0.0, 0.0, -0.0436332313], catmullrom: true },
                KfFrame { t: 1.5, v: [0.0, 0.0, -0.130899694], catmullrom: true },
                KfFrame { t: 2.0, v: [0.0, 0.0, -0.0436332313], catmullrom: true },
            ],
        },
        KfChannel {
            part: "right_ear",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0436332313], catmullrom: true },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.130899694], catmullrom: true },
                KfFrame { t: 1.0, v: [0.0, 0.0, 0.0436332313], catmullrom: true },
                KfFrame { t: 1.5, v: [0.0, 0.0, 0.130899694], catmullrom: true },
                KfFrame { t: 2.0, v: [0.0, 0.0, 0.0436332313], catmullrom: true },
            ],
        },
    ],
};

/// ARMADILLO_WALK (C:\Users\valtteri\AppData\Roaming\EwoClient\rewo\26.2\decompiled\net\minecraft\client\animation\definitions\ArmadilloAnimation.java | 12 channels, 0 scale skipped)
pub static ARMADILLO_WALK: KfDef = KfDef {
    length: 1.4583,
    looping: true,
    channels: &[
        KfChannel {
            part: "body",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.25, v: [0.0, 0.0, 0.0802851456], catmullrom: true },
                KfFrame { t: 0.2917, v: [0.0, 0.0, 0.118856922], catmullrom: true },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.7083, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.9583, v: [0.0, 0.0, -0.0802851456], catmullrom: true },
                KfFrame { t: 1.0, v: [0.0, 0.0, -0.120253185], catmullrom: true },
                KfFrame { t: 1.25, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.4583, v: [0.0, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "body",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.25, v: [0.0, 0.2, 0.0], catmullrom: true },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.7083, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.9583, v: [0.0, 0.2, 0.0], catmullrom: true },
                KfFrame { t: 1.25, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.4583, v: [0.0, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "tail",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [-0.160046692, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0872664626, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.2083, v: [-0.14381513, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.4583, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_hind_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [-0.872664626, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.872664626, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.872664626, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.2917, v: [-0.34906585, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.4583, v: [-0.872664626, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_hind_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 1.2917, v: [0.0, -1.0, -0.18], catmullrom: false },
                KfFrame { t: 1.4583, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_hind_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.872664626, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.872664626, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5417, v: [-0.34906585, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.7083, v: [-0.872664626, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.9583, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.2083, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.4583, v: [0.872664626, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_hind_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, -0.25], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 0.5417, v: [0.0, -1.0, -0.18], catmullrom: false },
                KfFrame { t: 0.7083, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.9583, v: [0.0, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 1.2083, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.4583, v: [0.0, 0.0, -0.25], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_front_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.872664626, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.2917, v: [0.872664626, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5417, v: [-0.34906585, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.7083, v: [-0.872664626, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.9583, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.2083, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.4583, v: [0.872664626, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_front_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, -0.25], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 0.5417, v: [0.0, -1.0, -0.18], catmullrom: false },
                KfFrame { t: 0.7083, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.9583, v: [0.0, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 1.2083, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.4583, v: [0.0, 0.0, -0.25], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_front_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [-0.872664626, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.872664626, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.872664626, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.2917, v: [-0.34906585, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.4583, v: [-0.872664626, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_front_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 1.2917, v: [0.0, -1.0, -0.18], catmullrom: false },
                KfFrame { t: 1.4583, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "head",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, 0.0, -0.0436332313], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.7083, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 0.0, 0.0436332313], catmullrom: false },
                KfFrame { t: 1.25, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.4583, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
    ],
};

/// BAT_FLYING (C:\Users\valtteri\AppData\Roaming\EwoClient\rewo\26.2\decompiled\net\minecraft\client\animation\definitions\BatAnimation.java | 9 channels, 0 scale skipped)
pub static BAT_FLYING: KfDef = KfDef {
    length: 0.5,
    looping: true,
    channels: &[
        KfChannel {
            part: "head",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.34906585, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "head",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, -2.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, -1.0, 0.0], catmullrom: false },
                KfFrame { t: 0.375, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.4583, v: [0.0, 1.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "body",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.698131701, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.916297857, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.698131701, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "body",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, -2.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, -1.0, 0.0], catmullrom: false },
                KfFrame { t: 0.375, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.4583, v: [0.0, 1.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "feet",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.174532925, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [-0.370882466, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [-0.218166156, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.174532925, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_wing",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 1.48352986, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, -0.959931089, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, 0.872664626, 0.0], catmullrom: false },
                KfFrame { t: 0.375, v: [0.0, 1.22173048, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, 1.48352986, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_wing_tip",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.183259571, 0.0], catmullrom: false },
                KfFrame { t: 0.0417, v: [0.0, 1.14319066, 0.0], catmullrom: false },
                KfFrame { t: 0.2083, v: [0.0, -2.35619449, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, 0.183259571, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_wing",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, -1.48352986, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, 0.959931089, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, -0.872664626, 0.0], catmullrom: false },
                KfFrame { t: 0.375, v: [0.0, -1.22173048, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, -1.48352986, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_wing_tip",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, -0.183259571, 0.0], catmullrom: false },
                KfFrame { t: 0.0417, v: [0.0, -1.14319066, 0.0], catmullrom: false },
                KfFrame { t: 0.2083, v: [0.0, 2.35619449, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, -0.183259571, 0.0], catmullrom: false },
            ],
        },
    ],
};

/// CREAKING_WALK (C:\Users\valtteri\AppData\Roaming\EwoClient\rewo\26.2\decompiled\net\minecraft\client\animation\definitions\CreakingAnimation.java | 8 channels, 0 scale skipped)
pub static CREAKING_WALK: KfDef = KfDef {
    length: 1.125,
    looping: true,
    channels: &[
        KfChannel {
            part: "upper_body",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.469147994, -0.408389592, -0.158154755], catmullrom: false },
                KfFrame { t: 0.125, v: [-0.0385595592, 0.10318212, 0.00117809725], catmullrom: false },
                KfFrame { t: 0.5417, v: [0.402783594, 0.249418022, 0.0804003373], catmullrom: false },
                KfFrame { t: 0.7083, v: [-0.174532925, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.875, v: [0.130899694, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.125, v: [0.469147994, -0.408389592, -0.158154755], catmullrom: false },
            ],
        },
        KfChannel {
            part: "head",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.0417, v: [-0.305432619, -1.09083078, 0.0], catmullrom: false },
                KfFrame { t: 0.0833, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.4167, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.4583, v: [0.0, 0.261799388, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0417, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0833, v: [-0.648445668, 1.41569066, -0.495012028], catmullrom: false },
                KfFrame { t: 1.125, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_arm",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.218166156, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [-0.558505361, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.875, v: [0.20943951, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.125, v: [-0.261799388, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_arm",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [-0.261799388, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.174532925, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5417, v: [-0.436332313, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [-0.158690572, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.7917, v: [-0.264190489, -1.16545757, 0.2436532], catmullrom: false },
                KfFrame { t: 0.8333, v: [-0.158690572, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.174532925, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.125, v: [-0.261799388, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.523598776, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.375, v: [0.870786652, -0.0668146944, 0.0561769126], catmullrom: false },
                KfFrame { t: 0.5, v: [0.305432619, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.625, v: [-0.987180914, -0.213633536, -0.152496398], catmullrom: false },
                KfFrame { t: 0.9167, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.125, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 2.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, -0.1846, 0.5979], catmullrom: false },
                KfFrame { t: 0.375, v: [0.0, 0.0665, -2.2177], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, -1.3563, -4.3474], catmullrom: false },
                KfFrame { t: 0.625, v: [0.0, -0.1047, -1.6556], catmullrom: false },
                KfFrame { t: 0.9167, v: [0.0, 0.0, -1.0], catmullrom: false },
                KfFrame { t: 1.125, v: [0.0, 0.0, 2.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.445591285, 0.197440372, 0.0934187482], catmullrom: false },
                KfFrame { t: 0.125, v: [-0.865034047, 0.128379438, 0.118565452], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.4583, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.9167, v: [0.523598776, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0417, v: [0.959931089, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.125, v: [0.445591285, 0.197440372, 0.0934187482], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, -0.9674, -3.6578], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, 0.2979, -0.9411], catmullrom: false },
                KfFrame { t: 0.25, v: [0.0, 0.3, -0.94], catmullrom: false },
                KfFrame { t: 0.4583, v: [0.0, 0.3, 1.06], catmullrom: false },
                KfFrame { t: 1.125, v: [0.0, -0.9674, -3.6578], catmullrom: false },
            ],
        },
    ],
};

/// COPPER_GOLEM_WALK (C:\Users\valtteri\AppData\Roaming\EwoClient\rewo\26.2\decompiled\net\minecraft\client\animation\definitions\CopperGolemAnimation.java | 6 channels, 0 scale skipped)
pub static COPPER_GOLEM_WALK: KfDef = KfDef {
    length: 0.8333,
    looping: true,
    channels: &[
        KfChannel {
            part: "body",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.174532925, 0.261799388, 0.0], catmullrom: true },
                KfFrame { t: 0.2083, v: [0.174532925, -0.032637657, -0.174532925], catmullrom: true },
                KfFrame { t: 0.4167, v: [0.174532925, -0.261799388, 0.0], catmullrom: true },
                KfFrame { t: 0.625, v: [0.174532925, -0.0143116999, 0.174532925], catmullrom: true },
                KfFrame { t: 0.8333, v: [0.174532925, 0.261799388, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "head",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [-0.174532925, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.2083, v: [-0.174532925, 0.032637657, 0.174532925], catmullrom: true },
                KfFrame { t: 0.4167, v: [-0.174532925, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.625, v: [-0.174532925, 0.0143116999, -0.174532925], catmullrom: true },
                KfFrame { t: 0.8333, v: [-0.174532925, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "right_arm",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [1.22173048, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.4167, v: [-1.3962634, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.8333, v: [1.22173048, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "left_arm",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [-1.3962634, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.4167, v: [1.22173048, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.8333, v: [-1.3962634, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "right_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [-1.04719755, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.4167, v: [1.04719755, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.8333, v: [-1.04719755, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "left_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [1.04719755, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.4167, v: [-1.04719755, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.8333, v: [1.04719755, 0.0, 0.0], catmullrom: true },
            ],
        },
    ],
};

/// COPPER_GOLEM_IDLE (C:\Users\valtteri\AppData\Roaming\EwoClient\rewo\26.2\decompiled\net\minecraft\client\animation\definitions\CopperGolemAnimation.java | 2 channels, 0 scale skipped)
pub static COPPER_GOLEM_IDLE: KfDef = KfDef {
    length: 3.5,
    looping: false,
    channels: &[
        KfChannel {
            part: "body",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, -0.610865238, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, -0.610865238, 0.0], catmullrom: false },
                KfFrame { t: 0.625, v: [0.0, 0.610865238, 0.0], catmullrom: false },
                KfFrame { t: 1.2083, v: [0.0, 0.610865238, 0.0], catmullrom: false },
                KfFrame { t: 2.7083, v: [0.0, 0.610865238, 0.0], catmullrom: false },
                KfFrame { t: 3.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 3.5, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "head",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.625, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.2083, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.5, v: [0.0, 5.23598776, 0.0], catmullrom: false },
                KfFrame { t: 1.6667, v: [0.0, 5.23598776, 0.0], catmullrom: false },
                KfFrame { t: 1.75, v: [-0.436332313, 5.23598776, 0.0], catmullrom: false },
                KfFrame { t: 2.7083, v: [-0.436332313, 5.23598776, 0.0], catmullrom: false },
                KfFrame { t: 3.0, v: [0.0, 6.28318531, 0.0], catmullrom: false },
                KfFrame { t: 3.5, v: [0.0, 6.28318531, 0.0], catmullrom: false },
            ],
        },
    ],
};

/// SWIMMING (C:\Users\valtteri\AppData\Roaming\EwoClient\rewo\26.2\decompiled\net\minecraft\client\animation\definitions\NautilusAnimation.java | 2 channels, 4 scale skipped)
pub static NAUTILUS_SWIMMING: KfDef = KfDef {
    length: 1.0,
    looping: true,
    channels: &[
        KfChannel {
            part: "upper_mouth",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [0.523598776, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.875, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "lower_mouth",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5, v: [-0.523598776, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.875, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
    ],
};

/// IDLE (C:\Users\valtteri\AppData\Roaming\EwoClient\rewo\26.2\decompiled\net\minecraft\client\animation\definitions\BreezeAnimation.java | 5 channels, 0 scale skipped)
pub static BREEZE_IDLE: KfDef = KfDef {
    length: 2.0,
    looping: true,
    channels: &[
        KfChannel {
            part: "wind_top",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.5, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [0.5, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 0.75, v: [-0.5, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 1.25, v: [-0.5, 0.0, 0.5], catmullrom: false },
                KfFrame { t: 1.75, v: [0.5, 0.0, 0.5], catmullrom: false },
                KfFrame { t: 2.0, v: [0.5, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "wind_mid",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.5, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 0.5, v: [-0.5, 0.0, -0.5], catmullrom: false },
                KfFrame { t: 1.0, v: [-0.5, 0.0, 0.5], catmullrom: false },
                KfFrame { t: 1.5, v: [0.5, 0.0, 0.5], catmullrom: false },
                KfFrame { t: 2.0, v: [0.5, 0.0, -0.5], catmullrom: false },
            ],
        },
        KfChannel {
            part: "head",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 1.0, v: [0.0, -1.0, 0.0], catmullrom: true },
                KfFrame { t: 2.0, v: [0.0, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "rods",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.0, 18.8495559, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "rods",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 1.0, v: [0.0, 1.0, 0.0], catmullrom: false },
                KfFrame { t: 2.0, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
    ],
};

/// HOP (C:\Users\valtteri\AppData\Roaming\EwoClient\rewo\26.2\decompiled\net\minecraft\client\animation\definitions\RabbitAnimation.java | 22 channels, 0 scale skipped)
pub static RABBIT_HOP: KfDef = KfDef {
    length: 0.75,
    looping: true,
    channels: &[
        KfChannel {
            part: "body",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.2083, v: [0.0698131701, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.2917, v: [0.567232007, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.4167, v: [0.575958653, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.5833, v: [0.314159265, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "body",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "head",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.2083, v: [-0.0698131701, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.2917, v: [-0.56147242, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.375, v: [-0.603534855, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5833, v: [-0.34906585, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "head",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.375, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "backlegs",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.25, v: [2.18166156, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.2917, v: [2.18166156, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.375, v: [2.0943951, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.4583, v: [1.65806279, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.5417, v: [0.733038286, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.6667, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "backlegs",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.6667, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "frontlegs",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [-0.00296705973, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [-0.00296705973, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.2083, v: [0.440695636, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.2917, v: [-1.13446401, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.4583, v: [-1.17809725, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.625, v: [-0.0218166156, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.749, v: [-0.0218166156, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "frontlegs",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.3333, v: [0.0, -0.5, 0.6], catmullrom: false },
                KfFrame { t: 0.4167, v: [0.0, -0.9, 0.4], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_front_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.125, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.2083, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.3333, v: [0.0, 0.0, -0.305432619], catmullrom: true },
                KfFrame { t: 0.5, v: [0.0, 0.0, -0.305432619], catmullrom: true },
                KfFrame { t: 0.5833, v: [0.0, 0.0, -0.034906585], catmullrom: true },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "right_front_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.2083, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_front_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.125, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.2083, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.3333, v: [0.0, 0.0, 0.34906585], catmullrom: true },
                KfFrame { t: 0.5, v: [0.0, 0.0, 0.34906585], catmullrom: true },
                KfFrame { t: 0.5833, v: [0.0, 0.0, 0.034906585], catmullrom: true },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "left_front_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.2083, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_ear",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.125, v: [0.0436332313, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.375, v: [-0.846484687, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.5417, v: [-0.719773784, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_ear",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [-0.025, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.2083, v: [-0.025, 0.2, 0.0], catmullrom: true },
                KfFrame { t: 0.375, v: [-0.02, 0.3, 0.0], catmullrom: true },
                KfFrame { t: 0.75, v: [-0.025, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "right_ear",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.125, v: [0.130899694, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.375, v: [-0.549778714, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.5, v: [-0.616624825, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "right_ear",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.025, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.2083, v: [0.025, 0.3, 0.0], catmullrom: true },
                KfFrame { t: 0.375, v: [0.02, 0.23, 0.0], catmullrom: true },
                KfFrame { t: 0.75, v: [0.025, 0.0, 0.0], catmullrom: true },
            ],
        },
        KfChannel {
            part: "right_hind_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, -0.0436332313, 0.0], catmullrom: false },
                KfFrame { t: 0.1667, v: [0.0, -0.0436332313, 0.0], catmullrom: false },
                KfFrame { t: 0.2083, v: [0.829031395, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.4167, v: [0.829031395, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.4583, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, -0.0436332313, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "right_hind_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.6667, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_hind_leg",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.1667, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.2083, v: [0.829031395, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.4167, v: [0.829031395, 0.0, 0.0], catmullrom: true },
                KfFrame { t: 0.4583, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "left_hind_leg",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.6667, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "tail",
            target: KfTarget::Rot,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.125, v: [-0.436332313, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.3333, v: [0.261799388, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.375, v: [0.479965544, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
        KfChannel {
            part: "tail",
            target: KfTarget::Pos,
            frames: &[
                KfFrame { t: 0.0, v: [0.0, 0.0, 0.0], catmullrom: false },
                KfFrame { t: 0.75, v: [0.0, 0.0, 0.0], catmullrom: false },
            ],
        },
    ],
};


