//! GENERATED by tools/gen_baby_textures.py - do not edit.
//!
//! Vanilla's `getTextureLocation` overrides that swap on `isBaby`,
//! extracted from the 26.2 decompile (nearest override wins up the
//! `extends` chain, fanned out over EntityRenderers' map). One row per
//! ENTITY NAME; the GPU side resolves the kind via
//! `mobs::kind_for_entity_name`, which keys kinds by the same short
//! name. Re-run after a version bump.
//!
//! Measured against this jar: 147 *baby*.png under
//! textures/entity, of which the plain-constant swaps this table
//! encodes cover 21; the rest belong to variant systems
//! Rewo cannot evaluate yet and are named in `EXCLUDED_REASON`.

/// One extracted swap: `entity` (no namespace), the BABY sheet's jar
/// path, the ADULT path it replaces (the slot the UV offset rides),
/// and the baby PNG's own dimensions.
#[derive(Clone, Copy, Debug)]
pub struct BabySwap {
    pub entity: &'static str,
    pub baby_key: &'static str,
    pub baby_path: &'static str,
    pub adult_path: &'static str,
    pub w: u32,
    pub h: u32,
}

/// Why an entity with a baby SHEET in the jar is absent from
/// [`BABY_SWAPS`] - suppression recorded, not silent.
pub static EXCLUDED_REASON: &[(&str, &str)] = &[
    ("axolotl", "renderer AxolotlRenderer mediates the baby sheet through a variant record"),
    ("bee", "renderer BeeRenderer mediates the baby sheet through a variant record"),
    ("chicken", "renderer ChickenRenderer mediates the baby sheet through a variant record"),
    ("cow", "renderer CowRenderer mediates the baby sheet through a variant record"),
    ("fox", "renderer FoxRenderer mediates the baby sheet through a variant record"),
    ("horse", "renderer HorseRenderer mediates the baby sheet through a variant record"),
    ("llama", "renderer LlamaRenderer mediates the baby sheet through a variant record"),
    ("mooshroom", "renderer MushroomCowRenderer mediates the baby sheet through a variant record"),
    ("panda", "renderer PandaRenderer mediates the baby sheet through a variant record"),
    ("pig", "renderer PigRenderer mediates the baby sheet through a variant record"),
    ("piglin", "renderer PiglinRenderer mediates the baby sheet through a variant record"),
    ("piglin_brute", "renderer PiglinRenderer mediates the baby sheet through a variant record"),
    ("rabbit", "renderer RabbitRenderer mediates the baby sheet through a variant record"),
    ("skeleton_horse", "renderer UndeadHorseRenderer mediates the baby sheet through a variant record"),
    ("strider", "renderer StriderRenderer mediates the baby sheet through a variant record"),
    ("trader_llama", "renderer LlamaRenderer mediates the baby sheet through a variant record"),
    ("zombie_horse", "renderer UndeadHorseRenderer mediates the baby sheet through a variant record"),
];

pub const BABY_SWAPS: &[BabySwap] = &[
    BabySwap {
        entity: "armadillo",
        baby_key: "armadillo_baby",
        baby_path: "textures/entity/armadillo/armadillo_baby.png",
        adult_path: "textures/entity/armadillo/armadillo.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "camel",
        baby_key: "camel_baby",
        baby_path: "textures/entity/camel/camel_baby.png",
        adult_path: "textures/entity/camel/camel.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "dolphin",
        baby_key: "dolphin_baby",
        baby_path: "textures/entity/dolphin/dolphin_baby.png",
        adult_path: "textures/entity/dolphin/dolphin.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "drowned",
        baby_key: "drowned_baby",
        baby_path: "textures/entity/zombie/drowned_baby.png",
        adult_path: "textures/entity/zombie/drowned.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "glow_squid",
        baby_key: "glow_squid_baby",
        baby_path: "textures/entity/squid/glow_squid_baby.png",
        adult_path: "textures/entity/squid/glow_squid.png",
        w: 32,
        h: 32,
    },
    BabySwap {
        entity: "goat",
        baby_key: "goat_baby",
        baby_path: "textures/entity/goat/goat_baby.png",
        adult_path: "textures/entity/goat/goat.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "happy_ghast",
        baby_key: "happy_ghast_baby",
        baby_path: "textures/entity/ghast/happy_ghast_baby.png",
        adult_path: "textures/entity/ghast/happy_ghast.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "hoglin",
        baby_key: "hoglin_baby",
        baby_path: "textures/entity/hoglin/hoglin_baby.png",
        adult_path: "textures/entity/hoglin/hoglin.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "husk",
        baby_key: "husk_baby",
        baby_path: "textures/entity/zombie/husk_baby.png",
        adult_path: "textures/entity/zombie/husk.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "nautilus",
        baby_key: "nautilus_baby",
        baby_path: "textures/entity/nautilus/nautilus_baby.png",
        adult_path: "textures/entity/nautilus/nautilus.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "ocelot",
        baby_key: "ocelot_baby",
        baby_path: "textures/entity/cat/ocelot_baby.png",
        adult_path: "textures/entity/cat/ocelot.png",
        w: 32,
        h: 32,
    },
    BabySwap {
        entity: "polar_bear",
        baby_key: "polar_bear_baby",
        baby_path: "textures/entity/bear/polarbear_baby.png",
        adult_path: "textures/entity/bear/polarbear.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "sheep",
        baby_key: "sheep_baby",
        baby_path: "textures/entity/sheep/sheep_baby.png",
        adult_path: "textures/entity/sheep/sheep.png",
        w: 64,
        h: 32,
    },
    BabySwap {
        entity: "sniffer",
        baby_key: "sniffer_baby",
        baby_path: "textures/entity/sniffer/snifflet.png",
        adult_path: "textures/entity/sniffer/sniffer.png",
        w: 128,
        h: 128,
    },
    BabySwap {
        entity: "sulfur_cube",
        baby_key: "sulfur_cube_baby",
        baby_path: "textures/entity/sulfur_cube/sulfur_cube_outer_small.png",
        adult_path: "textures/entity/sulfur_cube/sulfur_cube_outer.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "turtle",
        baby_key: "turtle_baby",
        baby_path: "textures/entity/turtle/turtle_baby.png",
        adult_path: "textures/entity/turtle/turtle.png",
        w: 16,
        h: 16,
    },
    BabySwap {
        entity: "villager",
        baby_key: "villager_baby",
        baby_path: "textures/entity/villager/villager_baby.png",
        adult_path: "textures/entity/villager/villager.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "zoglin",
        baby_key: "zoglin_baby",
        baby_path: "textures/entity/hoglin/zoglin_baby.png",
        adult_path: "textures/entity/hoglin/zoglin.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "zombie",
        baby_key: "zombie_baby",
        baby_path: "textures/entity/zombie/zombie_baby.png",
        adult_path: "textures/entity/zombie/zombie.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "zombie_villager",
        baby_key: "zombie_villager_baby",
        baby_path: "textures/entity/zombie_villager/zombie_villager_baby.png",
        adult_path: "textures/entity/zombie_villager/zombie_villager.png",
        w: 64,
        h: 64,
    },
    BabySwap {
        entity: "zombified_piglin",
        baby_key: "zombified_piglin_baby",
        baby_path: "textures/entity/piglin/zombified_piglin_baby.png",
        adult_path: "textures/entity/piglin/zombified_piglin.png",
        w: 64,
        h: 64,
    },
];

/// The row for an entity name, namespace prefix optional.
pub fn baby_swap_for_entity(name: &str) -> Option<&'static BabySwap> {
    let short = name.strip_prefix("minecraft:").unwrap_or(name);
    BABY_SWAPS.iter().find(|r| r.entity == short)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_sorted_by_entity_and_unique() {
        let mut names: Vec<_> = BABY_SWAPS.iter().map(|r| r.entity).collect();
        let sorted = names.clone();
        names.sort_unstable();
        assert_eq!(names, sorted, "rows must be sorted so a binary search can replace find");
        let uniq = sorted.len();
        names.dedup();
        assert_eq!(names.len(), uniq, "duplicate entity rows");
    }

    #[test]
    fn zombie_and_sheep_are_covered_and_bee_is_named() {
        assert!(baby_swap_for_entity("minecraft:zombie").is_some());
        assert_eq!(baby_swap_for_entity("zombie").unwrap().adult_path, "textures/entity/zombie/zombie.png");
        assert!(baby_swap_for_entity("sheep").is_some());
        assert!(
            EXCLUDED_REASON.iter().any(|(e, _)| *e == "bee"),
            "the bee's four state-combo sheets must stay a NAMED exclusion"
        );
    }
}
