//! `ItemTags.BEACON_PAYMENT_ITEMS` — GENERATED by
//! `tools/gen_beacon_payment.py`.
//!
//! Do not edit. Re-run the generator after a version bump.
//!
//! `BeaconMenu`'s payment slot is `mayPlace = itemStack.is(BEACON_PAYMENT_ITEMS)`,
//! and its `quickMoveStack` guard asks the same question, so this is the one
//! item fact the beacon's shift-click needs.
//!
//! Read out of the client jar's `data/minecraft/tags/item/beacon_payment_items.json`
//! — the vanilla datapack the jar carries — which is the same source `ItemTags.SPEARS`
//! (M19) and the enchantment tags (M42) come from. **The caveat those carry
//! applies here too:** a server datapack that retags this makes the table wrong
//! with no error anywhere, because a tag override arrives on `update_tags`
//! (decoded by M69, deliberately not plumbed into any consumer).

/// Every item in the tag, in the file's own order, 5 entries.
pub static BEACON_PAYMENT: &[&str] = &[
    "minecraft:netherite_ingot",
    "minecraft:emerald",
    "minecraft:diamond",
    "minecraft:gold_ingot",
    "minecraft:iron_ingot",
];

/// Whether an item id is accepted by a beacon's payment slot.
pub fn is_beacon_payment(name: &str) -> bool {
    BEACON_PAYMENT.contains(&name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_tag_is_the_five_vanilla_payment_metals() {
        // Pinned by name rather than by count: a version that adds a sixth
        // should fail here and be looked at, not silently widen the slot.
        assert_eq!(
            BEACON_PAYMENT,
            &[
                "minecraft:netherite_ingot",
                "minecraft:emerald",
                "minecraft:diamond",
                "minecraft:gold_ingot",
                "minecraft:iron_ingot",
            ]
        );
    }

    #[test]
    fn an_ordinary_item_is_not_payment() {
        // The negative matters more than the positive: `mayPlace` defaulting
        // to true is what would let a stick into the slot.
        assert!(!is_beacon_payment("minecraft:stick"));
        assert!(!is_beacon_payment("minecraft:iron_block"));
        assert!(!is_beacon_payment("minecraft:gold_nugget"));
        assert!(is_beacon_payment("minecraft:iron_ingot"));
    }
}
