//! GENERATED by `tools/gen_block_props.py` — do not edit.
//!
//! Source: decompiled 26.2 `Blocks.java`, block classes and
//! `data/minecraft/tags/block`. See the script header for the rules.

/// `Block.skipRendering` override kind: 1 = a same-block neighbour,
/// 2 = `IronBarsBlock`'s connected rule, 3 = same block on the Y axis.
pub const SKIP_RENDERING: &[(&str, u8)] = &[
    ("minecraft:black_stained_glass", 1),
    ("minecraft:black_stained_glass_pane", 2),
    ("minecraft:blue_ice", 1),
    ("minecraft:blue_stained_glass", 1),
    ("minecraft:blue_stained_glass_pane", 2),
    ("minecraft:brown_stained_glass", 1),
    ("minecraft:brown_stained_glass_pane", 2),
    ("minecraft:copper_bars", 2),
    ("minecraft:copper_grate", 1),
    ("minecraft:cyan_stained_glass", 1),
    ("minecraft:cyan_stained_glass_pane", 2),
    ("minecraft:exposed_copper_bars", 2),
    ("minecraft:exposed_copper_grate", 1),
    ("minecraft:frosted_ice", 1),
    ("minecraft:glass", 1),
    ("minecraft:glass_pane", 2),
    ("minecraft:gray_stained_glass", 1),
    ("minecraft:gray_stained_glass_pane", 2),
    ("minecraft:green_stained_glass", 1),
    ("minecraft:green_stained_glass_pane", 2),
    ("minecraft:honey_block", 1),
    ("minecraft:ice", 1),
    ("minecraft:iron_bars", 2),
    ("minecraft:light_blue_stained_glass", 1),
    ("minecraft:light_blue_stained_glass_pane", 2),
    ("minecraft:light_gray_stained_glass", 1),
    ("minecraft:light_gray_stained_glass_pane", 2),
    ("minecraft:lime_stained_glass", 1),
    ("minecraft:lime_stained_glass_pane", 2),
    ("minecraft:magenta_stained_glass", 1),
    ("minecraft:magenta_stained_glass_pane", 2),
    ("minecraft:mangrove_roots", 3),
    ("minecraft:orange_stained_glass", 1),
    ("minecraft:orange_stained_glass_pane", 2),
    ("minecraft:oxidized_copper_bars", 2),
    ("minecraft:oxidized_copper_grate", 1),
    ("minecraft:pink_stained_glass", 1),
    ("minecraft:pink_stained_glass_pane", 2),
    ("minecraft:powder_snow", 1),
    ("minecraft:purple_stained_glass", 1),
    ("minecraft:purple_stained_glass_pane", 2),
    ("minecraft:red_stained_glass", 1),
    ("minecraft:red_stained_glass_pane", 2),
    ("minecraft:slime_block", 1),
    ("minecraft:tinted_glass", 1),
    ("minecraft:waxed_copper_bars", 2),
    ("minecraft:waxed_copper_grate", 1),
    ("minecraft:waxed_exposed_copper_bars", 2),
    ("minecraft:waxed_exposed_copper_grate", 1),
    ("minecraft:waxed_oxidized_copper_bars", 2),
    ("minecraft:waxed_oxidized_copper_grate", 1),
    ("minecraft:waxed_weathered_copper_bars", 2),
    ("minecraft:waxed_weathered_copper_grate", 1),
    ("minecraft:weathered_copper_bars", 2),
    ("minecraft:weathered_copper_grate", 1),
    ("minecraft:white_stained_glass", 1),
    ("minecraft:white_stained_glass_pane", 2),
    ("minecraft:yellow_stained_glass", 1),
    ("minecraft:yellow_stained_glass_pane", 2),
];

/// `Properties.friction` (default 0.6).
pub const FRICTION: &[(&str, f32)] = &[
    ("minecraft:blue_ice", 0.989),
    ("minecraft:frosted_ice", 0.98),
    ("minecraft:ice", 0.98),
    ("minecraft:packed_ice", 0.98),
    ("minecraft:slime_block", 0.8),
];

/// `Properties.speedFactor` (default 1.0).
pub const SPEED_FACTOR: &[(&str, f32)] = &[
    ("minecraft:honey_block", 0.4),
    ("minecraft:soul_sand", 0.4),
];

/// `Properties.jumpFactor` (default 1.0).
pub const JUMP_FACTOR: &[(&str, f32)] = &[
    ("minecraft:honey_block", 0.5),
];

/// `makeStuckInBlock` multiplier from the block's `entityInside`.
pub const STUCK: &[(&str, [f64; 3])] = &[
    ("minecraft:cobweb", [0.25, 0.05f32 as f64, 0.25]),
    ("minecraft:powder_snow", [0.9f32 as f64, 1.5, 0.9f32 as f64]),
    ("minecraft:sweet_berry_bush", [0.8f32 as f64, 0.75, 0.8f32 as f64]),
];

/// Blocks whose class extends `TrapDoorBlock`.
pub const TRAPDOORS: &[&str] = &[
    "minecraft:acacia_trapdoor",
    "minecraft:bamboo_trapdoor",
    "minecraft:birch_trapdoor",
    "minecraft:cherry_trapdoor",
    "minecraft:copper_trapdoor",
    "minecraft:crimson_trapdoor",
    "minecraft:dark_oak_trapdoor",
    "minecraft:exposed_copper_trapdoor",
    "minecraft:iron_trapdoor",
    "minecraft:jungle_trapdoor",
    "minecraft:mangrove_trapdoor",
    "minecraft:oak_trapdoor",
    "minecraft:oxidized_copper_trapdoor",
    "minecraft:pale_oak_trapdoor",
    "minecraft:spruce_trapdoor",
    "minecraft:warped_trapdoor",
    "minecraft:waxed_copper_trapdoor",
    "minecraft:waxed_exposed_copper_trapdoor",
    "minecraft:waxed_oxidized_copper_trapdoor",
    "minecraft:waxed_weathered_copper_trapdoor",
    "minecraft:weathered_copper_trapdoor",
];

/// Blocks whose class extends `LadderBlock`.
pub const LADDERS: &[&str] = &[
    "minecraft:ladder",
];

/// Blocks whose class extends `FenceGateBlock`.
pub const FENCE_GATES: &[&str] = &[
    "minecraft:acacia_fence_gate",
    "minecraft:bamboo_fence_gate",
    "minecraft:birch_fence_gate",
    "minecraft:cherry_fence_gate",
    "minecraft:crimson_fence_gate",
    "minecraft:dark_oak_fence_gate",
    "minecraft:jungle_fence_gate",
    "minecraft:mangrove_fence_gate",
    "minecraft:oak_fence_gate",
    "minecraft:pale_oak_fence_gate",
    "minecraft:spruce_fence_gate",
    "minecraft:warped_fence_gate",
];

/// `#minecraft:climbable`, expanded.
pub const CLIMBABLE_TAG: &[&str] = &[
    "minecraft:cave_vines",
    "minecraft:cave_vines_plant",
    "minecraft:ladder",
    "minecraft:scaffolding",
    "minecraft:twisting_vines",
    "minecraft:twisting_vines_plant",
    "minecraft:vine",
    "minecraft:weeping_vines",
    "minecraft:weeping_vines_plant",
];

/// `#minecraft:bars`, expanded.
pub const BARS_TAG: &[&str] = &[
    "minecraft:copper_bars",
    "minecraft:exposed_copper_bars",
    "minecraft:iron_bars",
    "minecraft:oxidized_copper_bars",
    "minecraft:waxed_copper_bars",
    "minecraft:waxed_exposed_copper_bars",
    "minecraft:waxed_oxidized_copper_bars",
    "minecraft:waxed_weathered_copper_bars",
    "minecraft:weathered_copper_bars",
];

/// `#minecraft:fences`, expanded.
pub const FENCES_TAG: &[&str] = &[
    "minecraft:acacia_fence",
    "minecraft:bamboo_fence",
    "minecraft:birch_fence",
    "minecraft:cherry_fence",
    "minecraft:crimson_fence",
    "minecraft:dark_oak_fence",
    "minecraft:jungle_fence",
    "minecraft:mangrove_fence",
    "minecraft:nether_brick_fence",
    "minecraft:oak_fence",
    "minecraft:pale_oak_fence",
    "minecraft:spruce_fence",
    "minecraft:warped_fence",
];

/// `#minecraft:walls`, expanded.
pub const WALLS_TAG: &[&str] = &[
    "minecraft:andesite_wall",
    "minecraft:blackstone_wall",
    "minecraft:brick_wall",
    "minecraft:cinnabar_brick_wall",
    "minecraft:cinnabar_wall",
    "minecraft:cobbled_deepslate_wall",
    "minecraft:cobblestone_wall",
    "minecraft:deepslate_brick_wall",
    "minecraft:deepslate_tile_wall",
    "minecraft:diorite_wall",
    "minecraft:end_stone_brick_wall",
    "minecraft:granite_wall",
    "minecraft:mossy_cobblestone_wall",
    "minecraft:mossy_stone_brick_wall",
    "minecraft:mud_brick_wall",
    "minecraft:nether_brick_wall",
    "minecraft:polished_blackstone_brick_wall",
    "minecraft:polished_blackstone_wall",
    "minecraft:polished_cinnabar_wall",
    "minecraft:polished_deepslate_wall",
    "minecraft:polished_sulfur_wall",
    "minecraft:polished_tuff_wall",
    "minecraft:prismarine_wall",
    "minecraft:red_nether_brick_wall",
    "minecraft:red_sandstone_wall",
    "minecraft:resin_brick_wall",
    "minecraft:sandstone_wall",
    "minecraft:stone_brick_wall",
    "minecraft:sulfur_brick_wall",
    "minecraft:sulfur_wall",
    "minecraft:tuff_brick_wall",
    "minecraft:tuff_wall",
];

