//! GENERATED by `tools/gen_entity_pick.py` — do not edit.
//!
//! Source: the decompiled 26.2 client — `EntityTypes.java`
//! (`.sized(w, h)` per registration), `EntityType.java` (the builder's
//! own default dimensions), `EntityTypeIds.java`, and every
//! `isPickable()` declaration under `net/` walked against the
//! `class X extends Y` graph. Re-run after a version bump; the script
//! fails loud on an unparsed registration, an unattributed `.sized(`, an
//! `isPickable()` declarer with no rule, or an override body whose text
//! changed.
//!
//! 158 registered types. Rule census: Alive 119, AliveUnlessMarker 1, AliveUnlessSpectator 1, Always 7, Never 12, RedirectableProjectile 15, RedirectableProjectileNotInGround 3.

/// Registered entity types in this version — a runtime registry of a
/// different size means the pin has drifted.
pub const REGISTERED_TYPES: usize = 158;

/// `EntityType.Builder`'s own default, used by the 0 registration(s)
/// that call no `.sized(…)`.
pub const BUILDER_DEFAULT_SIZE: (f32, f32) = (0.6, 1.8);

/// Which `isPickable()` body a type inherits.
///
/// `EntitySelector.CAN_BE_PICKED` is `Entity::isPickable`, and the
/// default is **false** — so the interesting cases are the ones that are
/// *not* pickable, not the ones that are.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PickRule {
    /// `!this.isRemoved()` — `LivingEntity`, `PrimedTnt`,
    /// `FallingBlockEntity`, `AbstractBoat` and `AbstractMinecart`.
    Alive,

    /// `ArmorStand`: `super.isPickable() && !this.isMarker()`.
    AliveUnlessMarker,

    /// `Player`: `!this.isSpectator() && super.isPickable()`. A spectating
    /// player is never under anyone's crosshair.
    AliveUnlessSpectator,

    /// A flat `true` — `EndCrystal`, `Interaction`, `ShulkerBullet` and
    /// `BlockAttachedEntity` (item frames, paintings, leash knots).
    Always,

    /// `Entity.isPickable()` — a flat `false`, which is the **default** and
    /// therefore the answer for an item entity, an experience orb, a display,
    /// a lightning bolt and everything else that never overrode it. Also
    /// `EnderDragon`'s own override: the dragon's body is not pickable, only
    /// its (unregistered) `EnderDragonPart` hitboxes are.
    Never,

    /// `Projectile`: `this.is(EntityTypeTags.REDIRECTABLE_PROJECTILE)` — a
    /// **tag**, resolved from the client jar's data pack, not from this table.
    RedirectableProjectile,

    /// `AbstractArrow`: `super.isPickable() && !this.isInGround()`, so an
    /// arrow must be in the tag *and* still in flight.
    RedirectableProjectileNotInGround,
}

/// `(registry name, width, height, pick rule)` for every registered
/// type. Width and height are `EntityType.Builder.sized(w, h)`, the
/// arguments to `EntityDimensions.scalable`; the bounding box they make
/// is `AABB(x - w/2, y, z - w/2, x + w/2, y + h, z + w/2)`.
pub const ENTITY_PICK: &[(&str, f32, f32, PickRule)] = &[
    ("minecraft:acacia_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:acacia_chest_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:allay", 0.35, 0.6, PickRule::Alive), // LivingEntity
    ("minecraft:area_effect_cloud", 6.0, 0.5, PickRule::Never), // Entity
    ("minecraft:armadillo", 0.7, 0.65, PickRule::Alive), // LivingEntity
    ("minecraft:armor_stand", 0.5, 1.975, PickRule::AliveUnlessMarker), // ArmorStand
    ("minecraft:arrow", 0.5, 0.5, PickRule::RedirectableProjectileNotInGround), // AbstractArrow
    ("minecraft:axolotl", 0.75, 0.42, PickRule::Alive), // LivingEntity
    ("minecraft:bamboo_chest_raft", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:bamboo_raft", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:bat", 0.5, 0.9, PickRule::Alive), // LivingEntity
    ("minecraft:bee", 0.55, 0.5, PickRule::Alive), // LivingEntity
    ("minecraft:birch_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:birch_chest_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:blaze", 0.6, 1.8, PickRule::Alive), // LivingEntity
    ("minecraft:block_display", 0.0, 0.0, PickRule::Never), // Entity
    ("minecraft:bogged", 0.6, 1.99, PickRule::Alive), // LivingEntity
    ("minecraft:breeze", 0.6, 1.77, PickRule::Alive), // LivingEntity
    ("minecraft:breeze_wind_charge", 0.3125, 0.3125, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:camel", 1.7, 2.375, PickRule::Alive), // LivingEntity
    ("minecraft:camel_husk", 1.7, 2.375, PickRule::Alive), // LivingEntity
    ("minecraft:cat", 0.6, 0.7, PickRule::Alive), // LivingEntity
    ("minecraft:cave_spider", 0.7, 0.5, PickRule::Alive), // LivingEntity
    ("minecraft:cherry_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:cherry_chest_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:chest_minecart", 0.98, 0.7, PickRule::Alive), // AbstractMinecart
    ("minecraft:chicken", 0.4, 0.7, PickRule::Alive), // LivingEntity
    ("minecraft:cod", 0.5, 0.3, PickRule::Alive), // LivingEntity
    ("minecraft:command_block_minecart", 0.98, 0.7, PickRule::Alive), // AbstractMinecart
    ("minecraft:copper_golem", 0.49, 0.98, PickRule::Alive), // LivingEntity
    ("minecraft:cow", 0.9, 1.4, PickRule::Alive), // LivingEntity
    ("minecraft:creaking", 0.9, 2.7, PickRule::Alive), // LivingEntity
    ("minecraft:creeper", 0.6, 1.7, PickRule::Alive), // LivingEntity
    ("minecraft:dark_oak_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:dark_oak_chest_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:dolphin", 0.9, 0.6, PickRule::Alive), // LivingEntity
    ("minecraft:donkey", 1.3964844, 1.5, PickRule::Alive), // LivingEntity
    ("minecraft:dragon_fireball", 1.0, 1.0, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:drowned", 0.6, 1.95, PickRule::Alive), // LivingEntity
    ("minecraft:egg", 0.25, 0.25, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:elder_guardian", 1.9975, 1.9975, PickRule::Alive), // LivingEntity
    ("minecraft:end_crystal", 2.0, 2.0, PickRule::Always), // EndCrystal
    ("minecraft:ender_dragon", 16.0, 8.0, PickRule::Never), // EnderDragon
    ("minecraft:ender_pearl", 0.25, 0.25, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:enderman", 0.6, 2.9, PickRule::Alive), // LivingEntity
    ("minecraft:endermite", 0.4, 0.3, PickRule::Alive), // LivingEntity
    ("minecraft:evoker", 0.6, 1.95, PickRule::Alive), // LivingEntity
    ("minecraft:evoker_fangs", 0.5, 0.8, PickRule::Never), // Entity
    ("minecraft:experience_bottle", 0.25, 0.25, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:experience_orb", 0.5, 0.5, PickRule::Never), // Entity
    ("minecraft:eye_of_ender", 0.25, 0.25, PickRule::Never), // Entity
    ("minecraft:falling_block", 0.98, 0.98, PickRule::Alive), // FallingBlockEntity
    ("minecraft:fireball", 1.0, 1.0, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:firework_rocket", 0.25, 0.25, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:fishing_bobber", 0.25, 0.25, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:fox", 0.6, 0.7, PickRule::Alive), // LivingEntity
    ("minecraft:frog", 0.5, 0.5, PickRule::Alive), // LivingEntity
    ("minecraft:furnace_minecart", 0.98, 0.7, PickRule::Alive), // AbstractMinecart
    ("minecraft:ghast", 4.0, 4.0, PickRule::Alive), // LivingEntity
    ("minecraft:giant", 3.6, 12.0, PickRule::Alive), // LivingEntity
    ("minecraft:glow_item_frame", 0.5, 0.5, PickRule::Always), // BlockAttachedEntity
    ("minecraft:glow_squid", 0.8, 0.8, PickRule::Alive), // LivingEntity
    ("minecraft:goat", 0.9, 1.3, PickRule::Alive), // LivingEntity
    ("minecraft:guardian", 0.85, 0.85, PickRule::Alive), // LivingEntity
    ("minecraft:happy_ghast", 4.0, 4.0, PickRule::Alive), // LivingEntity
    ("minecraft:hoglin", 1.3964844, 1.4, PickRule::Alive), // LivingEntity
    ("minecraft:hopper_minecart", 0.98, 0.7, PickRule::Alive), // AbstractMinecart
    ("minecraft:horse", 1.3964844, 1.6, PickRule::Alive), // LivingEntity
    ("minecraft:husk", 0.6, 1.95, PickRule::Alive), // LivingEntity
    ("minecraft:illusioner", 0.6, 1.95, PickRule::Alive), // LivingEntity
    ("minecraft:interaction", 0.0, 0.0, PickRule::Always), // Interaction
    ("minecraft:iron_golem", 1.4, 2.7, PickRule::Alive), // LivingEntity
    ("minecraft:item", 0.25, 0.25, PickRule::Never), // Entity
    ("minecraft:item_display", 0.0, 0.0, PickRule::Never), // Entity
    ("minecraft:item_frame", 0.5, 0.5, PickRule::Always), // BlockAttachedEntity
    ("minecraft:jungle_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:jungle_chest_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:leash_knot", 0.375, 0.5, PickRule::Always), // BlockAttachedEntity
    ("minecraft:lightning_bolt", 0.0, 0.0, PickRule::Never), // Entity
    ("minecraft:lingering_potion", 0.25, 0.25, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:llama", 0.9, 1.87, PickRule::Alive), // LivingEntity
    ("minecraft:llama_spit", 0.25, 0.25, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:magma_cube", 0.52, 0.52, PickRule::Alive), // LivingEntity
    ("minecraft:mangrove_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:mangrove_chest_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:mannequin", 0.6, 1.8, PickRule::Alive), // LivingEntity
    ("minecraft:marker", 0.0, 0.0, PickRule::Never), // Entity
    ("minecraft:minecart", 0.98, 0.7, PickRule::Alive), // AbstractMinecart
    ("minecraft:mooshroom", 0.9, 1.4, PickRule::Alive), // LivingEntity
    ("minecraft:mule", 1.3964844, 1.6, PickRule::Alive), // LivingEntity
    ("minecraft:nautilus", 0.875, 0.95, PickRule::Alive), // LivingEntity
    ("minecraft:oak_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:oak_chest_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:ocelot", 0.6, 0.7, PickRule::Alive), // LivingEntity
    ("minecraft:ominous_item_spawner", 0.25, 0.25, PickRule::Never), // Entity
    ("minecraft:painting", 0.5, 0.5, PickRule::Always), // BlockAttachedEntity
    ("minecraft:pale_oak_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:pale_oak_chest_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:panda", 1.3, 1.25, PickRule::Alive), // LivingEntity
    ("minecraft:parched", 0.6, 1.99, PickRule::Alive), // LivingEntity
    ("minecraft:parrot", 0.5, 0.9, PickRule::Alive), // LivingEntity
    ("minecraft:phantom", 0.9, 0.5, PickRule::Alive), // LivingEntity
    ("minecraft:pig", 0.9, 0.9, PickRule::Alive), // LivingEntity
    ("minecraft:piglin", 0.6, 1.95, PickRule::Alive), // LivingEntity
    ("minecraft:piglin_brute", 0.6, 1.95, PickRule::Alive), // LivingEntity
    ("minecraft:pillager", 0.6, 1.95, PickRule::Alive), // LivingEntity
    ("minecraft:player", 0.6, 1.8, PickRule::AliveUnlessSpectator), // Player
    ("minecraft:polar_bear", 1.4, 1.4, PickRule::Alive), // LivingEntity
    ("minecraft:pufferfish", 0.7, 0.7, PickRule::Alive), // LivingEntity
    ("minecraft:rabbit", 0.49, 0.6, PickRule::Alive), // LivingEntity
    ("minecraft:ravager", 1.95, 2.2, PickRule::Alive), // LivingEntity
    ("minecraft:salmon", 0.7, 0.4, PickRule::Alive), // LivingEntity
    ("minecraft:sheep", 0.9, 1.3, PickRule::Alive), // LivingEntity
    ("minecraft:shulker", 1.0, 1.0, PickRule::Alive), // LivingEntity
    ("minecraft:shulker_bullet", 0.3125, 0.3125, PickRule::Always), // ShulkerBullet
    ("minecraft:silverfish", 0.4, 0.3, PickRule::Alive), // LivingEntity
    ("minecraft:skeleton", 0.6, 1.99, PickRule::Alive), // LivingEntity
    ("minecraft:skeleton_horse", 1.3964844, 1.6, PickRule::Alive), // LivingEntity
    ("minecraft:slime", 0.52, 0.52, PickRule::Alive), // LivingEntity
    ("minecraft:small_fireball", 0.3125, 0.3125, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:sniffer", 1.9, 1.75, PickRule::Alive), // LivingEntity
    ("minecraft:snow_golem", 0.7, 1.9, PickRule::Alive), // LivingEntity
    ("minecraft:snowball", 0.25, 0.25, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:spawner_minecart", 0.98, 0.7, PickRule::Alive), // AbstractMinecart
    ("minecraft:spectral_arrow", 0.5, 0.5, PickRule::RedirectableProjectileNotInGround), // AbstractArrow
    ("minecraft:spider", 1.4, 0.9, PickRule::Alive), // LivingEntity
    ("minecraft:splash_potion", 0.25, 0.25, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:spruce_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:spruce_chest_boat", 1.375, 0.5625, PickRule::Alive), // AbstractBoat
    ("minecraft:squid", 0.8, 0.8, PickRule::Alive), // LivingEntity
    ("minecraft:stray", 0.6, 1.99, PickRule::Alive), // LivingEntity
    ("minecraft:strider", 0.9, 1.7, PickRule::Alive), // LivingEntity
    ("minecraft:sulfur_cube", 0.49, 0.49, PickRule::Alive), // LivingEntity
    ("minecraft:tadpole", 0.4, 0.3, PickRule::Alive), // LivingEntity
    ("minecraft:text_display", 0.0, 0.0, PickRule::Never), // Entity
    ("minecraft:tnt", 0.98, 0.98, PickRule::Alive), // PrimedTnt
    ("minecraft:tnt_minecart", 0.98, 0.7, PickRule::Alive), // AbstractMinecart
    ("minecraft:trader_llama", 0.9, 1.87, PickRule::Alive), // LivingEntity
    ("minecraft:trident", 0.5, 0.5, PickRule::RedirectableProjectileNotInGround), // AbstractArrow
    ("minecraft:tropical_fish", 0.5, 0.4, PickRule::Alive), // LivingEntity
    ("minecraft:turtle", 1.2, 0.4, PickRule::Alive), // LivingEntity
    ("minecraft:vex", 0.4, 0.8, PickRule::Alive), // LivingEntity
    ("minecraft:villager", 0.6, 1.95, PickRule::Alive), // LivingEntity
    ("minecraft:vindicator", 0.6, 1.95, PickRule::Alive), // LivingEntity
    ("minecraft:wandering_trader", 0.6, 1.95, PickRule::Alive), // LivingEntity
    ("minecraft:warden", 0.9, 2.9, PickRule::Alive), // LivingEntity
    ("minecraft:wind_charge", 0.3125, 0.3125, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:witch", 0.6, 1.95, PickRule::Alive), // LivingEntity
    ("minecraft:wither", 0.9, 3.5, PickRule::Alive), // LivingEntity
    ("minecraft:wither_skeleton", 0.7, 2.4, PickRule::Alive), // LivingEntity
    ("minecraft:wither_skull", 0.3125, 0.3125, PickRule::RedirectableProjectile), // Projectile
    ("minecraft:wolf", 0.6, 0.85, PickRule::Alive), // LivingEntity
    ("minecraft:zoglin", 1.3964844, 1.4, PickRule::Alive), // LivingEntity
    ("minecraft:zombie", 0.6, 1.95, PickRule::Alive), // LivingEntity
    ("minecraft:zombie_horse", 1.3964844, 1.6, PickRule::Alive), // LivingEntity
    ("minecraft:zombie_nautilus", 0.875, 0.95, PickRule::Alive), // LivingEntity
    ("minecraft:zombie_villager", 0.6, 1.95, PickRule::Alive), // LivingEntity
    ("minecraft:zombified_piglin", 0.6, 1.95, PickRule::Alive), // LivingEntity
];
