//! GENERATED by `tools/gen_entity_classes.py` — do not edit.
//!
//! Source: the decompiled 26.2 client
//! (`EntityTypes.java` + `EntityTypeIds.java` + every `class X extends Y`
//! declaration under `net/`). Re-run after a version bump; the script
//! fails loud on an unparsed registration, an unresolved id constant, a
//! broken `extends` chain, or a change in the `updateSwingTime()` call
//! sites this table is derived from.
//!
//! 158 registered types, 93 living, 36 swing-ticking.

/// Registered entity types in this version — a runtime registry of a
/// different size means the pin has drifted.
pub const REGISTERED_TYPES: usize = 158;

/// The client call sites `SWING_TICKING` was derived from, recorded so a
/// reader can re-check the claim without re-running the generator.
pub const SWING_TICK_CALL_SITES: &[&str] = &[
    "net/minecraft/client/player/RemotePlayer.java",
    "net/minecraft/world/entity/decoration/Mannequin.java",
    "net/minecraft/world/entity/monster/Monster.java",
    "net/minecraft/world/entity/player/Player.java",
];

/// Registry names whose implementation class descends from
/// `LivingEntity`. `handleAnimate` casts to it, `handleSetEquipment` and
/// `handleUpdateMobEffect` test `instanceof` it — anything else is inert.
pub const LIVING: &[&str] = &[
    "minecraft:allay",
    "minecraft:armadillo",
    "minecraft:armor_stand",
    "minecraft:axolotl",
    "minecraft:bat",
    "minecraft:bee",
    "minecraft:blaze",
    "minecraft:bogged",
    "minecraft:breeze",
    "minecraft:camel",
    "minecraft:camel_husk",
    "minecraft:cat",
    "minecraft:cave_spider",
    "minecraft:chicken",
    "minecraft:cod",
    "minecraft:copper_golem",
    "minecraft:cow",
    "minecraft:creaking",
    "minecraft:creeper",
    "minecraft:dolphin",
    "minecraft:donkey",
    "minecraft:drowned",
    "minecraft:elder_guardian",
    "minecraft:ender_dragon",
    "minecraft:enderman",
    "minecraft:endermite",
    "minecraft:evoker",
    "minecraft:fox",
    "minecraft:frog",
    "minecraft:ghast",
    "minecraft:giant",
    "minecraft:glow_squid",
    "minecraft:goat",
    "minecraft:guardian",
    "minecraft:happy_ghast",
    "minecraft:hoglin",
    "minecraft:horse",
    "minecraft:husk",
    "minecraft:illusioner",
    "minecraft:iron_golem",
    "minecraft:llama",
    "minecraft:magma_cube",
    "minecraft:mannequin",
    "minecraft:mooshroom",
    "minecraft:mule",
    "minecraft:nautilus",
    "minecraft:ocelot",
    "minecraft:panda",
    "minecraft:parched",
    "minecraft:parrot",
    "minecraft:phantom",
    "minecraft:pig",
    "minecraft:piglin",
    "minecraft:piglin_brute",
    "minecraft:pillager",
    "minecraft:player",
    "minecraft:polar_bear",
    "minecraft:pufferfish",
    "minecraft:rabbit",
    "minecraft:ravager",
    "minecraft:salmon",
    "minecraft:sheep",
    "minecraft:shulker",
    "minecraft:silverfish",
    "minecraft:skeleton",
    "minecraft:skeleton_horse",
    "minecraft:slime",
    "minecraft:sniffer",
    "minecraft:snow_golem",
    "minecraft:spider",
    "minecraft:squid",
    "minecraft:stray",
    "minecraft:strider",
    "minecraft:sulfur_cube",
    "minecraft:tadpole",
    "minecraft:trader_llama",
    "minecraft:tropical_fish",
    "minecraft:turtle",
    "minecraft:vex",
    "minecraft:villager",
    "minecraft:vindicator",
    "minecraft:wandering_trader",
    "minecraft:warden",
    "minecraft:witch",
    "minecraft:wither",
    "minecraft:wither_skeleton",
    "minecraft:wolf",
    "minecraft:zoglin",
    "minecraft:zombie",
    "minecraft:zombie_horse",
    "minecraft:zombie_nautilus",
    "minecraft:zombie_villager",
    "minecraft:zombified_piglin",
];

/// Registry names whose **client** class runs
/// `LivingEntity.updateSwingTime()` every tick — a `Monster`, `Player` or
/// `Mannequin` descendant. Every other living entity can accept a swing
/// and never advance it, exactly as vanilla does.
pub const SWING_TICKING: &[&str] = &[
    "minecraft:blaze",
    "minecraft:bogged",
    "minecraft:breeze",
    "minecraft:cave_spider",
    "minecraft:creaking",
    "minecraft:creeper",
    "minecraft:drowned",
    "minecraft:elder_guardian",
    "minecraft:enderman",
    "minecraft:endermite",
    "minecraft:evoker",
    "minecraft:giant",
    "minecraft:guardian",
    "minecraft:husk",
    "minecraft:illusioner",
    "minecraft:mannequin",
    "minecraft:parched",
    "minecraft:piglin",
    "minecraft:piglin_brute",
    "minecraft:pillager",
    "minecraft:player",
    "minecraft:ravager",
    "minecraft:silverfish",
    "minecraft:skeleton",
    "minecraft:spider",
    "minecraft:stray",
    "minecraft:vex",
    "minecraft:vindicator",
    "minecraft:warden",
    "minecraft:witch",
    "minecraft:wither",
    "minecraft:wither_skeleton",
    "minecraft:zoglin",
    "minecraft:zombie",
    "minecraft:zombie_villager",
    "minecraft:zombified_piglin",
];

/// Registry names whose class descends from `Mob`, which introduces
/// `DATA_MOB_FLAGS_ID` at **index 15, BYTE** (bit 1 no-AI, bit 2
/// left-handed, bit 4 aggressive). `ArmorStand.DATA_CLIENT_FLAGS` is also
/// a BYTE at 15 and means something else entirely, so the flags byte may
/// only be read for a type in this set.
pub const MOB: &[&str] = &[
    "minecraft:allay",
    "minecraft:armadillo",
    "minecraft:axolotl",
    "minecraft:bat",
    "minecraft:bee",
    "minecraft:blaze",
    "minecraft:bogged",
    "minecraft:breeze",
    "minecraft:camel",
    "minecraft:camel_husk",
    "minecraft:cat",
    "minecraft:cave_spider",
    "minecraft:chicken",
    "minecraft:cod",
    "minecraft:copper_golem",
    "minecraft:cow",
    "minecraft:creaking",
    "minecraft:creeper",
    "minecraft:dolphin",
    "minecraft:donkey",
    "minecraft:drowned",
    "minecraft:elder_guardian",
    "minecraft:ender_dragon",
    "minecraft:enderman",
    "minecraft:endermite",
    "minecraft:evoker",
    "minecraft:fox",
    "minecraft:frog",
    "minecraft:ghast",
    "minecraft:giant",
    "minecraft:glow_squid",
    "minecraft:goat",
    "minecraft:guardian",
    "minecraft:happy_ghast",
    "minecraft:hoglin",
    "minecraft:horse",
    "minecraft:husk",
    "minecraft:illusioner",
    "minecraft:iron_golem",
    "minecraft:llama",
    "minecraft:magma_cube",
    "minecraft:mooshroom",
    "minecraft:mule",
    "minecraft:nautilus",
    "minecraft:ocelot",
    "minecraft:panda",
    "minecraft:parched",
    "minecraft:parrot",
    "minecraft:phantom",
    "minecraft:pig",
    "minecraft:piglin",
    "minecraft:piglin_brute",
    "minecraft:pillager",
    "minecraft:polar_bear",
    "minecraft:pufferfish",
    "minecraft:rabbit",
    "minecraft:ravager",
    "minecraft:salmon",
    "minecraft:sheep",
    "minecraft:shulker",
    "minecraft:silverfish",
    "minecraft:skeleton",
    "minecraft:skeleton_horse",
    "minecraft:slime",
    "minecraft:sniffer",
    "minecraft:snow_golem",
    "minecraft:spider",
    "minecraft:squid",
    "minecraft:stray",
    "minecraft:strider",
    "minecraft:sulfur_cube",
    "minecraft:tadpole",
    "minecraft:trader_llama",
    "minecraft:tropical_fish",
    "minecraft:turtle",
    "minecraft:vex",
    "minecraft:villager",
    "minecraft:vindicator",
    "minecraft:wandering_trader",
    "minecraft:warden",
    "minecraft:witch",
    "minecraft:wither",
    "minecraft:wither_skeleton",
    "minecraft:wolf",
    "minecraft:zoglin",
    "minecraft:zombie",
    "minecraft:zombie_horse",
    "minecraft:zombie_nautilus",
    "minecraft:zombie_villager",
    "minecraft:zombified_piglin",
];

/// Registry names whose class descends from `Raider`, which introduces
/// `IS_CELEBRATING` at **index 16 with the BOOLEAN serializer** — the same
/// slot and serializer as `AgeableMob`/`Zombie.DATA_BABY_ID` and
/// `Allay.DATA_DANCING`. The byte parser cannot separate them; only the
/// entity kind can, which is why this set exists.
pub const RAIDER: &[&str] = &[
    "minecraft:evoker",
    "minecraft:illusioner",
    "minecraft:pillager",
    "minecraft:ravager",
    "minecraft:vindicator",
    "minecraft:witch",
];

/// Registry names whose class descends from `SpellcasterIllager`, which
/// introduces `DATA_SPELL_CASTING_ID` at **index 17, BYTE**. Non-zero means
/// `isCastingSpell()`, which selects the SPELLCASTING arm pose.
pub const SPELLCASTER_ILLAGER: &[&str] = &[
    "minecraft:evoker",
    "minecraft:illusioner",
];

/// Registry names whose class descends from `AbstractIllager` — the models
/// that run `IllagerModel.setupAnim`'s arm-pose switch rather than the
/// humanoid/undead rigs.
pub const ILLAGER: &[&str] = &[
    "minecraft:evoker",
    "minecraft:illusioner",
    "minecraft:pillager",
    "minecraft:vindicator",
];

/// Registry names whose class descends from `Player`. Death entity-event 3
/// runs `if (!(this instanceof Player)) { setHealth(0); die(...); }`, so a
/// player must be excluded from the client-side kill. `Mannequin` shares
/// the `Avatar` base but is NOT a `Player`, which is exactly the
/// distinction a hand-written 'is it the player type id' check would miss.
pub const PLAYER: &[&str] = &[
    "minecraft:player",
];

/// Registry names whose class descends from `Animal`. Both `AbstractBoat`
/// and `Camel` bump a *second* passenger's seat offset by `+0.2` when
/// `passenger instanceof Animal`, so this set is read of the **rider**,
/// not the vehicle.
pub const ANIMAL: &[&str] = &[
    "minecraft:armadillo",
    "minecraft:axolotl",
    "minecraft:bee",
    "minecraft:camel",
    "minecraft:camel_husk",
    "minecraft:cat",
    "minecraft:chicken",
    "minecraft:cow",
    "minecraft:donkey",
    "minecraft:fox",
    "minecraft:frog",
    "minecraft:goat",
    "minecraft:happy_ghast",
    "minecraft:hoglin",
    "minecraft:horse",
    "minecraft:llama",
    "minecraft:mooshroom",
    "minecraft:mule",
    "minecraft:nautilus",
    "minecraft:ocelot",
    "minecraft:panda",
    "minecraft:parrot",
    "minecraft:pig",
    "minecraft:polar_bear",
    "minecraft:rabbit",
    "minecraft:sheep",
    "minecraft:skeleton_horse",
    "minecraft:sniffer",
    "minecraft:strider",
    "minecraft:trader_llama",
    "minecraft:turtle",
    "minecraft:wolf",
    "minecraft:zombie_horse",
    "minecraft:zombie_nautilus",
];

/// Registry names whose class descends from `AbstractBoat`, which
/// **fully replaces** `getPassengerAttachmentPoint` — a boat ignores its
/// own declared PASSENGER points entirely and computes
/// `(0, rideHeight(dimensions), xOffset)`.
pub const ABSTRACT_BOAT: &[&str] = &[
    "minecraft:acacia_boat",
    "minecraft:acacia_chest_boat",
    "minecraft:bamboo_chest_raft",
    "minecraft:bamboo_raft",
    "minecraft:birch_boat",
    "minecraft:birch_chest_boat",
    "minecraft:cherry_boat",
    "minecraft:cherry_chest_boat",
    "minecraft:dark_oak_boat",
    "minecraft:dark_oak_chest_boat",
    "minecraft:jungle_boat",
    "minecraft:jungle_chest_boat",
    "minecraft:mangrove_boat",
    "minecraft:mangrove_chest_boat",
    "minecraft:oak_boat",
    "minecraft:oak_chest_boat",
    "minecraft:pale_oak_boat",
    "minecraft:pale_oak_chest_boat",
    "minecraft:spruce_boat",
    "minecraft:spruce_chest_boat",
];

/// Registry names whose class descends from `AbstractChestBoat`, which
/// overrides `getSinglePassengerXOffset()` to **0.15** against
/// `AbstractBoat`'s 0.0 — the chest takes the stern, so the lone
/// passenger shifts forward.
pub const ABSTRACT_CHEST_BOAT: &[&str] = &[
    "minecraft:acacia_chest_boat",
    "minecraft:bamboo_chest_raft",
    "minecraft:birch_chest_boat",
    "minecraft:cherry_chest_boat",
    "minecraft:dark_oak_chest_boat",
    "minecraft:jungle_chest_boat",
    "minecraft:mangrove_chest_boat",
    "minecraft:oak_chest_boat",
    "minecraft:pale_oak_chest_boat",
    "minecraft:spruce_chest_boat",
];

/// Registry names whose class is `Raft`. `rideHeight` is
/// `height * 0.8888889` here against `Boat`/`ChestBoat`'s `height / 3`,
/// and the split does **not** follow the chest/non-chest one: `Raft`
/// extends `AbstractBoat` while `ChestRaft` extends `AbstractChestBoat`,
/// so the two raft leaves must be named separately.
pub const RAFT: &[&str] = &[
    "minecraft:bamboo_raft",
];

/// Registry names whose class is `ChestRaft` — the other half of the
/// raft `rideHeight`, see `RAFT`.
pub const CHEST_RAFT: &[&str] = &[
    "minecraft:bamboo_chest_raft",
];

/// Registry names whose class descends from `AbstractMinecart`, which
/// lowers the attachment to `Vec3.ZERO` for a `Villager` or
/// `WanderingTrader` passenger and otherwise defers to the default.
pub const ABSTRACT_MINECART: &[&str] = &[
    "minecraft:chest_minecart",
    "minecraft:command_block_minecart",
    "minecraft:furnace_minecart",
    "minecraft:hopper_minecart",
    "minecraft:minecart",
    "minecraft:spawner_minecart",
    "minecraft:tnt_minecart",
];

/// Registry names whose class descends from `Villager` — half of the
/// `AbstractMinecart` lowered-attachment test, read of the **rider**.
pub const VILLAGER: &[&str] = &[
    "minecraft:villager",
];

/// Registry names whose class descends from `WanderingTrader` — the other
/// half of the `AbstractMinecart` lowered-attachment test. It is a
/// sibling of `Villager` under `AbstractVillager`, not a subclass, so
/// testing one does not cover the other.
pub const WANDERING_TRADER: &[&str] = &[
    "minecraft:wandering_trader",
];

/// Registry names whose class descends from `AbstractCubeMob` (slime,
/// magma cube), which replaces the attachment with
/// `height - 0.015625 * size * scale` — the only override that reads the
/// synced size.
pub const ABSTRACT_CUBE_MOB: &[&str] = &[
    "minecraft:magma_cube",
    "minecraft:slime",
    "minecraft:sulfur_cube",
];

/// Registry names whose class descends from `Spider`, the only type that
/// overrides `getVehicleAttachmentPoint` — read of the **rider**, and
/// conditional on the vehicle being no wider than the spider.
pub const SPIDER: &[&str] = &[
    "minecraft:cave_spider",
    "minecraft:spider",
];

/// Registry names whose class is `Strider`, whose attachment adds a
/// **client-only** walk-animation bob on top of the default.
pub const STRIDER: &[&str] = &[
    "minecraft:strider",
];

/// Registry names whose class descends from `AbstractHorse`. Its
/// `positionRider` copies `yBodyRot` onto a living passenger, and its
/// `getPassengerAttachmentPoint` adds a rearing offset scaled by
/// `standAnimO` (zero at rest).
pub const ABSTRACT_HORSE: &[&str] = &[
    "minecraft:camel",
    "minecraft:camel_husk",
    "minecraft:donkey",
    "minecraft:horse",
    "minecraft:llama",
    "minecraft:mule",
    "minecraft:skeleton_horse",
    "minecraft:trader_llama",
    "minecraft:zombie_horse",
];

/// Registry names whose class descends from `Chicken`, the other type
/// whose `positionRider` copies `yBodyRot` onto a living passenger — the
/// chicken jockey.
pub const CHICKEN: &[&str] = &[
    "minecraft:chicken",
];

/// Registry names whose class descends from `Camel`, which replaces the
/// attachment with a two-seat body anchor. The camel declares **no**
/// `passengerAttachments`, so falling back to the default would put a
/// rider at the top of its bounding box rather than on its back.
pub const CAMEL: &[&str] = &[
    "minecraft:camel",
    "minecraft:camel_husk",
];

/// Registry names whose class descends from `AbstractNautilus` (M169),
/// which declares `DASH` at **index 20, BOOLEAN** (TamableAnimal owns 18
/// and 19) and arms a 40-tick `dashCooldown` from it in
/// `onSyncedDataUpdated` — the `getJumpCooldown()` the jump bar reads.
pub const ABSTRACT_NAUTILUS: &[&str] = &[
    "minecraft:nautilus",
    "minecraft:zombie_nautilus",
];

/// Registry names whose class descends from `AbstractHurtingProjectile` —
/// the only entities `handleProjectilePowerPacket` writes
/// `accelerationPower` onto. An arrow is an `AbstractArrow` and NOT one of
/// these, so a `projectile_power` naming one must mutate nothing.
pub const ABSTRACT_HURTING_PROJECTILE: &[&str] = &[
    "minecraft:breeze_wind_charge",
    "minecraft:dragon_fireball",
    "minecraft:fireball",
    "minecraft:small_fireball",
    "minecraft:wind_charge",
    "minecraft:wither_skull",
];

/// Registry names whose class implements `PlayerRideableJumping` (M169)
/// — the vehicles `LocalPlayer.jumpableVehicle()` can return, and so the
/// only ones whose rider ever sees the jump bar. The union of the
/// `AbstractHorse` and `AbstractNautilus` subtrees; pinning the implementor
/// pair is what stops a 26.3 that makes a pig jumpable from shipping a
/// set one subtree short.
///
/// Implementing classes at generation time: `AbstractHorse`, `AbstractNautilus`. The
/// generator asserts that set rather than trusting it.
pub const PLAYER_RIDEABLE_JUMPING: &[&str] = &[
    "minecraft:camel",
    "minecraft:camel_husk",
    "minecraft:donkey",
    "minecraft:horse",
    "minecraft:llama",
    "minecraft:mule",
    "minecraft:nautilus",
    "minecraft:skeleton_horse",
    "minecraft:trader_llama",
    "minecraft:zombie_horse",
    "minecraft:zombie_nautilus",
];

/// Registry names whose class implements `Leashable`, which is what
/// `handleEntityLinkPacket` casts to before calling
/// `setDelayedLeashHolderId`. `Leashable` is an **interface**, so this set
/// is the union of the `extends` subtrees of the classes that declare it —
/// `Mob` and `AbstractBoat` — rather than one ancestry walk. A
/// `set_entity_link` naming anything else (an armour stand, a minecart, an
/// item entity) mutates nothing.
///
/// Implementing classes at generation time: `AbstractBoat`, `Mob`. The
/// generator asserts that set rather than trusting it.
pub const LEASHABLE: &[&str] = &[
    "minecraft:acacia_boat",
    "minecraft:acacia_chest_boat",
    "minecraft:allay",
    "minecraft:armadillo",
    "minecraft:axolotl",
    "minecraft:bamboo_chest_raft",
    "minecraft:bamboo_raft",
    "minecraft:bat",
    "minecraft:bee",
    "minecraft:birch_boat",
    "minecraft:birch_chest_boat",
    "minecraft:blaze",
    "minecraft:bogged",
    "minecraft:breeze",
    "minecraft:camel",
    "minecraft:camel_husk",
    "minecraft:cat",
    "minecraft:cave_spider",
    "minecraft:cherry_boat",
    "minecraft:cherry_chest_boat",
    "minecraft:chicken",
    "minecraft:cod",
    "minecraft:copper_golem",
    "minecraft:cow",
    "minecraft:creaking",
    "minecraft:creeper",
    "minecraft:dark_oak_boat",
    "minecraft:dark_oak_chest_boat",
    "minecraft:dolphin",
    "minecraft:donkey",
    "minecraft:drowned",
    "minecraft:elder_guardian",
    "minecraft:ender_dragon",
    "minecraft:enderman",
    "minecraft:endermite",
    "minecraft:evoker",
    "minecraft:fox",
    "minecraft:frog",
    "minecraft:ghast",
    "minecraft:giant",
    "minecraft:glow_squid",
    "minecraft:goat",
    "minecraft:guardian",
    "minecraft:happy_ghast",
    "minecraft:hoglin",
    "minecraft:horse",
    "minecraft:husk",
    "minecraft:illusioner",
    "minecraft:iron_golem",
    "minecraft:jungle_boat",
    "minecraft:jungle_chest_boat",
    "minecraft:llama",
    "minecraft:magma_cube",
    "minecraft:mangrove_boat",
    "minecraft:mangrove_chest_boat",
    "minecraft:mooshroom",
    "minecraft:mule",
    "minecraft:nautilus",
    "minecraft:oak_boat",
    "minecraft:oak_chest_boat",
    "minecraft:ocelot",
    "minecraft:pale_oak_boat",
    "minecraft:pale_oak_chest_boat",
    "minecraft:panda",
    "minecraft:parched",
    "minecraft:parrot",
    "minecraft:phantom",
    "minecraft:pig",
    "minecraft:piglin",
    "minecraft:piglin_brute",
    "minecraft:pillager",
    "minecraft:polar_bear",
    "minecraft:pufferfish",
    "minecraft:rabbit",
    "minecraft:ravager",
    "minecraft:salmon",
    "minecraft:sheep",
    "minecraft:shulker",
    "minecraft:silverfish",
    "minecraft:skeleton",
    "minecraft:skeleton_horse",
    "minecraft:slime",
    "minecraft:sniffer",
    "minecraft:snow_golem",
    "minecraft:spider",
    "minecraft:spruce_boat",
    "minecraft:spruce_chest_boat",
    "minecraft:squid",
    "minecraft:stray",
    "minecraft:strider",
    "minecraft:sulfur_cube",
    "minecraft:tadpole",
    "minecraft:trader_llama",
    "minecraft:tropical_fish",
    "minecraft:turtle",
    "minecraft:vex",
    "minecraft:villager",
    "minecraft:vindicator",
    "minecraft:wandering_trader",
    "minecraft:warden",
    "minecraft:witch",
    "minecraft:wither",
    "minecraft:wither_skeleton",
    "minecraft:wolf",
    "minecraft:zoglin",
    "minecraft:zombie",
    "minecraft:zombie_horse",
    "minecraft:zombie_nautilus",
    "minecraft:zombie_villager",
    "minecraft:zombified_piglin",
];
