//! Vanilla furnace fuel burn times — GENERATED by `tools/gen_fuel_values.py`.
//!
//! Do not edit. Re-run the generator after a version bump.
//!
//! `FuelValues.vanillaBurnTimes` with `baseUnit = 200`, its tag arguments
//! expanded against the jar's own `data/minecraft/tags/item/*.json` (which nest,
//! so the expansion recurses) and its trailing
//! `.remove(ItemTags.NON_FLAMMABLE_WOOD)` applied — without which crimson and
//! warped wood would burn, because the `logs` and `planks` families add them
//! first.
//!
//! Order is the builder's, and it is load-bearing while generating: the map is
//! insertion-ordered and `put` overwrites, so a later `.add` wins.

/// `(item id, burn duration in ticks)`, 280 entries.
pub static FUEL: &[(&str, i32)] = &[
    ("minecraft:lava_bucket", 20000),
    ("minecraft:coal_block", 16000),
    ("minecraft:blaze_rod", 2400),
    ("minecraft:coal", 1600),
    ("minecraft:charcoal", 1600),
    ("minecraft:dark_oak_log", 300),
    ("minecraft:dark_oak_wood", 300),
    ("minecraft:stripped_dark_oak_log", 300),
    ("minecraft:stripped_dark_oak_wood", 300),
    ("minecraft:pale_oak_log", 300),
    ("minecraft:pale_oak_wood", 300),
    ("minecraft:stripped_pale_oak_log", 300),
    ("minecraft:stripped_pale_oak_wood", 300),
    ("minecraft:oak_log", 300),
    ("minecraft:oak_wood", 300),
    ("minecraft:stripped_oak_log", 300),
    ("minecraft:stripped_oak_wood", 300),
    ("minecraft:acacia_log", 300),
    ("minecraft:acacia_wood", 300),
    ("minecraft:stripped_acacia_log", 300),
    ("minecraft:stripped_acacia_wood", 300),
    ("minecraft:birch_log", 300),
    ("minecraft:birch_wood", 300),
    ("minecraft:stripped_birch_log", 300),
    ("minecraft:stripped_birch_wood", 300),
    ("minecraft:jungle_log", 300),
    ("minecraft:jungle_wood", 300),
    ("minecraft:stripped_jungle_log", 300),
    ("minecraft:stripped_jungle_wood", 300),
    ("minecraft:spruce_log", 300),
    ("minecraft:spruce_wood", 300),
    ("minecraft:stripped_spruce_log", 300),
    ("minecraft:stripped_spruce_wood", 300),
    ("minecraft:mangrove_log", 300),
    ("minecraft:mangrove_wood", 300),
    ("minecraft:stripped_mangrove_log", 300),
    ("minecraft:stripped_mangrove_wood", 300),
    ("minecraft:cherry_log", 300),
    ("minecraft:cherry_wood", 300),
    ("minecraft:stripped_cherry_log", 300),
    ("minecraft:stripped_cherry_wood", 300),
    ("minecraft:bamboo_block", 300),
    ("minecraft:stripped_bamboo_block", 300),
    ("minecraft:oak_planks", 300),
    ("minecraft:spruce_planks", 300),
    ("minecraft:birch_planks", 300),
    ("minecraft:jungle_planks", 300),
    ("minecraft:acacia_planks", 300),
    ("minecraft:dark_oak_planks", 300),
    ("minecraft:pale_oak_planks", 300),
    ("minecraft:mangrove_planks", 300),
    ("minecraft:bamboo_planks", 300),
    ("minecraft:cherry_planks", 300),
    ("minecraft:bamboo_mosaic", 300),
    ("minecraft:oak_stairs", 300),
    ("minecraft:spruce_stairs", 300),
    ("minecraft:birch_stairs", 300),
    ("minecraft:jungle_stairs", 300),
    ("minecraft:acacia_stairs", 300),
    ("minecraft:dark_oak_stairs", 300),
    ("minecraft:pale_oak_stairs", 300),
    ("minecraft:mangrove_stairs", 300),
    ("minecraft:bamboo_stairs", 300),
    ("minecraft:cherry_stairs", 300),
    ("minecraft:bamboo_mosaic_stairs", 300),
    ("minecraft:oak_slab", 150),
    ("minecraft:spruce_slab", 150),
    ("minecraft:birch_slab", 150),
    ("minecraft:jungle_slab", 150),
    ("minecraft:acacia_slab", 150),
    ("minecraft:dark_oak_slab", 150),
    ("minecraft:pale_oak_slab", 150),
    ("minecraft:mangrove_slab", 150),
    ("minecraft:bamboo_slab", 150),
    ("minecraft:cherry_slab", 150),
    ("minecraft:bamboo_mosaic_slab", 150),
    ("minecraft:acacia_trapdoor", 300),
    ("minecraft:birch_trapdoor", 300),
    ("minecraft:dark_oak_trapdoor", 300),
    ("minecraft:pale_oak_trapdoor", 300),
    ("minecraft:jungle_trapdoor", 300),
    ("minecraft:oak_trapdoor", 300),
    ("minecraft:spruce_trapdoor", 300),
    ("minecraft:mangrove_trapdoor", 300),
    ("minecraft:bamboo_trapdoor", 300),
    ("minecraft:cherry_trapdoor", 300),
    ("minecraft:oak_pressure_plate", 300),
    ("minecraft:spruce_pressure_plate", 300),
    ("minecraft:birch_pressure_plate", 300),
    ("minecraft:jungle_pressure_plate", 300),
    ("minecraft:acacia_pressure_plate", 300),
    ("minecraft:dark_oak_pressure_plate", 300),
    ("minecraft:pale_oak_pressure_plate", 300),
    ("minecraft:mangrove_pressure_plate", 300),
    ("minecraft:bamboo_pressure_plate", 300),
    ("minecraft:cherry_pressure_plate", 300),
    ("minecraft:acacia_shelf", 300),
    ("minecraft:bamboo_shelf", 300),
    ("minecraft:birch_shelf", 300),
    ("minecraft:cherry_shelf", 300),
    ("minecraft:dark_oak_shelf", 300),
    ("minecraft:jungle_shelf", 300),
    ("minecraft:mangrove_shelf", 300),
    ("minecraft:oak_shelf", 300),
    ("minecraft:pale_oak_shelf", 300),
    ("minecraft:spruce_shelf", 300),
    ("minecraft:oak_fence", 300),
    ("minecraft:acacia_fence", 300),
    ("minecraft:dark_oak_fence", 300),
    ("minecraft:pale_oak_fence", 300),
    ("minecraft:spruce_fence", 300),
    ("minecraft:birch_fence", 300),
    ("minecraft:jungle_fence", 300),
    ("minecraft:mangrove_fence", 300),
    ("minecraft:bamboo_fence", 300),
    ("minecraft:cherry_fence", 300),
    ("minecraft:acacia_fence_gate", 300),
    ("minecraft:birch_fence_gate", 300),
    ("minecraft:dark_oak_fence_gate", 300),
    ("minecraft:pale_oak_fence_gate", 300),
    ("minecraft:jungle_fence_gate", 300),
    ("minecraft:oak_fence_gate", 300),
    ("minecraft:spruce_fence_gate", 300),
    ("minecraft:mangrove_fence_gate", 300),
    ("minecraft:bamboo_fence_gate", 300),
    ("minecraft:cherry_fence_gate", 300),
    ("minecraft:note_block", 300),
    ("minecraft:bookshelf", 300),
    ("minecraft:chiseled_bookshelf", 300),
    ("minecraft:lectern", 300),
    ("minecraft:jukebox", 300),
    ("minecraft:chest", 300),
    ("minecraft:trapped_chest", 300),
    ("minecraft:crafting_table", 300),
    ("minecraft:daylight_detector", 300),
    ("minecraft:white_banner", 300),
    ("minecraft:orange_banner", 300),
    ("minecraft:magenta_banner", 300),
    ("minecraft:light_blue_banner", 300),
    ("minecraft:yellow_banner", 300),
    ("minecraft:lime_banner", 300),
    ("minecraft:pink_banner", 300),
    ("minecraft:gray_banner", 300),
    ("minecraft:light_gray_banner", 300),
    ("minecraft:cyan_banner", 300),
    ("minecraft:purple_banner", 300),
    ("minecraft:blue_banner", 300),
    ("minecraft:brown_banner", 300),
    ("minecraft:green_banner", 300),
    ("minecraft:red_banner", 300),
    ("minecraft:black_banner", 300),
    ("minecraft:bow", 300),
    ("minecraft:fishing_rod", 300),
    ("minecraft:ladder", 300),
    ("minecraft:oak_sign", 200),
    ("minecraft:spruce_sign", 200),
    ("minecraft:birch_sign", 200),
    ("minecraft:acacia_sign", 200),
    ("minecraft:jungle_sign", 200),
    ("minecraft:dark_oak_sign", 200),
    ("minecraft:pale_oak_sign", 200),
    ("minecraft:mangrove_sign", 200),
    ("minecraft:bamboo_sign", 200),
    ("minecraft:cherry_sign", 200),
    ("minecraft:oak_hanging_sign", 800),
    ("minecraft:spruce_hanging_sign", 800),
    ("minecraft:birch_hanging_sign", 800),
    ("minecraft:acacia_hanging_sign", 800),
    ("minecraft:cherry_hanging_sign", 800),
    ("minecraft:jungle_hanging_sign", 800),
    ("minecraft:dark_oak_hanging_sign", 800),
    ("minecraft:pale_oak_hanging_sign", 800),
    ("minecraft:mangrove_hanging_sign", 800),
    ("minecraft:bamboo_hanging_sign", 800),
    ("minecraft:wooden_shovel", 200),
    ("minecraft:wooden_sword", 200),
    ("minecraft:wooden_spear", 200),
    ("minecraft:wooden_hoe", 200),
    ("minecraft:wooden_axe", 200),
    ("minecraft:wooden_pickaxe", 200),
    ("minecraft:oak_door", 200),
    ("minecraft:spruce_door", 200),
    ("minecraft:birch_door", 200),
    ("minecraft:jungle_door", 200),
    ("minecraft:acacia_door", 200),
    ("minecraft:dark_oak_door", 200),
    ("minecraft:pale_oak_door", 200),
    ("minecraft:mangrove_door", 200),
    ("minecraft:bamboo_door", 200),
    ("minecraft:cherry_door", 200),
    ("minecraft:oak_boat", 1200),
    ("minecraft:spruce_boat", 1200),
    ("minecraft:birch_boat", 1200),
    ("minecraft:jungle_boat", 1200),
    ("minecraft:acacia_boat", 1200),
    ("minecraft:dark_oak_boat", 1200),
    ("minecraft:pale_oak_boat", 1200),
    ("minecraft:mangrove_boat", 1200),
    ("minecraft:bamboo_raft", 1200),
    ("minecraft:cherry_boat", 1200),
    ("minecraft:oak_chest_boat", 1200),
    ("minecraft:spruce_chest_boat", 1200),
    ("minecraft:birch_chest_boat", 1200),
    ("minecraft:jungle_chest_boat", 1200),
    ("minecraft:acacia_chest_boat", 1200),
    ("minecraft:dark_oak_chest_boat", 1200),
    ("minecraft:pale_oak_chest_boat", 1200),
    ("minecraft:mangrove_chest_boat", 1200),
    ("minecraft:bamboo_chest_raft", 1200),
    ("minecraft:cherry_chest_boat", 1200),
    ("minecraft:white_wool", 100),
    ("minecraft:orange_wool", 100),
    ("minecraft:magenta_wool", 100),
    ("minecraft:light_blue_wool", 100),
    ("minecraft:yellow_wool", 100),
    ("minecraft:lime_wool", 100),
    ("minecraft:pink_wool", 100),
    ("minecraft:gray_wool", 100),
    ("minecraft:light_gray_wool", 100),
    ("minecraft:cyan_wool", 100),
    ("minecraft:purple_wool", 100),
    ("minecraft:blue_wool", 100),
    ("minecraft:brown_wool", 100),
    ("minecraft:green_wool", 100),
    ("minecraft:red_wool", 100),
    ("minecraft:black_wool", 100),
    ("minecraft:oak_button", 100),
    ("minecraft:spruce_button", 100),
    ("minecraft:birch_button", 100),
    ("minecraft:jungle_button", 100),
    ("minecraft:acacia_button", 100),
    ("minecraft:dark_oak_button", 100),
    ("minecraft:pale_oak_button", 100),
    ("minecraft:mangrove_button", 100),
    ("minecraft:bamboo_button", 100),
    ("minecraft:cherry_button", 100),
    ("minecraft:stick", 100),
    ("minecraft:oak_sapling", 100),
    ("minecraft:spruce_sapling", 100),
    ("minecraft:birch_sapling", 100),
    ("minecraft:jungle_sapling", 100),
    ("minecraft:acacia_sapling", 100),
    ("minecraft:dark_oak_sapling", 100),
    ("minecraft:pale_oak_sapling", 100),
    ("minecraft:azalea", 100),
    ("minecraft:flowering_azalea", 100),
    ("minecraft:mangrove_propagule", 100),
    ("minecraft:cherry_sapling", 100),
    ("minecraft:bowl", 100),
    ("minecraft:white_carpet", 67),
    ("minecraft:orange_carpet", 67),
    ("minecraft:magenta_carpet", 67),
    ("minecraft:light_blue_carpet", 67),
    ("minecraft:yellow_carpet", 67),
    ("minecraft:lime_carpet", 67),
    ("minecraft:pink_carpet", 67),
    ("minecraft:gray_carpet", 67),
    ("minecraft:light_gray_carpet", 67),
    ("minecraft:cyan_carpet", 67),
    ("minecraft:purple_carpet", 67),
    ("minecraft:blue_carpet", 67),
    ("minecraft:brown_carpet", 67),
    ("minecraft:green_carpet", 67),
    ("minecraft:red_carpet", 67),
    ("minecraft:black_carpet", 67),
    ("minecraft:dried_kelp_block", 4001),
    ("minecraft:crossbow", 300),
    ("minecraft:bamboo", 50),
    ("minecraft:dead_bush", 100),
    ("minecraft:short_dry_grass", 100),
    ("minecraft:tall_dry_grass", 100),
    ("minecraft:scaffolding", 50),
    ("minecraft:loom", 300),
    ("minecraft:barrel", 300),
    ("minecraft:cartography_table", 300),
    ("minecraft:fletching_table", 300),
    ("minecraft:smithing_table", 300),
    ("minecraft:composter", 300),
    ("minecraft:mangrove_roots", 300),
    ("minecraft:leaf_litter", 100),
];

/// `FuelValues.burnDuration` — 0 for anything absent, which is what
/// `Object2IntMap`'s default return value gives.
pub fn burn_duration(item: &str) -> i32 {
    FUEL.iter()
        .find(|(k, _)| *k == item)
        .map(|(_, v)| *v)
        .unwrap_or(0)
}

/// `AbstractFurnaceMenu.isFuel` — a positive burn duration.
pub fn is_fuel(item: &str) -> bool {
    burn_duration(item) > 0
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Burn times measured against vanilla, not against the generator.
    ///
    /// `dried_kelp_block` is the one that matters: its expression is
    /// `1 + baseUnit * 20`, and a left-to-right evaluator answers 4020 where
    /// Java's precedence gives 4001. The generator's first cut was
    /// left-to-right and this caught it — while `white_carpet`
    /// (`1 + baseUnit / 3`) gives 67 under *either* reading, so it confirms
    /// nothing on its own. Both are here so the pair keeps saying that.
    #[test]
    fn known_vanilla_burn_times() {
        for (item, want) in [
            ("minecraft:coal", 1600),
            ("minecraft:charcoal", 1600),
            ("minecraft:lava_bucket", 20000),
            ("minecraft:coal_block", 16000),
            ("minecraft:blaze_rod", 2400),
            ("minecraft:stick", 100),
            ("minecraft:oak_planks", 300),
            ("minecraft:oak_slab", 150),
            ("minecraft:white_carpet", 67),
            ("minecraft:dried_kelp_block", 4001),
            ("minecraft:bamboo", 50),
            ("minecraft:scaffolding", 50),
        ] {
            assert_eq!(burn_duration(item), want, "{item}");
        }
    }

    #[test]
    fn non_flammable_wood_is_removed_last() {
        // The `logs` and `planks` families add crimson and warped; the
        // trailing `.remove(ItemTags.NON_FLAMMABLE_WOOD)` takes them out. Drop
        // that step and warped planks burn, which they do not.
        for item in [
            "minecraft:warped_planks",
            "minecraft:crimson_planks",
            "minecraft:warped_stem",
            "minecraft:crimson_hyphae",
            "minecraft:warped_slab",
        ] {
            assert!(!is_fuel(item), "{item} must not burn");
        }
        // ...while their flammable siblings still do, so the removal is not
        // simply taking the whole family out.
        assert!(is_fuel("minecraft:oak_planks"));
        assert!(is_fuel("minecraft:spruce_slab"));
    }

    #[test]
    fn an_unlisted_item_is_not_fuel() {
        // `burnDuration` reads an Object2IntMap whose default return value is
        // 0, so an absent item is not an error.
        assert_eq!(burn_duration("minecraft:stone"), 0);
        assert!(!is_fuel("minecraft:stone"));
        assert!(!is_fuel("minecraft:not_a_real_item"));
    }

    #[test]
    fn the_table_is_the_size_the_generator_reported() {
        // A short table is the failure mode that hides: an item that simply
        // refuses to route to the fuel slot.
        assert_eq!(FUEL.len(), 280);
    }
}
