//! Every item's **prototype component set** — GENERATED, do not edit.
//!
//! Regenerate with `python tools/gen_item_components.py` after a version bump.
//!
//! Source: the datagen per-item component report for 26.2. Of
//! 1537 items, 12 components are on every one of them and
//! 47 more appear at all; 19356 prototype entries in total
//! (446 items carry at least one non-universal component). Set-size
//! histogram: 12: 1091, 13: 303, 14: 55, 15: 10, 16: 3, 17: 27, 18: 36, 19: 5, 22: 6, 23: 1.
//!
//! # Why the client needs this
//!
//! `ItemStack.addDetailsToTooltip`'s advanced block ends with
//! `Component.translatable("item.components", this.components.size())`, and
//! `this.components` is the **merged** `PatchedDataComponentMap` — prototype
//! plus patch — not the patch. A plain dirt stack arrives with an empty patch
//! and still reads "12 component(s)". Counting the
//! patch's own entries would print `0` for nearly every stack in the game.
//!
//! `PatchedDataComponentMap.size()` adjusts the prototype's count by one for
//! each patch entry whose *presence* differs from the prototype's, which is
//! why the names are here and not just the count: an entry that overrides a
//! component the prototype already has changes nothing.
//!
//! # Membership is an answer
//!
//! Every item is listed, including the 1091 whose mask is
//! zero. An item the table does not know returns `None` and the tooltip drops
//! the `item.components` line rather than guessing 12 — the same
//! fail-closed rule the unresolvable item models take.

/// The components on **every** item — `DataComponents.COMMON_ITEM_COMPONENTS`
/// plus what `Item.Properties` always sets. Stored once rather than in every
/// row.
pub const BASE_COMPONENTS: &[&str] = &[
    "minecraft:attribute_modifiers",
    "minecraft:break_sound",
    "minecraft:enchantments",
    "minecraft:item_model",
    "minecraft:item_name",
    "minecraft:lore",
    "minecraft:max_stack_size",
    "minecraft:rarity",
    "minecraft:repair_cost",
    "minecraft:swing_animation",
    "minecraft:tooltip_display",
    "minecraft:use_effects",
];

/// Every other component name a prototype carries, in the order the mask's
/// bits index them: bit `i` of a row's mask is `EXTRA_COMPONENTS[i]`.
pub const EXTRA_COMPONENTS: &[&str] = &[
    "minecraft:attack_range",
    "minecraft:banner_patterns",
    "minecraft:bees",
    "minecraft:block_state",
    "minecraft:blocks_attacks",
    "minecraft:bucket_entity_data",
    "minecraft:bundle_contents",
    "minecraft:charged_projectiles",
    "minecraft:chicken/variant",
    "minecraft:consumable",
    "minecraft:container",
    "minecraft:damage",
    "minecraft:damage_resistant",
    "minecraft:damage_type",
    "minecraft:death_protection",
    "minecraft:debug_stick_state",
    "minecraft:dye",
    "minecraft:enchantable",
    "minecraft:enchantment_glint_override",
    "minecraft:entity_data",
    "minecraft:equippable",
    "minecraft:fireworks",
    "minecraft:food",
    "minecraft:glider",
    "minecraft:instrument",
    "minecraft:jukebox_playable",
    "minecraft:kinetic_weapon",
    "minecraft:map_color",
    "minecraft:map_decorations",
    "minecraft:max_damage",
    "minecraft:minimum_attack_charge",
    "minecraft:ominous_bottle_amplifier",
    "minecraft:piercing_weapon",
    "minecraft:pot_decorations",
    "minecraft:potion_contents",
    "minecraft:potion_duration_scale",
    "minecraft:provides_banner_patterns",
    "minecraft:provides_trim_material",
    "minecraft:recipes",
    "minecraft:repairable",
    "minecraft:stored_enchantments",
    "minecraft:suspicious_stew_effects",
    "minecraft:tool",
    "minecraft:use_cooldown",
    "minecraft:use_remainder",
    "minecraft:weapon",
    "minecraft:writable_book_content",
];

/// `(item name, bitmask over `EXTRA_COMPONENTS`)`, sorted by name so a binary
/// search finds it. A zero mask means the item's prototype is exactly
/// [`BASE_COMPONENTS`] — which is still a row, because absence from this table
/// means "unknown item", not "no extras".
pub const ITEM_COMPONENTS: &[(&str, u64)] = &[
    ("minecraft:acacia_boat", 0x0),
    ("minecraft:acacia_button", 0x0),
    ("minecraft:acacia_chest_boat", 0x0),
    ("minecraft:acacia_door", 0x0),
    ("minecraft:acacia_fence", 0x0),
    ("minecraft:acacia_fence_gate", 0x0),
    ("minecraft:acacia_hanging_sign", 0x0),
    ("minecraft:acacia_leaves", 0x0),
    ("minecraft:acacia_log", 0x0),
    ("minecraft:acacia_planks", 0x0),
    ("minecraft:acacia_pressure_plate", 0x0),
    ("minecraft:acacia_sapling", 0x0),
    ("minecraft:acacia_shelf", 0x400),
    ("minecraft:acacia_sign", 0x0),
    ("minecraft:acacia_slab", 0x0),
    ("minecraft:acacia_stairs", 0x0),
    ("minecraft:acacia_trapdoor", 0x0),
    ("minecraft:acacia_wood", 0x0),
    ("minecraft:activator_rail", 0x0),
    ("minecraft:air", 0x0),
    ("minecraft:allay_spawn_egg", 0x80000),
    ("minecraft:allium", 0x0),
    ("minecraft:amethyst_block", 0x0),
    ("minecraft:amethyst_cluster", 0x0),
    ("minecraft:amethyst_shard", 0x2000000000),
    ("minecraft:ancient_debris", 0x1000),
    ("minecraft:andesite", 0x0),
    ("minecraft:andesite_slab", 0x0),
    ("minecraft:andesite_stairs", 0x0),
    ("minecraft:andesite_wall", 0x0),
    ("minecraft:angler_pottery_sherd", 0x0),
    ("minecraft:anvil", 0x0),
    ("minecraft:apple", 0x400200),
    ("minecraft:archer_pottery_sherd", 0x0),
    ("minecraft:armadillo_scute", 0x0),
    ("minecraft:armadillo_spawn_egg", 0x80000),
    ("minecraft:armor_stand", 0x0),
    ("minecraft:arms_up_pottery_sherd", 0x0),
    ("minecraft:arrow", 0x0),
    ("minecraft:axolotl_bucket", 0x20),
    ("minecraft:axolotl_spawn_egg", 0x80000),
    ("minecraft:azalea", 0x0),
    ("minecraft:azalea_leaves", 0x0),
    ("minecraft:azure_bluet", 0x0),
    ("minecraft:baked_potato", 0x400200),
    ("minecraft:bamboo", 0x0),
    ("minecraft:bamboo_block", 0x0),
    ("minecraft:bamboo_button", 0x0),
    ("minecraft:bamboo_chest_raft", 0x0),
    ("minecraft:bamboo_door", 0x0),
    ("minecraft:bamboo_fence", 0x0),
    ("minecraft:bamboo_fence_gate", 0x0),
    ("minecraft:bamboo_hanging_sign", 0x0),
    ("minecraft:bamboo_mosaic", 0x0),
    ("minecraft:bamboo_mosaic_slab", 0x0),
    ("minecraft:bamboo_mosaic_stairs", 0x0),
    ("minecraft:bamboo_planks", 0x0),
    ("minecraft:bamboo_pressure_plate", 0x0),
    ("minecraft:bamboo_raft", 0x0),
    ("minecraft:bamboo_shelf", 0x400),
    ("minecraft:bamboo_sign", 0x0),
    ("minecraft:bamboo_slab", 0x0),
    ("minecraft:bamboo_stairs", 0x0),
    ("minecraft:bamboo_trapdoor", 0x0),
    ("minecraft:barrel", 0x400),
    ("minecraft:barrier", 0x0),
    ("minecraft:basalt", 0x0),
    ("minecraft:bat_spawn_egg", 0x80000),
    ("minecraft:beacon", 0x0),
    ("minecraft:bedrock", 0x0),
    ("minecraft:bee_nest", 0xc),
    ("minecraft:bee_spawn_egg", 0x80000),
    ("minecraft:beef", 0x400200),
    ("minecraft:beehive", 0xc),
    ("minecraft:beetroot", 0x400200),
    ("minecraft:beetroot_seeds", 0x0),
    ("minecraft:beetroot_soup", 0x100000400200),
    ("minecraft:bell", 0x0),
    ("minecraft:big_dripleaf", 0x0),
    ("minecraft:birch_boat", 0x0),
    ("minecraft:birch_button", 0x0),
    ("minecraft:birch_chest_boat", 0x0),
    ("minecraft:birch_door", 0x0),
    ("minecraft:birch_fence", 0x0),
    ("minecraft:birch_fence_gate", 0x0),
    ("minecraft:birch_hanging_sign", 0x0),
    ("minecraft:birch_leaves", 0x0),
    ("minecraft:birch_log", 0x0),
    ("minecraft:birch_planks", 0x0),
    ("minecraft:birch_pressure_plate", 0x0),
    ("minecraft:birch_sapling", 0x0),
    ("minecraft:birch_shelf", 0x400),
    ("minecraft:birch_sign", 0x0),
    ("minecraft:birch_slab", 0x0),
    ("minecraft:birch_stairs", 0x0),
    ("minecraft:birch_trapdoor", 0x0),
    ("minecraft:birch_wood", 0x0),
    ("minecraft:black_banner", 0x2),
    ("minecraft:black_bed", 0x0),
    ("minecraft:black_bundle", 0x40),
    ("minecraft:black_candle", 0x0),
    ("minecraft:black_carpet", 0x100000),
    ("minecraft:black_concrete", 0x0),
    ("minecraft:black_concrete_powder", 0x0),
    ("minecraft:black_dye", 0x10000),
    ("minecraft:black_glazed_terracotta", 0x0),
    ("minecraft:black_harness", 0x100000),
    ("minecraft:black_shulker_box", 0x400),
    ("minecraft:black_stained_glass", 0x0),
    ("minecraft:black_stained_glass_pane", 0x0),
    ("minecraft:black_terracotta", 0x0),
    ("minecraft:black_wool", 0x0),
    ("minecraft:blackstone", 0x0),
    ("minecraft:blackstone_slab", 0x0),
    ("minecraft:blackstone_stairs", 0x0),
    ("minecraft:blackstone_wall", 0x0),
    ("minecraft:blade_pottery_sherd", 0x0),
    ("minecraft:blast_furnace", 0x400),
    ("minecraft:blaze_powder", 0x0),
    ("minecraft:blaze_rod", 0x0),
    ("minecraft:blaze_spawn_egg", 0x80000),
    ("minecraft:blue_banner", 0x2),
    ("minecraft:blue_bed", 0x0),
    ("minecraft:blue_bundle", 0x40),
    ("minecraft:blue_candle", 0x0),
    ("minecraft:blue_carpet", 0x100000),
    ("minecraft:blue_concrete", 0x0),
    ("minecraft:blue_concrete_powder", 0x0),
    ("minecraft:blue_dye", 0x10000),
    ("minecraft:blue_egg", 0x100),
    ("minecraft:blue_glazed_terracotta", 0x0),
    ("minecraft:blue_harness", 0x100000),
    ("minecraft:blue_ice", 0x0),
    ("minecraft:blue_orchid", 0x0),
    ("minecraft:blue_shulker_box", 0x400),
    ("minecraft:blue_stained_glass", 0x0),
    ("minecraft:blue_stained_glass_pane", 0x0),
    ("minecraft:blue_terracotta", 0x0),
    ("minecraft:blue_wool", 0x0),
    ("minecraft:bogged_spawn_egg", 0x80000),
    ("minecraft:bolt_armor_trim_smithing_template", 0x0),
    ("minecraft:bone", 0x0),
    ("minecraft:bone_block", 0x0),
    ("minecraft:bone_meal", 0x0),
    ("minecraft:book", 0x20000),
    ("minecraft:bookshelf", 0x0),
    ("minecraft:bordure_indented_banner_pattern", 0x1000000000),
    ("minecraft:bow", 0x20020800),
    ("minecraft:bowl", 0x0),
    ("minecraft:brain_coral", 0x0),
    ("minecraft:brain_coral_block", 0x0),
    ("minecraft:brain_coral_fan", 0x0),
    ("minecraft:bread", 0x400200),
    ("minecraft:breeze_rod", 0x0),
    ("minecraft:breeze_spawn_egg", 0x80000),
    ("minecraft:brewer_pottery_sherd", 0x0),
    ("minecraft:brewing_stand", 0x400),
    ("minecraft:brick", 0x0),
    ("minecraft:brick_slab", 0x0),
    ("minecraft:brick_stairs", 0x0),
    ("minecraft:brick_wall", 0x0),
    ("minecraft:bricks", 0x0),
    ("minecraft:brown_banner", 0x2),
    ("minecraft:brown_bed", 0x0),
    ("minecraft:brown_bundle", 0x40),
    ("minecraft:brown_candle", 0x0),
    ("minecraft:brown_carpet", 0x100000),
    ("minecraft:brown_concrete", 0x0),
    ("minecraft:brown_concrete_powder", 0x0),
    ("minecraft:brown_dye", 0x10000),
    ("minecraft:brown_egg", 0x100),
    ("minecraft:brown_glazed_terracotta", 0x0),
    ("minecraft:brown_harness", 0x100000),
    ("minecraft:brown_mushroom", 0x0),
    ("minecraft:brown_mushroom_block", 0x0),
    ("minecraft:brown_shulker_box", 0x400),
    ("minecraft:brown_stained_glass", 0x0),
    ("minecraft:brown_stained_glass_pane", 0x0),
    ("minecraft:brown_terracotta", 0x0),
    ("minecraft:brown_wool", 0x0),
    ("minecraft:brush", 0x20000800),
    ("minecraft:bubble_coral", 0x0),
    ("minecraft:bubble_coral_block", 0x0),
    ("minecraft:bubble_coral_fan", 0x0),
    ("minecraft:bucket", 0x0),
    ("minecraft:budding_amethyst", 0x0),
    ("minecraft:bundle", 0x40),
    ("minecraft:burn_pottery_sherd", 0x0),
    ("minecraft:bush", 0x0),
    ("minecraft:cactus", 0x0),
    ("minecraft:cactus_flower", 0x0),
    ("minecraft:cake", 0x0),
    ("minecraft:calcite", 0x0),
    ("minecraft:calibrated_sculk_sensor", 0x0),
    ("minecraft:camel_husk_spawn_egg", 0x80000),
    ("minecraft:camel_spawn_egg", 0x80000),
    ("minecraft:campfire", 0x400),
    ("minecraft:candle", 0x0),
    ("minecraft:carrot", 0x400200),
    ("minecraft:carrot_on_a_stick", 0x20000800),
    ("minecraft:cartography_table", 0x0),
    ("minecraft:carved_pumpkin", 0x100000),
    ("minecraft:cat_spawn_egg", 0x80000),
    ("minecraft:cauldron", 0x0),
    ("minecraft:cave_spider_spawn_egg", 0x80000),
    ("minecraft:chain_command_block", 0x0),
    ("minecraft:chainmail_boots", 0x8020120800),
    ("minecraft:chainmail_chestplate", 0x8020120800),
    ("minecraft:chainmail_helmet", 0x8020120800),
    ("minecraft:chainmail_leggings", 0x8020120800),
    ("minecraft:charcoal", 0x0),
    ("minecraft:cherry_boat", 0x0),
    ("minecraft:cherry_button", 0x0),
    ("minecraft:cherry_chest_boat", 0x0),
    ("minecraft:cherry_door", 0x0),
    ("minecraft:cherry_fence", 0x0),
    ("minecraft:cherry_fence_gate", 0x0),
    ("minecraft:cherry_hanging_sign", 0x0),
    ("minecraft:cherry_leaves", 0x0),
    ("minecraft:cherry_log", 0x0),
    ("minecraft:cherry_planks", 0x0),
    ("minecraft:cherry_pressure_plate", 0x0),
    ("minecraft:cherry_sapling", 0x0),
    ("minecraft:cherry_shelf", 0x400),
    ("minecraft:cherry_sign", 0x0),
    ("minecraft:cherry_slab", 0x0),
    ("minecraft:cherry_stairs", 0x0),
    ("minecraft:cherry_trapdoor", 0x0),
    ("minecraft:cherry_wood", 0x0),
    ("minecraft:chest", 0x400),
    ("minecraft:chest_minecart", 0x0),
    ("minecraft:chicken", 0x400200),
    ("minecraft:chicken_spawn_egg", 0x80000),
    ("minecraft:chipped_anvil", 0x0),
    ("minecraft:chiseled_bookshelf", 0x400),
    ("minecraft:chiseled_cinnabar", 0x0),
    ("minecraft:chiseled_copper", 0x0),
    ("minecraft:chiseled_deepslate", 0x0),
    ("minecraft:chiseled_nether_bricks", 0x0),
    ("minecraft:chiseled_polished_blackstone", 0x0),
    ("minecraft:chiseled_quartz_block", 0x0),
    ("minecraft:chiseled_red_sandstone", 0x0),
    ("minecraft:chiseled_resin_bricks", 0x0),
    ("minecraft:chiseled_sandstone", 0x0),
    ("minecraft:chiseled_stone_bricks", 0x0),
    ("minecraft:chiseled_sulfur", 0x0),
    ("minecraft:chiseled_tuff", 0x0),
    ("minecraft:chiseled_tuff_bricks", 0x0),
    ("minecraft:chorus_flower", 0x0),
    ("minecraft:chorus_fruit", 0x80000400200),
    ("minecraft:chorus_plant", 0x0),
    ("minecraft:cinnabar", 0x0),
    ("minecraft:cinnabar_brick_slab", 0x0),
    ("minecraft:cinnabar_brick_stairs", 0x0),
    ("minecraft:cinnabar_brick_wall", 0x0),
    ("minecraft:cinnabar_bricks", 0x0),
    ("minecraft:cinnabar_slab", 0x0),
    ("minecraft:cinnabar_stairs", 0x0),
    ("minecraft:cinnabar_wall", 0x0),
    ("minecraft:clay", 0x0),
    ("minecraft:clay_ball", 0x0),
    ("minecraft:clock", 0x0),
    ("minecraft:closed_eyeblossom", 0x0),
    ("minecraft:coal", 0x0),
    ("minecraft:coal_block", 0x0),
    ("minecraft:coal_ore", 0x0),
    ("minecraft:coarse_dirt", 0x0),
    ("minecraft:coast_armor_trim_smithing_template", 0x0),
    ("minecraft:cobbled_deepslate", 0x0),
    ("minecraft:cobbled_deepslate_slab", 0x0),
    ("minecraft:cobbled_deepslate_stairs", 0x0),
    ("minecraft:cobbled_deepslate_wall", 0x0),
    ("minecraft:cobblestone", 0x0),
    ("minecraft:cobblestone_slab", 0x0),
    ("minecraft:cobblestone_stairs", 0x0),
    ("minecraft:cobblestone_wall", 0x0),
    ("minecraft:cobweb", 0x0),
    ("minecraft:cocoa_beans", 0x0),
    ("minecraft:cod", 0x400200),
    ("minecraft:cod_bucket", 0x400020),
    ("minecraft:cod_spawn_egg", 0x80000),
    ("minecraft:command_block", 0x0),
    ("minecraft:command_block_minecart", 0x0),
    ("minecraft:comparator", 0x0),
    ("minecraft:compass", 0x0),
    ("minecraft:composter", 0x0),
    ("minecraft:conduit", 0x0),
    ("minecraft:cooked_beef", 0x400200),
    ("minecraft:cooked_chicken", 0x400200),
    ("minecraft:cooked_cod", 0x400200),
    ("minecraft:cooked_mutton", 0x400200),
    ("minecraft:cooked_porkchop", 0x400200),
    ("minecraft:cooked_rabbit", 0x400200),
    ("minecraft:cooked_salmon", 0x400200),
    ("minecraft:cookie", 0x400200),
    ("minecraft:copper_axe", 0x248020020800),
    ("minecraft:copper_bars", 0x0),
    ("minecraft:copper_block", 0x0),
    ("minecraft:copper_boots", 0x8020120800),
    ("minecraft:copper_bulb", 0x0),
    ("minecraft:copper_chain", 0x0),
    ("minecraft:copper_chest", 0x0),
    ("minecraft:copper_chestplate", 0x8020120800),
    ("minecraft:copper_door", 0x0),
    ("minecraft:copper_golem_spawn_egg", 0x80000),
    ("minecraft:copper_golem_statue", 0x8),
    ("minecraft:copper_grate", 0x0),
    ("minecraft:copper_helmet", 0x8020120800),
    ("minecraft:copper_hoe", 0x248020020800),
    ("minecraft:copper_horse_armor", 0x100000),
    ("minecraft:copper_ingot", 0x2000000000),
    ("minecraft:copper_lantern", 0x0),
    ("minecraft:copper_leggings", 0x8020120800),
    ("minecraft:copper_nautilus_armor", 0x100000),
    ("minecraft:copper_nugget", 0x0),
    ("minecraft:copper_ore", 0x0),
    ("minecraft:copper_pickaxe", 0x248020020800),
    ("minecraft:copper_shovel", 0x248020020800),
    ("minecraft:copper_spear", 0x208164022801),
    ("minecraft:copper_sword", 0x248020020800),
    ("minecraft:copper_torch", 0x0),
    ("minecraft:copper_trapdoor", 0x0),
    ("minecraft:cornflower", 0x0),
    ("minecraft:cow_spawn_egg", 0x80000),
    ("minecraft:cracked_deepslate_bricks", 0x0),
    ("minecraft:cracked_deepslate_tiles", 0x0),
    ("minecraft:cracked_nether_bricks", 0x0),
    ("minecraft:cracked_polished_blackstone_bricks", 0x0),
    ("minecraft:cracked_stone_bricks", 0x0),
    ("minecraft:crafter", 0x400),
    ("minecraft:crafting_table", 0x0),
    ("minecraft:creaking_heart", 0x0),
    ("minecraft:creaking_spawn_egg", 0x80000),
    ("minecraft:creeper_banner_pattern", 0x1000000000),
    ("minecraft:creeper_head", 0x100000),
    ("minecraft:creeper_spawn_egg", 0x80000),
    ("minecraft:crimson_button", 0x0),
    ("minecraft:crimson_door", 0x0),
    ("minecraft:crimson_fence", 0x0),
    ("minecraft:crimson_fence_gate", 0x0),
    ("minecraft:crimson_fungus", 0x0),
    ("minecraft:crimson_hanging_sign", 0x0),
    ("minecraft:crimson_hyphae", 0x0),
    ("minecraft:crimson_nylium", 0x0),
    ("minecraft:crimson_planks", 0x0),
    ("minecraft:crimson_pressure_plate", 0x0),
    ("minecraft:crimson_roots", 0x0),
    ("minecraft:crimson_shelf", 0x400),
    ("minecraft:crimson_sign", 0x0),
    ("minecraft:crimson_slab", 0x0),
    ("minecraft:crimson_stairs", 0x0),
    ("minecraft:crimson_stem", 0x0),
    ("minecraft:crimson_trapdoor", 0x0),
    ("minecraft:crossbow", 0x20020880),
    ("minecraft:crying_obsidian", 0x0),
    ("minecraft:cut_copper", 0x0),
    ("minecraft:cut_copper_slab", 0x0),
    ("minecraft:cut_copper_stairs", 0x0),
    ("minecraft:cut_red_sandstone", 0x0),
    ("minecraft:cut_red_sandstone_slab", 0x0),
    ("minecraft:cut_sandstone", 0x0),
    ("minecraft:cut_sandstone_slab", 0x0),
    ("minecraft:cyan_banner", 0x2),
    ("minecraft:cyan_bed", 0x0),
    ("minecraft:cyan_bundle", 0x40),
    ("minecraft:cyan_candle", 0x0),
    ("minecraft:cyan_carpet", 0x100000),
    ("minecraft:cyan_concrete", 0x0),
    ("minecraft:cyan_concrete_powder", 0x0),
    ("minecraft:cyan_dye", 0x10000),
    ("minecraft:cyan_glazed_terracotta", 0x0),
    ("minecraft:cyan_harness", 0x100000),
    ("minecraft:cyan_shulker_box", 0x400),
    ("minecraft:cyan_stained_glass", 0x0),
    ("minecraft:cyan_stained_glass_pane", 0x0),
    ("minecraft:cyan_terracotta", 0x0),
    ("minecraft:cyan_wool", 0x0),
    ("minecraft:damaged_anvil", 0x0),
    ("minecraft:dandelion", 0x0),
    ("minecraft:danger_pottery_sherd", 0x0),
    ("minecraft:dark_oak_boat", 0x0),
    ("minecraft:dark_oak_button", 0x0),
    ("minecraft:dark_oak_chest_boat", 0x0),
    ("minecraft:dark_oak_door", 0x0),
    ("minecraft:dark_oak_fence", 0x0),
    ("minecraft:dark_oak_fence_gate", 0x0),
    ("minecraft:dark_oak_hanging_sign", 0x0),
    ("minecraft:dark_oak_leaves", 0x0),
    ("minecraft:dark_oak_log", 0x0),
    ("minecraft:dark_oak_planks", 0x0),
    ("minecraft:dark_oak_pressure_plate", 0x0),
    ("minecraft:dark_oak_sapling", 0x0),
    ("minecraft:dark_oak_shelf", 0x400),
    ("minecraft:dark_oak_sign", 0x0),
    ("minecraft:dark_oak_slab", 0x0),
    ("minecraft:dark_oak_stairs", 0x0),
    ("minecraft:dark_oak_trapdoor", 0x0),
    ("minecraft:dark_oak_wood", 0x0),
    ("minecraft:dark_prismarine", 0x0),
    ("minecraft:dark_prismarine_slab", 0x0),
    ("minecraft:dark_prismarine_stairs", 0x0),
    ("minecraft:daylight_detector", 0x0),
    ("minecraft:dead_brain_coral", 0x0),
    ("minecraft:dead_brain_coral_block", 0x0),
    ("minecraft:dead_brain_coral_fan", 0x0),
    ("minecraft:dead_bubble_coral", 0x0),
    ("minecraft:dead_bubble_coral_block", 0x0),
    ("minecraft:dead_bubble_coral_fan", 0x0),
    ("minecraft:dead_bush", 0x0),
    ("minecraft:dead_fire_coral", 0x0),
    ("minecraft:dead_fire_coral_block", 0x0),
    ("minecraft:dead_fire_coral_fan", 0x0),
    ("minecraft:dead_horn_coral", 0x0),
    ("minecraft:dead_horn_coral_block", 0x0),
    ("minecraft:dead_horn_coral_fan", 0x0),
    ("minecraft:dead_tube_coral", 0x0),
    ("minecraft:dead_tube_coral_block", 0x0),
    ("minecraft:dead_tube_coral_fan", 0x0),
    ("minecraft:debug_stick", 0x48000),
    ("minecraft:decorated_pot", 0x200000400),
    ("minecraft:deepslate", 0x0),
    ("minecraft:deepslate_brick_slab", 0x0),
    ("minecraft:deepslate_brick_stairs", 0x0),
    ("minecraft:deepslate_brick_wall", 0x0),
    ("minecraft:deepslate_bricks", 0x0),
    ("minecraft:deepslate_coal_ore", 0x0),
    ("minecraft:deepslate_copper_ore", 0x0),
    ("minecraft:deepslate_diamond_ore", 0x0),
    ("minecraft:deepslate_emerald_ore", 0x0),
    ("minecraft:deepslate_gold_ore", 0x0),
    ("minecraft:deepslate_iron_ore", 0x0),
    ("minecraft:deepslate_lapis_ore", 0x0),
    ("minecraft:deepslate_redstone_ore", 0x0),
    ("minecraft:deepslate_tile_slab", 0x0),
    ("minecraft:deepslate_tile_stairs", 0x0),
    ("minecraft:deepslate_tile_wall", 0x0),
    ("minecraft:deepslate_tiles", 0x0),
    ("minecraft:detector_rail", 0x0),
    ("minecraft:diamond", 0x2000000000),
    ("minecraft:diamond_axe", 0x248020020800),
    ("minecraft:diamond_block", 0x0),
    ("minecraft:diamond_boots", 0x8020120800),
    ("minecraft:diamond_chestplate", 0x8020120800),
    ("minecraft:diamond_helmet", 0x8020120800),
    ("minecraft:diamond_hoe", 0x248020020800),
    ("minecraft:diamond_horse_armor", 0x100000),
    ("minecraft:diamond_leggings", 0x8020120800),
    ("minecraft:diamond_nautilus_armor", 0x100000),
    ("minecraft:diamond_ore", 0x0),
    ("minecraft:diamond_pickaxe", 0x248020020800),
    ("minecraft:diamond_shovel", 0x248020020800),
    ("minecraft:diamond_spear", 0x208164022801),
    ("minecraft:diamond_sword", 0x248020020800),
    ("minecraft:diorite", 0x0),
    ("minecraft:diorite_slab", 0x0),
    ("minecraft:diorite_stairs", 0x0),
    ("minecraft:diorite_wall", 0x0),
    ("minecraft:dirt", 0x0),
    ("minecraft:dirt_path", 0x0),
    ("minecraft:disc_fragment_5", 0x0),
    ("minecraft:dispenser", 0x400),
    ("minecraft:dolphin_spawn_egg", 0x80000),
    ("minecraft:donkey_spawn_egg", 0x80000),
    ("minecraft:dragon_breath", 0x0),
    ("minecraft:dragon_egg", 0x0),
    ("minecraft:dragon_head", 0x100000),
    ("minecraft:dried_ghast", 0x0),
    ("minecraft:dried_kelp", 0x400200),
    ("minecraft:dried_kelp_block", 0x0),
    ("minecraft:dripstone_block", 0x0),
    ("minecraft:dropper", 0x400),
    ("minecraft:drowned_spawn_egg", 0x80000),
    ("minecraft:dune_armor_trim_smithing_template", 0x0),
    ("minecraft:echo_shard", 0x0),
    ("minecraft:egg", 0x100),
    ("minecraft:elder_guardian_spawn_egg", 0x80000),
    ("minecraft:elytra", 0x8020900800),
    ("minecraft:emerald", 0x2000000000),
    ("minecraft:emerald_block", 0x0),
    ("minecraft:emerald_ore", 0x0),
    ("minecraft:enchanted_book", 0x10000040000),
    ("minecraft:enchanted_golden_apple", 0x440200),
    ("minecraft:enchanting_table", 0x0),
    ("minecraft:end_crystal", 0x40000),
    ("minecraft:end_portal_frame", 0x0),
    ("minecraft:end_rod", 0x0),
    ("minecraft:end_stone", 0x0),
    ("minecraft:end_stone_brick_slab", 0x0),
    ("minecraft:end_stone_brick_stairs", 0x0),
    ("minecraft:end_stone_brick_wall", 0x0),
    ("minecraft:end_stone_bricks", 0x0),
    ("minecraft:ender_chest", 0x0),
    ("minecraft:ender_dragon_spawn_egg", 0x80000),
    ("minecraft:ender_eye", 0x0),
    ("minecraft:ender_pearl", 0x80000000000),
    ("minecraft:enderman_spawn_egg", 0x80000),
    ("minecraft:endermite_spawn_egg", 0x80000),
    ("minecraft:evoker_spawn_egg", 0x80000),
    ("minecraft:experience_bottle", 0x40000),
    ("minecraft:explorer_pottery_sherd", 0x0),
    ("minecraft:exposed_chiseled_copper", 0x0),
    ("minecraft:exposed_copper", 0x0),
    ("minecraft:exposed_copper_bars", 0x0),
    ("minecraft:exposed_copper_bulb", 0x0),
    ("minecraft:exposed_copper_chain", 0x0),
    ("minecraft:exposed_copper_chest", 0x0),
    ("minecraft:exposed_copper_door", 0x0),
    ("minecraft:exposed_copper_golem_statue", 0x8),
    ("minecraft:exposed_copper_grate", 0x0),
    ("minecraft:exposed_copper_lantern", 0x0),
    ("minecraft:exposed_copper_trapdoor", 0x0),
    ("minecraft:exposed_cut_copper", 0x0),
    ("minecraft:exposed_cut_copper_slab", 0x0),
    ("minecraft:exposed_cut_copper_stairs", 0x0),
    ("minecraft:exposed_lightning_rod", 0x0),
    ("minecraft:eye_armor_trim_smithing_template", 0x0),
    ("minecraft:farmland", 0x0),
    ("minecraft:feather", 0x0),
    ("minecraft:fermented_spider_eye", 0x0),
    ("minecraft:fern", 0x0),
    ("minecraft:field_masoned_banner_pattern", 0x1000000000),
    ("minecraft:filled_map", 0x18000000),
    ("minecraft:fire_charge", 0x0),
    ("minecraft:fire_coral", 0x0),
    ("minecraft:fire_coral_block", 0x0),
    ("minecraft:fire_coral_fan", 0x0),
    ("minecraft:firefly_bush", 0x0),
    ("minecraft:firework_rocket", 0x200000),
    ("minecraft:firework_star", 0x0),
    ("minecraft:fishing_rod", 0x20020800),
    ("minecraft:fletching_table", 0x0),
    ("minecraft:flint", 0x0),
    ("minecraft:flint_and_steel", 0x20000800),
    ("minecraft:flow_armor_trim_smithing_template", 0x0),
    ("minecraft:flow_banner_pattern", 0x1000000000),
    ("minecraft:flow_pottery_sherd", 0x0),
    ("minecraft:flower_banner_pattern", 0x1000000000),
    ("minecraft:flower_pot", 0x0),
    ("minecraft:flowering_azalea", 0x0),
    ("minecraft:flowering_azalea_leaves", 0x0),
    ("minecraft:fox_spawn_egg", 0x80000),
    ("minecraft:friend_pottery_sherd", 0x0),
    ("minecraft:frog_spawn_egg", 0x80000),
    ("minecraft:frogspawn", 0x0),
    ("minecraft:furnace", 0x400),
    ("minecraft:furnace_minecart", 0x0),
    ("minecraft:ghast_spawn_egg", 0x80000),
    ("minecraft:ghast_tear", 0x0),
    ("minecraft:gilded_blackstone", 0x0),
    ("minecraft:glass", 0x0),
    ("minecraft:glass_bottle", 0x0),
    ("minecraft:glass_pane", 0x0),
    ("minecraft:glistering_melon_slice", 0x0),
    ("minecraft:globe_banner_pattern", 0x1000000000),
    ("minecraft:glow_berries", 0x400200),
    ("minecraft:glow_ink_sac", 0x0),
    ("minecraft:glow_item_frame", 0x0),
    ("minecraft:glow_lichen", 0x0),
    ("minecraft:glow_squid_spawn_egg", 0x80000),
    ("minecraft:glowstone", 0x0),
    ("minecraft:glowstone_dust", 0x0),
    ("minecraft:goat_horn", 0x1000000),
    ("minecraft:goat_spawn_egg", 0x80000),
    ("minecraft:gold_block", 0x0),
    ("minecraft:gold_ingot", 0x2000000000),
    ("minecraft:gold_nugget", 0x0),
    ("minecraft:gold_ore", 0x0),
    ("minecraft:golden_apple", 0x400200),
    ("minecraft:golden_axe", 0x248020020800),
    ("minecraft:golden_boots", 0x8020120800),
    ("minecraft:golden_carrot", 0x400200),
    ("minecraft:golden_chestplate", 0x8020120800),
    ("minecraft:golden_dandelion", 0x0),
    ("minecraft:golden_helmet", 0x8020120800),
    ("minecraft:golden_hoe", 0x248020020800),
    ("minecraft:golden_horse_armor", 0x100000),
    ("minecraft:golden_leggings", 0x8020120800),
    ("minecraft:golden_nautilus_armor", 0x100000),
    ("minecraft:golden_pickaxe", 0x248020020800),
    ("minecraft:golden_shovel", 0x248020020800),
    ("minecraft:golden_spear", 0x208164022801),
    ("minecraft:golden_sword", 0x248020020800),
    ("minecraft:granite", 0x0),
    ("minecraft:granite_slab", 0x0),
    ("minecraft:granite_stairs", 0x0),
    ("minecraft:granite_wall", 0x0),
    ("minecraft:grass_block", 0x0),
    ("minecraft:gravel", 0x0),
    ("minecraft:gray_banner", 0x2),
    ("minecraft:gray_bed", 0x0),
    ("minecraft:gray_bundle", 0x40),
    ("minecraft:gray_candle", 0x0),
    ("minecraft:gray_carpet", 0x100000),
    ("minecraft:gray_concrete", 0x0),
    ("minecraft:gray_concrete_powder", 0x0),
    ("minecraft:gray_dye", 0x10000),
    ("minecraft:gray_glazed_terracotta", 0x0),
    ("minecraft:gray_harness", 0x100000),
    ("minecraft:gray_shulker_box", 0x400),
    ("minecraft:gray_stained_glass", 0x0),
    ("minecraft:gray_stained_glass_pane", 0x0),
    ("minecraft:gray_terracotta", 0x0),
    ("minecraft:gray_wool", 0x0),
    ("minecraft:green_banner", 0x2),
    ("minecraft:green_bed", 0x0),
    ("minecraft:green_bundle", 0x40),
    ("minecraft:green_candle", 0x0),
    ("minecraft:green_carpet", 0x100000),
    ("minecraft:green_concrete", 0x0),
    ("minecraft:green_concrete_powder", 0x0),
    ("minecraft:green_dye", 0x10000),
    ("minecraft:green_glazed_terracotta", 0x0),
    ("minecraft:green_harness", 0x100000),
    ("minecraft:green_shulker_box", 0x400),
    ("minecraft:green_stained_glass", 0x0),
    ("minecraft:green_stained_glass_pane", 0x0),
    ("minecraft:green_terracotta", 0x0),
    ("minecraft:green_wool", 0x0),
    ("minecraft:grindstone", 0x0),
    ("minecraft:guardian_spawn_egg", 0x80000),
    ("minecraft:gunpowder", 0x0),
    ("minecraft:guster_banner_pattern", 0x1000000000),
    ("minecraft:guster_pottery_sherd", 0x0),
    ("minecraft:hanging_roots", 0x0),
    ("minecraft:happy_ghast_spawn_egg", 0x80000),
    ("minecraft:hay_block", 0x0),
    ("minecraft:heart_of_the_sea", 0x0),
    ("minecraft:heart_pottery_sherd", 0x0),
    ("minecraft:heartbreak_pottery_sherd", 0x0),
    ("minecraft:heavy_core", 0x0),
    ("minecraft:heavy_weighted_pressure_plate", 0x0),
    ("minecraft:hoglin_spawn_egg", 0x80000),
    ("minecraft:honey_block", 0x0),
    ("minecraft:honey_bottle", 0x100000400200),
    ("minecraft:honeycomb", 0x0),
    ("minecraft:honeycomb_block", 0x0),
    ("minecraft:hopper", 0x400),
    ("minecraft:hopper_minecart", 0x0),
    ("minecraft:horn_coral", 0x0),
    ("minecraft:horn_coral_block", 0x0),
    ("minecraft:horn_coral_fan", 0x0),
    ("minecraft:horse_spawn_egg", 0x80000),
    ("minecraft:host_armor_trim_smithing_template", 0x0),
    ("minecraft:howl_pottery_sherd", 0x0),
    ("minecraft:husk_spawn_egg", 0x80000),
    ("minecraft:ice", 0x0),
    ("minecraft:infested_chiseled_stone_bricks", 0x0),
    ("minecraft:infested_cobblestone", 0x0),
    ("minecraft:infested_cracked_stone_bricks", 0x0),
    ("minecraft:infested_deepslate", 0x0),
    ("minecraft:infested_mossy_stone_bricks", 0x0),
    ("minecraft:infested_stone", 0x0),
    ("minecraft:infested_stone_bricks", 0x0),
    ("minecraft:ink_sac", 0x0),
    ("minecraft:iron_axe", 0x248020020800),
    ("minecraft:iron_bars", 0x0),
    ("minecraft:iron_block", 0x0),
    ("minecraft:iron_boots", 0x8020120800),
    ("minecraft:iron_chain", 0x0),
    ("minecraft:iron_chestplate", 0x8020120800),
    ("minecraft:iron_door", 0x0),
    ("minecraft:iron_golem_spawn_egg", 0x80000),
    ("minecraft:iron_helmet", 0x8020120800),
    ("minecraft:iron_hoe", 0x248020020800),
    ("minecraft:iron_horse_armor", 0x100000),
    ("minecraft:iron_ingot", 0x2000000000),
    ("minecraft:iron_leggings", 0x8020120800),
    ("minecraft:iron_nautilus_armor", 0x100000),
    ("minecraft:iron_nugget", 0x0),
    ("minecraft:iron_ore", 0x0),
    ("minecraft:iron_pickaxe", 0x248020020800),
    ("minecraft:iron_shovel", 0x248020020800),
    ("minecraft:iron_spear", 0x208164022801),
    ("minecraft:iron_sword", 0x248020020800),
    ("minecraft:iron_trapdoor", 0x0),
    ("minecraft:item_frame", 0x0),
    ("minecraft:jack_o_lantern", 0x0),
    ("minecraft:jigsaw", 0x0),
    ("minecraft:jukebox", 0x0),
    ("minecraft:jungle_boat", 0x0),
    ("minecraft:jungle_button", 0x0),
    ("minecraft:jungle_chest_boat", 0x0),
    ("minecraft:jungle_door", 0x0),
    ("minecraft:jungle_fence", 0x0),
    ("minecraft:jungle_fence_gate", 0x0),
    ("minecraft:jungle_hanging_sign", 0x0),
    ("minecraft:jungle_leaves", 0x0),
    ("minecraft:jungle_log", 0x0),
    ("minecraft:jungle_planks", 0x0),
    ("minecraft:jungle_pressure_plate", 0x0),
    ("minecraft:jungle_sapling", 0x0),
    ("minecraft:jungle_shelf", 0x400),
    ("minecraft:jungle_sign", 0x0),
    ("minecraft:jungle_slab", 0x0),
    ("minecraft:jungle_stairs", 0x0),
    ("minecraft:jungle_trapdoor", 0x0),
    ("minecraft:jungle_wood", 0x0),
    ("minecraft:kelp", 0x0),
    ("minecraft:knowledge_book", 0x4000000000),
    ("minecraft:ladder", 0x0),
    ("minecraft:lantern", 0x0),
    ("minecraft:lapis_block", 0x0),
    ("minecraft:lapis_lazuli", 0x2000000000),
    ("minecraft:lapis_ore", 0x0),
    ("minecraft:large_amethyst_bud", 0x0),
    ("minecraft:large_fern", 0x0),
    ("minecraft:lava_bucket", 0x0),
    ("minecraft:lead", 0x0),
    ("minecraft:leaf_litter", 0x0),
    ("minecraft:leather", 0x0),
    ("minecraft:leather_boots", 0x8020120800),
    ("minecraft:leather_chestplate", 0x8020120800),
    ("minecraft:leather_helmet", 0x8020120800),
    ("minecraft:leather_horse_armor", 0x100000),
    ("minecraft:leather_leggings", 0x8020120800),
    ("minecraft:lectern", 0x0),
    ("minecraft:lever", 0x0),
    ("minecraft:light", 0x8),
    ("minecraft:light_blue_banner", 0x2),
    ("minecraft:light_blue_bed", 0x0),
    ("minecraft:light_blue_bundle", 0x40),
    ("minecraft:light_blue_candle", 0x0),
    ("minecraft:light_blue_carpet", 0x100000),
    ("minecraft:light_blue_concrete", 0x0),
    ("minecraft:light_blue_concrete_powder", 0x0),
    ("minecraft:light_blue_dye", 0x10000),
    ("minecraft:light_blue_glazed_terracotta", 0x0),
    ("minecraft:light_blue_harness", 0x100000),
    ("minecraft:light_blue_shulker_box", 0x400),
    ("minecraft:light_blue_stained_glass", 0x0),
    ("minecraft:light_blue_stained_glass_pane", 0x0),
    ("minecraft:light_blue_terracotta", 0x0),
    ("minecraft:light_blue_wool", 0x0),
    ("minecraft:light_gray_banner", 0x2),
    ("minecraft:light_gray_bed", 0x0),
    ("minecraft:light_gray_bundle", 0x40),
    ("minecraft:light_gray_candle", 0x0),
    ("minecraft:light_gray_carpet", 0x100000),
    ("minecraft:light_gray_concrete", 0x0),
    ("minecraft:light_gray_concrete_powder", 0x0),
    ("minecraft:light_gray_dye", 0x10000),
    ("minecraft:light_gray_glazed_terracotta", 0x0),
    ("minecraft:light_gray_harness", 0x100000),
    ("minecraft:light_gray_shulker_box", 0x400),
    ("minecraft:light_gray_stained_glass", 0x0),
    ("minecraft:light_gray_stained_glass_pane", 0x0),
    ("minecraft:light_gray_terracotta", 0x0),
    ("minecraft:light_gray_wool", 0x0),
    ("minecraft:light_weighted_pressure_plate", 0x0),
    ("minecraft:lightning_rod", 0x0),
    ("minecraft:lilac", 0x0),
    ("minecraft:lily_of_the_valley", 0x0),
    ("minecraft:lily_pad", 0x0),
    ("minecraft:lime_banner", 0x2),
    ("minecraft:lime_bed", 0x0),
    ("minecraft:lime_bundle", 0x40),
    ("minecraft:lime_candle", 0x0),
    ("minecraft:lime_carpet", 0x100000),
    ("minecraft:lime_concrete", 0x0),
    ("minecraft:lime_concrete_powder", 0x0),
    ("minecraft:lime_dye", 0x10000),
    ("minecraft:lime_glazed_terracotta", 0x0),
    ("minecraft:lime_harness", 0x100000),
    ("minecraft:lime_shulker_box", 0x400),
    ("minecraft:lime_stained_glass", 0x0),
    ("minecraft:lime_stained_glass_pane", 0x0),
    ("minecraft:lime_terracotta", 0x0),
    ("minecraft:lime_wool", 0x0),
    ("minecraft:lingering_potion", 0xc00000000),
    ("minecraft:llama_spawn_egg", 0x80000),
    ("minecraft:lodestone", 0x0),
    ("minecraft:loom", 0x0),
    ("minecraft:mace", 0x248020020800),
    ("minecraft:magenta_banner", 0x2),
    ("minecraft:magenta_bed", 0x0),
    ("minecraft:magenta_bundle", 0x40),
    ("minecraft:magenta_candle", 0x0),
    ("minecraft:magenta_carpet", 0x100000),
    ("minecraft:magenta_concrete", 0x0),
    ("minecraft:magenta_concrete_powder", 0x0),
    ("minecraft:magenta_dye", 0x10000),
    ("minecraft:magenta_glazed_terracotta", 0x0),
    ("minecraft:magenta_harness", 0x100000),
    ("minecraft:magenta_shulker_box", 0x400),
    ("minecraft:magenta_stained_glass", 0x0),
    ("minecraft:magenta_stained_glass_pane", 0x0),
    ("minecraft:magenta_terracotta", 0x0),
    ("minecraft:magenta_wool", 0x0),
    ("minecraft:magma_block", 0x0),
    ("minecraft:magma_cream", 0x0),
    ("minecraft:magma_cube_spawn_egg", 0x80000),
    ("minecraft:mangrove_boat", 0x0),
    ("minecraft:mangrove_button", 0x0),
    ("minecraft:mangrove_chest_boat", 0x0),
    ("minecraft:mangrove_door", 0x0),
    ("minecraft:mangrove_fence", 0x0),
    ("minecraft:mangrove_fence_gate", 0x0),
    ("minecraft:mangrove_hanging_sign", 0x0),
    ("minecraft:mangrove_leaves", 0x0),
    ("minecraft:mangrove_log", 0x0),
    ("minecraft:mangrove_planks", 0x0),
    ("minecraft:mangrove_pressure_plate", 0x0),
    ("minecraft:mangrove_propagule", 0x0),
    ("minecraft:mangrove_roots", 0x0),
    ("minecraft:mangrove_shelf", 0x400),
    ("minecraft:mangrove_sign", 0x0),
    ("minecraft:mangrove_slab", 0x0),
    ("minecraft:mangrove_stairs", 0x0),
    ("minecraft:mangrove_trapdoor", 0x0),
    ("minecraft:mangrove_wood", 0x0),
    ("minecraft:map", 0x0),
    ("minecraft:medium_amethyst_bud", 0x0),
    ("minecraft:melon", 0x0),
    ("minecraft:melon_seeds", 0x0),
    ("minecraft:melon_slice", 0x400200),
    ("minecraft:milk_bucket", 0x100000000200),
    ("minecraft:minecart", 0x0),
    ("minecraft:miner_pottery_sherd", 0x0),
    ("minecraft:mojang_banner_pattern", 0x1000000000),
    ("minecraft:mooshroom_spawn_egg", 0x80000),
    ("minecraft:moss_block", 0x0),
    ("minecraft:moss_carpet", 0x0),
    ("minecraft:mossy_cobblestone", 0x0),
    ("minecraft:mossy_cobblestone_slab", 0x0),
    ("minecraft:mossy_cobblestone_stairs", 0x0),
    ("minecraft:mossy_cobblestone_wall", 0x0),
    ("minecraft:mossy_stone_brick_slab", 0x0),
    ("minecraft:mossy_stone_brick_stairs", 0x0),
    ("minecraft:mossy_stone_brick_wall", 0x0),
    ("minecraft:mossy_stone_bricks", 0x0),
    ("minecraft:mourner_pottery_sherd", 0x0),
    ("minecraft:mud", 0x0),
    ("minecraft:mud_brick_slab", 0x0),
    ("minecraft:mud_brick_stairs", 0x0),
    ("minecraft:mud_brick_wall", 0x0),
    ("minecraft:mud_bricks", 0x0),
    ("minecraft:muddy_mangrove_roots", 0x0),
    ("minecraft:mule_spawn_egg", 0x80000),
    ("minecraft:mushroom_stem", 0x0),
    ("minecraft:mushroom_stew", 0x100000400200),
    ("minecraft:music_disc_11", 0x2000000),
    ("minecraft:music_disc_13", 0x2000000),
    ("minecraft:music_disc_5", 0x2000000),
    ("minecraft:music_disc_blocks", 0x2000000),
    ("minecraft:music_disc_bounce", 0x2000000),
    ("minecraft:music_disc_cat", 0x2000000),
    ("minecraft:music_disc_chirp", 0x2000000),
    ("minecraft:music_disc_creator", 0x2000000),
    ("minecraft:music_disc_creator_music_box", 0x2000000),
    ("minecraft:music_disc_far", 0x2000000),
    ("minecraft:music_disc_lava_chicken", 0x2000000),
    ("minecraft:music_disc_mall", 0x2000000),
    ("minecraft:music_disc_mellohi", 0x2000000),
    ("minecraft:music_disc_otherside", 0x2000000),
    ("minecraft:music_disc_pigstep", 0x2000000),
    ("minecraft:music_disc_precipice", 0x2000000),
    ("minecraft:music_disc_relic", 0x2000000),
    ("minecraft:music_disc_stal", 0x2000000),
    ("minecraft:music_disc_strad", 0x2000000),
    ("minecraft:music_disc_tears", 0x2000000),
    ("minecraft:music_disc_wait", 0x2000000),
    ("minecraft:music_disc_ward", 0x2000000),
    ("minecraft:mutton", 0x400200),
    ("minecraft:mycelium", 0x0),
    ("minecraft:name_tag", 0x0),
    ("minecraft:nautilus_shell", 0x0),
    ("minecraft:nautilus_spawn_egg", 0x80000),
    ("minecraft:nether_brick", 0x0),
    ("minecraft:nether_brick_fence", 0x0),
    ("minecraft:nether_brick_slab", 0x0),
    ("minecraft:nether_brick_stairs", 0x0),
    ("minecraft:nether_brick_wall", 0x0),
    ("minecraft:nether_bricks", 0x0),
    ("minecraft:nether_gold_ore", 0x0),
    ("minecraft:nether_quartz_ore", 0x0),
    ("minecraft:nether_sprouts", 0x0),
    ("minecraft:nether_star", 0x41000),
    ("minecraft:nether_wart", 0x0),
    ("minecraft:nether_wart_block", 0x0),
    ("minecraft:netherite_axe", 0x248020021800),
    ("minecraft:netherite_block", 0x1000),
    ("minecraft:netherite_boots", 0x8020121800),
    ("minecraft:netherite_chestplate", 0x8020121800),
    ("minecraft:netherite_helmet", 0x8020121800),
    ("minecraft:netherite_hoe", 0x248020021800),
    ("minecraft:netherite_horse_armor", 0x101000),
    ("minecraft:netherite_ingot", 0x2000001000),
    ("minecraft:netherite_leggings", 0x8020121800),
    ("minecraft:netherite_nautilus_armor", 0x101000),
    ("minecraft:netherite_pickaxe", 0x248020021800),
    ("minecraft:netherite_scrap", 0x1000),
    ("minecraft:netherite_shovel", 0x248020021800),
    ("minecraft:netherite_spear", 0x208164023801),
    ("minecraft:netherite_sword", 0x248020021800),
    ("minecraft:netherite_upgrade_smithing_template", 0x0),
    ("minecraft:netherrack", 0x0),
    ("minecraft:note_block", 0x0),
    ("minecraft:oak_boat", 0x0),
    ("minecraft:oak_button", 0x0),
    ("minecraft:oak_chest_boat", 0x0),
    ("minecraft:oak_door", 0x0),
    ("minecraft:oak_fence", 0x0),
    ("minecraft:oak_fence_gate", 0x0),
    ("minecraft:oak_hanging_sign", 0x0),
    ("minecraft:oak_leaves", 0x0),
    ("minecraft:oak_log", 0x0),
    ("minecraft:oak_planks", 0x0),
    ("minecraft:oak_pressure_plate", 0x0),
    ("minecraft:oak_sapling", 0x0),
    ("minecraft:oak_shelf", 0x400),
    ("minecraft:oak_sign", 0x0),
    ("minecraft:oak_slab", 0x0),
    ("minecraft:oak_stairs", 0x0),
    ("minecraft:oak_trapdoor", 0x0),
    ("minecraft:oak_wood", 0x0),
    ("minecraft:observer", 0x0),
    ("minecraft:obsidian", 0x0),
    ("minecraft:ocelot_spawn_egg", 0x80000),
    ("minecraft:ochre_froglight", 0x0),
    ("minecraft:ominous_bottle", 0x80000200),
    ("minecraft:ominous_trial_key", 0x0),
    ("minecraft:open_eyeblossom", 0x0),
    ("minecraft:orange_banner", 0x2),
    ("minecraft:orange_bed", 0x0),
    ("minecraft:orange_bundle", 0x40),
    ("minecraft:orange_candle", 0x0),
    ("minecraft:orange_carpet", 0x100000),
    ("minecraft:orange_concrete", 0x0),
    ("minecraft:orange_concrete_powder", 0x0),
    ("minecraft:orange_dye", 0x10000),
    ("minecraft:orange_glazed_terracotta", 0x0),
    ("minecraft:orange_harness", 0x100000),
    ("minecraft:orange_shulker_box", 0x400),
    ("minecraft:orange_stained_glass", 0x0),
    ("minecraft:orange_stained_glass_pane", 0x0),
    ("minecraft:orange_terracotta", 0x0),
    ("minecraft:orange_tulip", 0x0),
    ("minecraft:orange_wool", 0x0),
    ("minecraft:oxeye_daisy", 0x0),
    ("minecraft:oxidized_chiseled_copper", 0x0),
    ("minecraft:oxidized_copper", 0x0),
    ("minecraft:oxidized_copper_bars", 0x0),
    ("minecraft:oxidized_copper_bulb", 0x0),
    ("minecraft:oxidized_copper_chain", 0x0),
    ("minecraft:oxidized_copper_chest", 0x0),
    ("minecraft:oxidized_copper_door", 0x0),
    ("minecraft:oxidized_copper_golem_statue", 0x8),
    ("minecraft:oxidized_copper_grate", 0x0),
    ("minecraft:oxidized_copper_lantern", 0x0),
    ("minecraft:oxidized_copper_trapdoor", 0x0),
    ("minecraft:oxidized_cut_copper", 0x0),
    ("minecraft:oxidized_cut_copper_slab", 0x0),
    ("minecraft:oxidized_cut_copper_stairs", 0x0),
    ("minecraft:oxidized_lightning_rod", 0x0),
    ("minecraft:packed_ice", 0x0),
    ("minecraft:packed_mud", 0x0),
    ("minecraft:painting", 0x0),
    ("minecraft:pale_hanging_moss", 0x0),
    ("minecraft:pale_moss_block", 0x0),
    ("minecraft:pale_moss_carpet", 0x0),
    ("minecraft:pale_oak_boat", 0x0),
    ("minecraft:pale_oak_button", 0x0),
    ("minecraft:pale_oak_chest_boat", 0x0),
    ("minecraft:pale_oak_door", 0x0),
    ("minecraft:pale_oak_fence", 0x0),
    ("minecraft:pale_oak_fence_gate", 0x0),
    ("minecraft:pale_oak_hanging_sign", 0x0),
    ("minecraft:pale_oak_leaves", 0x0),
    ("minecraft:pale_oak_log", 0x0),
    ("minecraft:pale_oak_planks", 0x0),
    ("minecraft:pale_oak_pressure_plate", 0x0),
    ("minecraft:pale_oak_sapling", 0x0),
    ("minecraft:pale_oak_shelf", 0x400),
    ("minecraft:pale_oak_sign", 0x0),
    ("minecraft:pale_oak_slab", 0x0),
    ("minecraft:pale_oak_stairs", 0x0),
    ("minecraft:pale_oak_trapdoor", 0x0),
    ("minecraft:pale_oak_wood", 0x0),
    ("minecraft:panda_spawn_egg", 0x80000),
    ("minecraft:paper", 0x0),
    ("minecraft:parched_spawn_egg", 0x80000),
    ("minecraft:parrot_spawn_egg", 0x80000),
    ("minecraft:pearlescent_froglight", 0x0),
    ("minecraft:peony", 0x0),
    ("minecraft:petrified_oak_slab", 0x0),
    ("minecraft:phantom_membrane", 0x0),
    ("minecraft:phantom_spawn_egg", 0x80000),
    ("minecraft:pig_spawn_egg", 0x80000),
    ("minecraft:piglin_banner_pattern", 0x1000000000),
    ("minecraft:piglin_brute_spawn_egg", 0x80000),
    ("minecraft:piglin_head", 0x100000),
    ("minecraft:piglin_spawn_egg", 0x80000),
    ("minecraft:pillager_spawn_egg", 0x80000),
    ("minecraft:pink_banner", 0x2),
    ("minecraft:pink_bed", 0x0),
    ("minecraft:pink_bundle", 0x40),
    ("minecraft:pink_candle", 0x0),
    ("minecraft:pink_carpet", 0x100000),
    ("minecraft:pink_concrete", 0x0),
    ("minecraft:pink_concrete_powder", 0x0),
    ("minecraft:pink_dye", 0x10000),
    ("minecraft:pink_glazed_terracotta", 0x0),
    ("minecraft:pink_harness", 0x100000),
    ("minecraft:pink_petals", 0x0),
    ("minecraft:pink_shulker_box", 0x400),
    ("minecraft:pink_stained_glass", 0x0),
    ("minecraft:pink_stained_glass_pane", 0x0),
    ("minecraft:pink_terracotta", 0x0),
    ("minecraft:pink_tulip", 0x0),
    ("minecraft:pink_wool", 0x0),
    ("minecraft:piston", 0x0),
    ("minecraft:pitcher_plant", 0x0),
    ("minecraft:pitcher_pod", 0x0),
    ("minecraft:player_head", 0x100000),
    ("minecraft:plenty_pottery_sherd", 0x0),
    ("minecraft:podzol", 0x0),
    ("minecraft:pointed_dripstone", 0x0),
    ("minecraft:poisonous_potato", 0x400200),
    ("minecraft:polar_bear_spawn_egg", 0x80000),
    ("minecraft:polished_andesite", 0x0),
    ("minecraft:polished_andesite_slab", 0x0),
    ("minecraft:polished_andesite_stairs", 0x0),
    ("minecraft:polished_basalt", 0x0),
    ("minecraft:polished_blackstone", 0x0),
    ("minecraft:polished_blackstone_brick_slab", 0x0),
    ("minecraft:polished_blackstone_brick_stairs", 0x0),
    ("minecraft:polished_blackstone_brick_wall", 0x0),
    ("minecraft:polished_blackstone_bricks", 0x0),
    ("minecraft:polished_blackstone_button", 0x0),
    ("minecraft:polished_blackstone_pressure_plate", 0x0),
    ("minecraft:polished_blackstone_slab", 0x0),
    ("minecraft:polished_blackstone_stairs", 0x0),
    ("minecraft:polished_blackstone_wall", 0x0),
    ("minecraft:polished_cinnabar", 0x0),
    ("minecraft:polished_cinnabar_slab", 0x0),
    ("minecraft:polished_cinnabar_stairs", 0x0),
    ("minecraft:polished_cinnabar_wall", 0x0),
    ("minecraft:polished_deepslate", 0x0),
    ("minecraft:polished_deepslate_slab", 0x0),
    ("minecraft:polished_deepslate_stairs", 0x0),
    ("minecraft:polished_deepslate_wall", 0x0),
    ("minecraft:polished_diorite", 0x0),
    ("minecraft:polished_diorite_slab", 0x0),
    ("minecraft:polished_diorite_stairs", 0x0),
    ("minecraft:polished_granite", 0x0),
    ("minecraft:polished_granite_slab", 0x0),
    ("minecraft:polished_granite_stairs", 0x0),
    ("minecraft:polished_sulfur", 0x0),
    ("minecraft:polished_sulfur_slab", 0x0),
    ("minecraft:polished_sulfur_stairs", 0x0),
    ("minecraft:polished_sulfur_wall", 0x0),
    ("minecraft:polished_tuff", 0x0),
    ("minecraft:polished_tuff_slab", 0x0),
    ("minecraft:polished_tuff_stairs", 0x0),
    ("minecraft:polished_tuff_wall", 0x0),
    ("minecraft:popped_chorus_fruit", 0x0),
    ("minecraft:poppy", 0x0),
    ("minecraft:porkchop", 0x400200),
    ("minecraft:potato", 0x400200),
    ("minecraft:potent_sulfur", 0x0),
    ("minecraft:potion", 0x100400000200),
    ("minecraft:powder_snow_bucket", 0x0),
    ("minecraft:powered_rail", 0x0),
    ("minecraft:prismarine", 0x0),
    ("minecraft:prismarine_brick_slab", 0x0),
    ("minecraft:prismarine_brick_stairs", 0x0),
    ("minecraft:prismarine_bricks", 0x0),
    ("minecraft:prismarine_crystals", 0x0),
    ("minecraft:prismarine_shard", 0x0),
    ("minecraft:prismarine_slab", 0x0),
    ("minecraft:prismarine_stairs", 0x0),
    ("minecraft:prismarine_wall", 0x0),
    ("minecraft:prize_pottery_sherd", 0x0),
    ("minecraft:pufferfish", 0x400200),
    ("minecraft:pufferfish_bucket", 0x400020),
    ("minecraft:pufferfish_spawn_egg", 0x80000),
    ("minecraft:pumpkin", 0x0),
    ("minecraft:pumpkin_pie", 0x400200),
    ("minecraft:pumpkin_seeds", 0x0),
    ("minecraft:purple_banner", 0x2),
    ("minecraft:purple_bed", 0x0),
    ("minecraft:purple_bundle", 0x40),
    ("minecraft:purple_candle", 0x0),
    ("minecraft:purple_carpet", 0x100000),
    ("minecraft:purple_concrete", 0x0),
    ("minecraft:purple_concrete_powder", 0x0),
    ("minecraft:purple_dye", 0x10000),
    ("minecraft:purple_glazed_terracotta", 0x0),
    ("minecraft:purple_harness", 0x100000),
    ("minecraft:purple_shulker_box", 0x400),
    ("minecraft:purple_stained_glass", 0x0),
    ("minecraft:purple_stained_glass_pane", 0x0),
    ("minecraft:purple_terracotta", 0x0),
    ("minecraft:purple_wool", 0x0),
    ("minecraft:purpur_block", 0x0),
    ("minecraft:purpur_pillar", 0x0),
    ("minecraft:purpur_slab", 0x0),
    ("minecraft:purpur_stairs", 0x0),
    ("minecraft:quartz", 0x2000000000),
    ("minecraft:quartz_block", 0x0),
    ("minecraft:quartz_bricks", 0x0),
    ("minecraft:quartz_pillar", 0x0),
    ("minecraft:quartz_slab", 0x0),
    ("minecraft:quartz_stairs", 0x0),
    ("minecraft:rabbit", 0x400200),
    ("minecraft:rabbit_foot", 0x0),
    ("minecraft:rabbit_hide", 0x0),
    ("minecraft:rabbit_spawn_egg", 0x80000),
    ("minecraft:rabbit_stew", 0x100000400200),
    ("minecraft:rail", 0x0),
    ("minecraft:raiser_armor_trim_smithing_template", 0x0),
    ("minecraft:ravager_spawn_egg", 0x80000),
    ("minecraft:raw_copper", 0x0),
    ("minecraft:raw_copper_block", 0x0),
    ("minecraft:raw_gold", 0x0),
    ("minecraft:raw_gold_block", 0x0),
    ("minecraft:raw_iron", 0x0),
    ("minecraft:raw_iron_block", 0x0),
    ("minecraft:recovery_compass", 0x0),
    ("minecraft:red_banner", 0x2),
    ("minecraft:red_bed", 0x0),
    ("minecraft:red_bundle", 0x40),
    ("minecraft:red_candle", 0x0),
    ("minecraft:red_carpet", 0x100000),
    ("minecraft:red_concrete", 0x0),
    ("minecraft:red_concrete_powder", 0x0),
    ("minecraft:red_dye", 0x10000),
    ("minecraft:red_glazed_terracotta", 0x0),
    ("minecraft:red_harness", 0x100000),
    ("minecraft:red_mushroom", 0x0),
    ("minecraft:red_mushroom_block", 0x0),
    ("minecraft:red_nether_brick_slab", 0x0),
    ("minecraft:red_nether_brick_stairs", 0x0),
    ("minecraft:red_nether_brick_wall", 0x0),
    ("minecraft:red_nether_bricks", 0x0),
    ("minecraft:red_sand", 0x0),
    ("minecraft:red_sandstone", 0x0),
    ("minecraft:red_sandstone_slab", 0x0),
    ("minecraft:red_sandstone_stairs", 0x0),
    ("minecraft:red_sandstone_wall", 0x0),
    ("minecraft:red_shulker_box", 0x400),
    ("minecraft:red_stained_glass", 0x0),
    ("minecraft:red_stained_glass_pane", 0x0),
    ("minecraft:red_terracotta", 0x0),
    ("minecraft:red_tulip", 0x0),
    ("minecraft:red_wool", 0x0),
    ("minecraft:redstone", 0x2000000000),
    ("minecraft:redstone_block", 0x0),
    ("minecraft:redstone_lamp", 0x0),
    ("minecraft:redstone_ore", 0x0),
    ("minecraft:redstone_torch", 0x0),
    ("minecraft:reinforced_deepslate", 0x0),
    ("minecraft:repeater", 0x0),
    ("minecraft:repeating_command_block", 0x0),
    ("minecraft:resin_block", 0x0),
    ("minecraft:resin_brick", 0x2000000000),
    ("minecraft:resin_brick_slab", 0x0),
    ("minecraft:resin_brick_stairs", 0x0),
    ("minecraft:resin_brick_wall", 0x0),
    ("minecraft:resin_bricks", 0x0),
    ("minecraft:resin_clump", 0x0),
    ("minecraft:respawn_anchor", 0x0),
    ("minecraft:rib_armor_trim_smithing_template", 0x0),
    ("minecraft:rooted_dirt", 0x0),
    ("minecraft:rose_bush", 0x0),
    ("minecraft:rotten_flesh", 0x400200),
    ("minecraft:saddle", 0x100000),
    ("minecraft:salmon", 0x400200),
    ("minecraft:salmon_bucket", 0x400020),
    ("minecraft:salmon_spawn_egg", 0x80000),
    ("minecraft:sand", 0x0),
    ("minecraft:sandstone", 0x0),
    ("minecraft:sandstone_slab", 0x0),
    ("minecraft:sandstone_stairs", 0x0),
    ("minecraft:sandstone_wall", 0x0),
    ("minecraft:scaffolding", 0x0),
    ("minecraft:scrape_pottery_sherd", 0x0),
    ("minecraft:sculk", 0x0),
    ("minecraft:sculk_catalyst", 0x0),
    ("minecraft:sculk_sensor", 0x0),
    ("minecraft:sculk_shrieker", 0x0),
    ("minecraft:sculk_vein", 0x0),
    ("minecraft:sea_lantern", 0x0),
    ("minecraft:sea_pickle", 0x0),
    ("minecraft:seagrass", 0x0),
    ("minecraft:sentry_armor_trim_smithing_template", 0x0),
    ("minecraft:shaper_armor_trim_smithing_template", 0x0),
    ("minecraft:sheaf_pottery_sherd", 0x0),
    ("minecraft:shears", 0x40020000800),
    ("minecraft:sheep_spawn_egg", 0x80000),
    ("minecraft:shelter_pottery_sherd", 0x0),
    ("minecraft:shield", 0x8020100812),
    ("minecraft:short_dry_grass", 0x0),
    ("minecraft:short_grass", 0x0),
    ("minecraft:shroomlight", 0x0),
    ("minecraft:shulker_box", 0x400),
    ("minecraft:shulker_shell", 0x0),
    ("minecraft:shulker_spawn_egg", 0x80000),
    ("minecraft:silence_armor_trim_smithing_template", 0x0),
    ("minecraft:silverfish_spawn_egg", 0x80000),
    ("minecraft:skeleton_horse_spawn_egg", 0x80000),
    ("minecraft:skeleton_skull", 0x100000),
    ("minecraft:skeleton_spawn_egg", 0x80000),
    ("minecraft:skull_banner_pattern", 0x1000000000),
    ("minecraft:skull_pottery_sherd", 0x0),
    ("minecraft:slime_ball", 0x0),
    ("minecraft:slime_block", 0x0),
    ("minecraft:slime_spawn_egg", 0x80000),
    ("minecraft:small_amethyst_bud", 0x0),
    ("minecraft:small_dripleaf", 0x0),
    ("minecraft:smithing_table", 0x0),
    ("minecraft:smoker", 0x400),
    ("minecraft:smooth_basalt", 0x0),
    ("minecraft:smooth_quartz", 0x0),
    ("minecraft:smooth_quartz_slab", 0x0),
    ("minecraft:smooth_quartz_stairs", 0x0),
    ("minecraft:smooth_red_sandstone", 0x0),
    ("minecraft:smooth_red_sandstone_slab", 0x0),
    ("minecraft:smooth_red_sandstone_stairs", 0x0),
    ("minecraft:smooth_sandstone", 0x0),
    ("minecraft:smooth_sandstone_slab", 0x0),
    ("minecraft:smooth_sandstone_stairs", 0x0),
    ("minecraft:smooth_stone", 0x0),
    ("minecraft:smooth_stone_slab", 0x0),
    ("minecraft:sniffer_egg", 0x0),
    ("minecraft:sniffer_spawn_egg", 0x80000),
    ("minecraft:snort_pottery_sherd", 0x0),
    ("minecraft:snout_armor_trim_smithing_template", 0x0),
    ("minecraft:snow", 0x0),
    ("minecraft:snow_block", 0x0),
    ("minecraft:snow_golem_spawn_egg", 0x80000),
    ("minecraft:snowball", 0x0),
    ("minecraft:soul_campfire", 0x400),
    ("minecraft:soul_lantern", 0x0),
    ("minecraft:soul_sand", 0x0),
    ("minecraft:soul_soil", 0x0),
    ("minecraft:soul_torch", 0x0),
    ("minecraft:spawner", 0x0),
    ("minecraft:spectral_arrow", 0x0),
    ("minecraft:spider_eye", 0x400200),
    ("minecraft:spider_spawn_egg", 0x80000),
    ("minecraft:spire_armor_trim_smithing_template", 0x0),
    ("minecraft:splash_potion", 0x400000000),
    ("minecraft:sponge", 0x0),
    ("minecraft:spore_blossom", 0x0),
    ("minecraft:spruce_boat", 0x0),
    ("minecraft:spruce_button", 0x0),
    ("minecraft:spruce_chest_boat", 0x0),
    ("minecraft:spruce_door", 0x0),
    ("minecraft:spruce_fence", 0x0),
    ("minecraft:spruce_fence_gate", 0x0),
    ("minecraft:spruce_hanging_sign", 0x0),
    ("minecraft:spruce_leaves", 0x0),
    ("minecraft:spruce_log", 0x0),
    ("minecraft:spruce_planks", 0x0),
    ("minecraft:spruce_pressure_plate", 0x0),
    ("minecraft:spruce_sapling", 0x0),
    ("minecraft:spruce_shelf", 0x400),
    ("minecraft:spruce_sign", 0x0),
    ("minecraft:spruce_slab", 0x0),
    ("minecraft:spruce_stairs", 0x0),
    ("minecraft:spruce_trapdoor", 0x0),
    ("minecraft:spruce_wood", 0x0),
    ("minecraft:spyglass", 0x0),
    ("minecraft:squid_spawn_egg", 0x80000),
    ("minecraft:stick", 0x0),
    ("minecraft:sticky_piston", 0x0),
    ("minecraft:stone", 0x0),
    ("minecraft:stone_axe", 0x248020020800),
    ("minecraft:stone_brick_slab", 0x0),
    ("minecraft:stone_brick_stairs", 0x0),
    ("minecraft:stone_brick_wall", 0x0),
    ("minecraft:stone_bricks", 0x0),
    ("minecraft:stone_button", 0x0),
    ("minecraft:stone_hoe", 0x248020020800),
    ("minecraft:stone_pickaxe", 0x248020020800),
    ("minecraft:stone_pressure_plate", 0x0),
    ("minecraft:stone_shovel", 0x248020020800),
    ("minecraft:stone_slab", 0x0),
    ("minecraft:stone_spear", 0x208164022801),
    ("minecraft:stone_stairs", 0x0),
    ("minecraft:stone_sword", 0x248020020800),
    ("minecraft:stonecutter", 0x0),
    ("minecraft:stray_spawn_egg", 0x80000),
    ("minecraft:strider_spawn_egg", 0x80000),
    ("minecraft:string", 0x0),
    ("minecraft:stripped_acacia_log", 0x0),
    ("minecraft:stripped_acacia_wood", 0x0),
    ("minecraft:stripped_bamboo_block", 0x0),
    ("minecraft:stripped_birch_log", 0x0),
    ("minecraft:stripped_birch_wood", 0x0),
    ("minecraft:stripped_cherry_log", 0x0),
    ("minecraft:stripped_cherry_wood", 0x0),
    ("minecraft:stripped_crimson_hyphae", 0x0),
    ("minecraft:stripped_crimson_stem", 0x0),
    ("minecraft:stripped_dark_oak_log", 0x0),
    ("minecraft:stripped_dark_oak_wood", 0x0),
    ("minecraft:stripped_jungle_log", 0x0),
    ("minecraft:stripped_jungle_wood", 0x0),
    ("minecraft:stripped_mangrove_log", 0x0),
    ("minecraft:stripped_mangrove_wood", 0x0),
    ("minecraft:stripped_oak_log", 0x0),
    ("minecraft:stripped_oak_wood", 0x0),
    ("minecraft:stripped_pale_oak_log", 0x0),
    ("minecraft:stripped_pale_oak_wood", 0x0),
    ("minecraft:stripped_spruce_log", 0x0),
    ("minecraft:stripped_spruce_wood", 0x0),
    ("minecraft:stripped_warped_hyphae", 0x0),
    ("minecraft:stripped_warped_stem", 0x0),
    ("minecraft:structure_block", 0x0),
    ("minecraft:structure_void", 0x0),
    ("minecraft:sugar", 0x0),
    ("minecraft:sugar_cane", 0x0),
    ("minecraft:sulfur", 0x0),
    ("minecraft:sulfur_brick_slab", 0x0),
    ("minecraft:sulfur_brick_stairs", 0x0),
    ("minecraft:sulfur_brick_wall", 0x0),
    ("minecraft:sulfur_bricks", 0x0),
    ("minecraft:sulfur_cube_bucket", 0x20),
    ("minecraft:sulfur_cube_spawn_egg", 0x80000),
    ("minecraft:sulfur_slab", 0x0),
    ("minecraft:sulfur_spike", 0x0),
    ("minecraft:sulfur_stairs", 0x0),
    ("minecraft:sulfur_wall", 0x0),
    ("minecraft:sunflower", 0x0),
    ("minecraft:suspicious_gravel", 0x0),
    ("minecraft:suspicious_sand", 0x0),
    ("minecraft:suspicious_stew", 0x120000400200),
    ("minecraft:sweet_berries", 0x400200),
    ("minecraft:tadpole_bucket", 0x20),
    ("minecraft:tadpole_spawn_egg", 0x80000),
    ("minecraft:tall_dry_grass", 0x0),
    ("minecraft:tall_grass", 0x0),
    ("minecraft:target", 0x0),
    ("minecraft:terracotta", 0x0),
    ("minecraft:test_block", 0x8),
    ("minecraft:test_instance_block", 0x0),
    ("minecraft:tide_armor_trim_smithing_template", 0x0),
    ("minecraft:tinted_glass", 0x0),
    ("minecraft:tipped_arrow", 0xc00000000),
    ("minecraft:tnt", 0x0),
    ("minecraft:tnt_minecart", 0x0),
    ("minecraft:torch", 0x0),
    ("minecraft:torchflower", 0x0),
    ("minecraft:torchflower_seeds", 0x0),
    ("minecraft:totem_of_undying", 0x4000),
    ("minecraft:trader_llama_spawn_egg", 0x80000),
    ("minecraft:trapped_chest", 0x400),
    ("minecraft:trial_key", 0x0),
    ("minecraft:trial_spawner", 0x0),
    ("minecraft:trident", 0x240020020800),
    ("minecraft:tripwire_hook", 0x0),
    ("minecraft:tropical_fish", 0x400200),
    ("minecraft:tropical_fish_bucket", 0x400020),
    ("minecraft:tropical_fish_spawn_egg", 0x80000),
    ("minecraft:tube_coral", 0x0),
    ("minecraft:tube_coral_block", 0x0),
    ("minecraft:tube_coral_fan", 0x0),
    ("minecraft:tuff", 0x0),
    ("minecraft:tuff_brick_slab", 0x0),
    ("minecraft:tuff_brick_stairs", 0x0),
    ("minecraft:tuff_brick_wall", 0x0),
    ("minecraft:tuff_bricks", 0x0),
    ("minecraft:tuff_slab", 0x0),
    ("minecraft:tuff_stairs", 0x0),
    ("minecraft:tuff_wall", 0x0),
    ("minecraft:turtle_egg", 0x0),
    ("minecraft:turtle_helmet", 0x8020120800),
    ("minecraft:turtle_scute", 0x0),
    ("minecraft:turtle_spawn_egg", 0x80000),
    ("minecraft:twisting_vines", 0x0),
    ("minecraft:vault", 0x0),
    ("minecraft:verdant_froglight", 0x0),
    ("minecraft:vex_armor_trim_smithing_template", 0x0),
    ("minecraft:vex_spawn_egg", 0x80000),
    ("minecraft:villager_spawn_egg", 0x80000),
    ("minecraft:vindicator_spawn_egg", 0x80000),
    ("minecraft:vine", 0x0),
    ("minecraft:wandering_trader_spawn_egg", 0x80000),
    ("minecraft:ward_armor_trim_smithing_template", 0x0),
    ("minecraft:warden_spawn_egg", 0x80000),
    ("minecraft:warped_button", 0x0),
    ("minecraft:warped_door", 0x0),
    ("minecraft:warped_fence", 0x0),
    ("minecraft:warped_fence_gate", 0x0),
    ("minecraft:warped_fungus", 0x0),
    ("minecraft:warped_fungus_on_a_stick", 0x20000800),
    ("minecraft:warped_hanging_sign", 0x0),
    ("minecraft:warped_hyphae", 0x0),
    ("minecraft:warped_nylium", 0x0),
    ("minecraft:warped_planks", 0x0),
    ("minecraft:warped_pressure_plate", 0x0),
    ("minecraft:warped_roots", 0x0),
    ("minecraft:warped_shelf", 0x400),
    ("minecraft:warped_sign", 0x0),
    ("minecraft:warped_slab", 0x0),
    ("minecraft:warped_stairs", 0x0),
    ("minecraft:warped_stem", 0x0),
    ("minecraft:warped_trapdoor", 0x0),
    ("minecraft:warped_wart_block", 0x0),
    ("minecraft:water_bucket", 0x0),
    ("minecraft:waxed_chiseled_copper", 0x0),
    ("minecraft:waxed_copper_bars", 0x0),
    ("minecraft:waxed_copper_block", 0x0),
    ("minecraft:waxed_copper_bulb", 0x0),
    ("minecraft:waxed_copper_chain", 0x0),
    ("minecraft:waxed_copper_chest", 0x0),
    ("minecraft:waxed_copper_door", 0x0),
    ("minecraft:waxed_copper_golem_statue", 0x8),
    ("minecraft:waxed_copper_grate", 0x0),
    ("minecraft:waxed_copper_lantern", 0x0),
    ("minecraft:waxed_copper_trapdoor", 0x0),
    ("minecraft:waxed_cut_copper", 0x0),
    ("minecraft:waxed_cut_copper_slab", 0x0),
    ("minecraft:waxed_cut_copper_stairs", 0x0),
    ("minecraft:waxed_exposed_chiseled_copper", 0x0),
    ("minecraft:waxed_exposed_copper", 0x0),
    ("minecraft:waxed_exposed_copper_bars", 0x0),
    ("minecraft:waxed_exposed_copper_bulb", 0x0),
    ("minecraft:waxed_exposed_copper_chain", 0x0),
    ("minecraft:waxed_exposed_copper_chest", 0x0),
    ("minecraft:waxed_exposed_copper_door", 0x0),
    ("minecraft:waxed_exposed_copper_golem_statue", 0x8),
    ("minecraft:waxed_exposed_copper_grate", 0x0),
    ("minecraft:waxed_exposed_copper_lantern", 0x0),
    ("minecraft:waxed_exposed_copper_trapdoor", 0x0),
    ("minecraft:waxed_exposed_cut_copper", 0x0),
    ("minecraft:waxed_exposed_cut_copper_slab", 0x0),
    ("minecraft:waxed_exposed_cut_copper_stairs", 0x0),
    ("minecraft:waxed_exposed_lightning_rod", 0x0),
    ("minecraft:waxed_lightning_rod", 0x0),
    ("minecraft:waxed_oxidized_chiseled_copper", 0x0),
    ("minecraft:waxed_oxidized_copper", 0x0),
    ("minecraft:waxed_oxidized_copper_bars", 0x0),
    ("minecraft:waxed_oxidized_copper_bulb", 0x0),
    ("minecraft:waxed_oxidized_copper_chain", 0x0),
    ("minecraft:waxed_oxidized_copper_chest", 0x0),
    ("minecraft:waxed_oxidized_copper_door", 0x0),
    ("minecraft:waxed_oxidized_copper_golem_statue", 0x8),
    ("minecraft:waxed_oxidized_copper_grate", 0x0),
    ("minecraft:waxed_oxidized_copper_lantern", 0x0),
    ("minecraft:waxed_oxidized_copper_trapdoor", 0x0),
    ("minecraft:waxed_oxidized_cut_copper", 0x0),
    ("minecraft:waxed_oxidized_cut_copper_slab", 0x0),
    ("minecraft:waxed_oxidized_cut_copper_stairs", 0x0),
    ("minecraft:waxed_oxidized_lightning_rod", 0x0),
    ("minecraft:waxed_weathered_chiseled_copper", 0x0),
    ("minecraft:waxed_weathered_copper", 0x0),
    ("minecraft:waxed_weathered_copper_bars", 0x0),
    ("minecraft:waxed_weathered_copper_bulb", 0x0),
    ("minecraft:waxed_weathered_copper_chain", 0x0),
    ("minecraft:waxed_weathered_copper_chest", 0x0),
    ("minecraft:waxed_weathered_copper_door", 0x0),
    ("minecraft:waxed_weathered_copper_golem_statue", 0x8),
    ("minecraft:waxed_weathered_copper_grate", 0x0),
    ("minecraft:waxed_weathered_copper_lantern", 0x0),
    ("minecraft:waxed_weathered_copper_trapdoor", 0x0),
    ("minecraft:waxed_weathered_cut_copper", 0x0),
    ("minecraft:waxed_weathered_cut_copper_slab", 0x0),
    ("minecraft:waxed_weathered_cut_copper_stairs", 0x0),
    ("minecraft:waxed_weathered_lightning_rod", 0x0),
    ("minecraft:wayfinder_armor_trim_smithing_template", 0x0),
    ("minecraft:weathered_chiseled_copper", 0x0),
    ("minecraft:weathered_copper", 0x0),
    ("minecraft:weathered_copper_bars", 0x0),
    ("minecraft:weathered_copper_bulb", 0x0),
    ("minecraft:weathered_copper_chain", 0x0),
    ("minecraft:weathered_copper_chest", 0x0),
    ("minecraft:weathered_copper_door", 0x0),
    ("minecraft:weathered_copper_golem_statue", 0x8),
    ("minecraft:weathered_copper_grate", 0x0),
    ("minecraft:weathered_copper_lantern", 0x0),
    ("minecraft:weathered_copper_trapdoor", 0x0),
    ("minecraft:weathered_cut_copper", 0x0),
    ("minecraft:weathered_cut_copper_slab", 0x0),
    ("minecraft:weathered_cut_copper_stairs", 0x0),
    ("minecraft:weathered_lightning_rod", 0x0),
    ("minecraft:weeping_vines", 0x0),
    ("minecraft:wet_sponge", 0x0),
    ("minecraft:wheat", 0x0),
    ("minecraft:wheat_seeds", 0x0),
    ("minecraft:white_banner", 0x2),
    ("minecraft:white_bed", 0x0),
    ("minecraft:white_bundle", 0x40),
    ("minecraft:white_candle", 0x0),
    ("minecraft:white_carpet", 0x100000),
    ("minecraft:white_concrete", 0x0),
    ("minecraft:white_concrete_powder", 0x0),
    ("minecraft:white_dye", 0x10000),
    ("minecraft:white_glazed_terracotta", 0x0),
    ("minecraft:white_harness", 0x100000),
    ("minecraft:white_shulker_box", 0x400),
    ("minecraft:white_stained_glass", 0x0),
    ("minecraft:white_stained_glass_pane", 0x0),
    ("minecraft:white_terracotta", 0x0),
    ("minecraft:white_tulip", 0x0),
    ("minecraft:white_wool", 0x0),
    ("minecraft:wild_armor_trim_smithing_template", 0x0),
    ("minecraft:wildflowers", 0x0),
    ("minecraft:wind_charge", 0x80000000000),
    ("minecraft:witch_spawn_egg", 0x80000),
    ("minecraft:wither_rose", 0x0),
    ("minecraft:wither_skeleton_skull", 0x100000),
    ("minecraft:wither_skeleton_spawn_egg", 0x80000),
    ("minecraft:wither_spawn_egg", 0x80000),
    ("minecraft:wolf_armor", 0x8020100800),
    ("minecraft:wolf_spawn_egg", 0x80000),
    ("minecraft:wooden_axe", 0x248020020800),
    ("minecraft:wooden_hoe", 0x248020020800),
    ("minecraft:wooden_pickaxe", 0x248020020800),
    ("minecraft:wooden_shovel", 0x248020020800),
    ("minecraft:wooden_spear", 0x208164022801),
    ("minecraft:wooden_sword", 0x248020020800),
    ("minecraft:writable_book", 0x400000000000),
    ("minecraft:written_book", 0x40000),
    ("minecraft:yellow_banner", 0x2),
    ("minecraft:yellow_bed", 0x0),
    ("minecraft:yellow_bundle", 0x40),
    ("minecraft:yellow_candle", 0x0),
    ("minecraft:yellow_carpet", 0x100000),
    ("minecraft:yellow_concrete", 0x0),
    ("minecraft:yellow_concrete_powder", 0x0),
    ("minecraft:yellow_dye", 0x10000),
    ("minecraft:yellow_glazed_terracotta", 0x0),
    ("minecraft:yellow_harness", 0x100000),
    ("minecraft:yellow_shulker_box", 0x400),
    ("minecraft:yellow_stained_glass", 0x0),
    ("minecraft:yellow_stained_glass_pane", 0x0),
    ("minecraft:yellow_terracotta", 0x0),
    ("minecraft:yellow_wool", 0x0),
    ("minecraft:zoglin_spawn_egg", 0x80000),
    ("minecraft:zombie_head", 0x100000),
    ("minecraft:zombie_horse_spawn_egg", 0x80000),
    ("minecraft:zombie_nautilus_spawn_egg", 0x80000),
    ("minecraft:zombie_spawn_egg", 0x80000),
    ("minecraft:zombie_villager_spawn_egg", 0x80000),
    ("minecraft:zombified_piglin_spawn_egg", 0x80000),
];

fn mask_of(item: &str) -> Option<u64> {
    ITEM_COMPONENTS
        .binary_search_by(|(name, _)| (*name).cmp(item))
        .ok()
        .map(|i| ITEM_COMPONENTS[i].1)
}

/// `prototype.size()` — how many components an item carries before any patch.
///
/// `None` for an item this build's table does not know, which is a version
/// skew rather than a zero.
pub fn prototype_component_count(item: &str) -> Option<i32> {
    mask_of(item).map(|m| BASE_COMPONENTS.len() as i32 + m.count_ones() as i32)
}

/// `prototype.has(type)` — whether an item's prototype carries a component.
///
/// This is what decides whether a patch entry *changes* the merged count: an
/// addition the prototype already has is an override and adds nothing, and a
/// removal of something the prototype never had takes nothing away.
pub fn prototype_has_component(item: &str, component: &str) -> Option<bool> {
    let mask = mask_of(item)?;
    if BASE_COMPONENTS.contains(&component) {
        return Some(true);
    }
    Some(match EXTRA_COMPONENTS.iter().position(|c| *c == component) {
        Some(i) => mask & (1 << i) != 0,
        None => false,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The table is binary-searched, so an unsorted regeneration would answer
    /// `None` for real items.
    #[test]
    fn the_table_is_sorted_and_complete() {
        assert!(ITEM_COMPONENTS.windows(2).all(|w| w[0].0 < w[1].0));
        assert_eq!(ITEM_COMPONENTS.len(), 1537);
        assert_eq!(BASE_COMPONENTS.len(), 12);
        assert_eq!(EXTRA_COMPONENTS.len(), 47);
        assert!(EXTRA_COMPONENTS.windows(2).all(|w| w[0] < w[1]));
    }

    /// The two numbers a player actually sees, read out of the report by the
    /// generator. A plain block carries only the universal set; a sword adds
    /// 6.
    #[test]
    fn the_prototype_count_is_the_number_the_tooltip_prints() {
        assert_eq!(
            prototype_component_count("minecraft:dirt"),
            Some(12)
        );
        assert_eq!(
            prototype_component_count("minecraft:diamond_sword"),
            Some(18)
        );
    }

    /// Absence is a distinct answer from zero extras — the first suppresses
    /// the tooltip line, the second prints the base count.
    #[test]
    fn an_unknown_item_is_not_a_zero() {
        assert_eq!(prototype_component_count("minecraft:not_an_item"), None);
        assert_eq!(prototype_has_component("minecraft:not_an_item", "minecraft:damage"), None);
    }

    /// The membership half. `damage` is on a sword's prototype and not on
    /// dirt's, which is the difference between a patched `damage` costing the
    /// count nothing and costing it one.
    #[test]
    fn membership_separates_an_override_from_an_addition() {
        assert_eq!(
            prototype_has_component("minecraft:diamond_sword", "minecraft:damage"),
            Some(true)
        );
        assert_eq!(
            prototype_has_component("minecraft:dirt", "minecraft:damage"),
            Some(false)
        );
        // A universal one is on everything, mask or no mask.
        assert_eq!(
            prototype_has_component("minecraft:dirt", "minecraft:rarity"),
            Some(true)
        );
        // A name no prototype carries — `minecraft:custom_name` is only ever
        // a patch — is absent from every item rather than unknown.
        assert_eq!(
            prototype_has_component("minecraft:dirt", "minecraft:custom_name"),
            Some(false)
        );
    }
}
