//! What a loom offers to stamp — GENERATED by
//! `tools/gen_loom_patterns.py`. Do not edit; re-run after a version bump.
//!
//! `LoomMenu.getSelectablePatterns` is two cases: an **empty** pattern slot
//! offers `BannerPatternTags.NO_ITEM_REQUIRED`, and an occupied one offers
//! whatever that item's `PROVIDES_BANNER_PATTERNS` names.
//!
//! # Both are jar data, which M93h got wrong
//!
//! M93h recorded the occupied case as blocked on decoding a HolderSet **value**
//! off the wire and on the `minecraft:banner_pattern` **registry**. Neither is
//! needed: the component lives on the item's **prototype**, which never crosses
//! the wire at all, and its value is a **named** HolderSet — a tag id, whose
//! contents are in the jar. The only real blocker was that the tag expander
//! hardcoded `tags/item`.
//!
//! # The mapping is extracted, not inferred
//!
//! `flower_banner_pattern -> pattern_item/flower` looks like a rule. It is a
//! naming coincidence: `Items.java` names an explicit constant per item and
//! `BannerPatternTags` maps that constant to a tag id. Both sides are read.
//!
//! # The caveat
//!
//! A datapack may retag these, and `update_tags` reaches no consumer — the same
//! trade M19, M42, M91 and M93a make.

/// `BannerPatternTags.NO_ITEM_REQUIRED` — what an EMPTY pattern slot offers,
/// 32 patterns.
pub static NO_ITEM_REQUIRED: &[&str] = &[
    "minecraft:square_bottom_left",
    "minecraft:square_bottom_right",
    "minecraft:square_top_left",
    "minecraft:square_top_right",
    "minecraft:stripe_bottom",
    "minecraft:stripe_top",
    "minecraft:stripe_left",
    "minecraft:stripe_right",
    "minecraft:stripe_center",
    "minecraft:stripe_middle",
    "minecraft:stripe_downright",
    "minecraft:stripe_downleft",
    "minecraft:small_stripes",
    "minecraft:cross",
    "minecraft:straight_cross",
    "minecraft:triangle_bottom",
    "minecraft:triangle_top",
    "minecraft:triangles_bottom",
    "minecraft:triangles_top",
    "minecraft:diagonal_left",
    "minecraft:diagonal_up_right",
    "minecraft:diagonal_up_left",
    "minecraft:diagonal_right",
    "minecraft:circle",
    "minecraft:rhombus",
    "minecraft:half_vertical",
    "minecraft:half_horizontal",
    "minecraft:half_vertical_right",
    "minecraft:half_horizontal_bottom",
    "minecraft:border",
    "minecraft:gradient",
    "minecraft:gradient_up",
];

/// Each pattern item and the patterns it offers, in `Items.java` order.
pub static PATTERN_ITEMS: &[(&str, &[&str])] = &[
    ("minecraft:flower_banner_pattern", &["minecraft:flower"]),
    ("minecraft:creeper_banner_pattern", &["minecraft:creeper"]),
    ("minecraft:skull_banner_pattern", &["minecraft:skull"]),
    ("minecraft:mojang_banner_pattern", &["minecraft:mojang"]),
    ("minecraft:globe_banner_pattern", &["minecraft:globe"]),
    ("minecraft:piglin_banner_pattern", &["minecraft:piglin"]),
    ("minecraft:flow_banner_pattern", &["minecraft:flow"]),
    ("minecraft:guster_banner_pattern", &["minecraft:guster"]),
    ("minecraft:field_masoned_banner_pattern", &["minecraft:bricks"]),
    ("minecraft:bordure_indented_banner_pattern", &["minecraft:curly_border"]),
];

/// `LoomMenu.getSelectablePatterns` — what the loom offers for this pattern
/// slot.
///
/// `None` is an **empty** slot, which offers the no-item-required set. An
/// occupied slot offers only its own item's patterns, and an item with no
/// `PROVIDES_BANNER_PATTERNS` offers **nothing at all** — `ImmutableList.of()`,
/// not the default set. Falling back to `NO_ITEM_REQUIRED` there would let any
/// junk in the pattern slot unlock every pattern.
pub fn selectable_patterns(pattern_slot: Option<&str>) -> &'static [&'static str] {
    match pattern_slot {
        None => NO_ITEM_REQUIRED,
        Some(item) => PATTERN_ITEMS
            .iter()
            .find(|(i, _)| *i == item)
            .map_or(&[][..], |(_, p)| *p),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_empty_slot_offers_the_no_item_required_set() {
        assert_eq!(selectable_patterns(None), NO_ITEM_REQUIRED);
        assert!(NO_ITEM_REQUIRED.len() >= 16, "and it is the big one");
    }

    #[test]
    fn a_pattern_item_offers_only_its_own() {
        let flower = selectable_patterns(Some("minecraft:flower_banner_pattern"));
        assert_eq!(flower.len(), 1);
        // ...and it is NOT a subset of the free set: a pattern that needs an
        // item is exactly one the empty slot does not offer.
        assert!(!NO_ITEM_REQUIRED.contains(&flower[0]), "{:?}", flower[0]);
    }

    #[test]
    fn an_item_with_no_patterns_offers_NOTHING_not_the_default() {
        // `ImmutableList.of()`, not the no-item-required set. Falling back
        // would let any junk in the pattern slot unlock every pattern.
        assert!(selectable_patterns(Some("minecraft:stick")).is_empty());
        assert!(selectable_patterns(Some("minecraft:white_banner")).is_empty());
    }

    #[test]
    fn every_pattern_item_maps_to_a_distinct_pattern() {
        // Two items offering the same pattern would make the loom's index
        // ambiguous in a way vanilla's data never is.
        let mut seen = std::collections::BTreeSet::new();
        for (item, pats) in PATTERN_ITEMS {
            for p in *pats {
                assert!(seen.insert(*p), "{p} offered by two items, one is {item}");
            }
        }
        assert_eq!(PATTERN_ITEMS.len(), 10);
    }
}
