//! The loom's three input sets — GENERATED by `tools/gen_loom_items.py`.
//!
//! Do not edit. Re-run the generator after a version bump; it emits its own
//! tests, so a re-run reproduces this file whole.
//!
//! # `BANNERS` is a tag standing in for a class, and that is checked
//!
//! `LoomMenu`'s banner slot is `getItem() instanceof BannerItem`. The obvious
//! data stand-in — the `minecraft:banner_patterns` prototype component — is
//! **wrong by exactly one item**: the SHIELD carries it too, and a shield is a
//! plausible thing to try to put in a loom. `BannerItem` is constructed in one
//! place only, the 16-colour `ColorCollection`, and `#minecraft:banners` holds
//! exactly those 16 — which the generator asserts rather than assumes.
//!
//! # The other two are CONJUNCTIONS
//!
//! ```java
//! isDyeItem     = is(ItemTags.LOOM_DYES)     && has(DataComponents.DYE)
//! isPatternItem = is(ItemTags.LOOM_PATTERNS) && has(PROVIDES_BANNER_PATTERNS)
//! ```
//!
//! Only the tag half is here. The component half is
//! `item_components_table::prototype_has_component` (M56) plus the stack's own
//! patch, because a patch can **remove** a component the prototype carries.
//! Every vanilla item satisfies both terms together, so a tag-only test looks
//! correct — the same trap as M93e's `max_damage` without `damage`.
//!
//! # The caveat
//!
//! `update_tags` is the authoritative source and Rewo does not plumb it into
//! any consumer, so a datapack that retags these makes the table wrong with no
//! error anywhere. Same trade M19 makes for `ItemTags.SPEARS`, M42 for the
//! enchantment tags, M91 for the smelting sets and M93a for the beacon's.

/// `#minecraft:banners`, standing in for `instanceof BannerItem` — 16 items.
pub static BANNERS: &[&str] = &[
    "minecraft:white_banner",
    "minecraft:orange_banner",
    "minecraft:magenta_banner",
    "minecraft:light_blue_banner",
    "minecraft:yellow_banner",
    "minecraft:lime_banner",
    "minecraft:pink_banner",
    "minecraft:gray_banner",
    "minecraft:light_gray_banner",
    "minecraft:cyan_banner",
    "minecraft:purple_banner",
    "minecraft:blue_banner",
    "minecraft:brown_banner",
    "minecraft:green_banner",
    "minecraft:red_banner",
    "minecraft:black_banner",
];

/// `ItemTags.LOOM_DYES` (which nests `#minecraft:dyes`) — 16 items.
pub static LOOM_DYES: &[&str] = &[
    "minecraft:white_dye",
    "minecraft:orange_dye",
    "minecraft:magenta_dye",
    "minecraft:light_blue_dye",
    "minecraft:yellow_dye",
    "minecraft:lime_dye",
    "minecraft:pink_dye",
    "minecraft:gray_dye",
    "minecraft:light_gray_dye",
    "minecraft:cyan_dye",
    "minecraft:purple_dye",
    "minecraft:blue_dye",
    "minecraft:brown_dye",
    "minecraft:green_dye",
    "minecraft:red_dye",
    "minecraft:black_dye",
];

/// `ItemTags.LOOM_PATTERNS` — 10 items.
pub static LOOM_PATTERNS: &[&str] = &[
    "minecraft:flower_banner_pattern",
    "minecraft:creeper_banner_pattern",
    "minecraft:skull_banner_pattern",
    "minecraft:mojang_banner_pattern",
    "minecraft:globe_banner_pattern",
    "minecraft:piglin_banner_pattern",
    "minecraft:flow_banner_pattern",
    "minecraft:guster_banner_pattern",
    "minecraft:field_masoned_banner_pattern",
    "minecraft:bordure_indented_banner_pattern",
];

/// `getItem() instanceof BannerItem`.
pub fn is_banner(item: &str) -> bool {
    BANNERS.contains(&item)
}

/// The **tag half** of `isDyeItem`. The caller must still check
/// `has(DataComponents.DYE)` — see the module docs.
pub fn in_loom_dyes(item: &str) -> bool {
    LOOM_DYES.contains(&item)
}

/// The **tag half** of `isPatternItem`. The caller must still check
/// `has(PROVIDES_BANNER_PATTERNS)`.
pub fn in_loom_patterns(item: &str) -> bool {
    LOOM_PATTERNS.contains(&item)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_banner_set_is_the_sixteen_colours_and_not_the_shield() {
        assert_eq!(BANNERS.len(), 16);
        assert!(is_banner("minecraft:white_banner"));
        assert!(is_banner("minecraft:black_banner"));
        // THE case this table exists for. A shield carries
        // `minecraft:banner_patterns` on its prototype exactly as a banner
        // does, so deriving the set from that component instead of from the
        // tag would let a shield into the loom's banner slot.
        assert!(!is_banner("minecraft:shield"));
        assert!(!is_banner("minecraft:white_wall_banner"));
    }

    #[test]
    fn the_dye_and_pattern_sets_are_disjoint_from_each_other_and_from_banners() {
        // The loom tests the three in order, and an item in two sets would
        // make that order load-bearing in a way vanilla's data never is.
        for d in LOOM_DYES {
            assert!(!is_banner(d), "{d} is in two sets");
            assert!(!in_loom_patterns(d), "{d} is in two sets");
        }
        for p in LOOM_PATTERNS {
            assert!(!is_banner(p), "{p} is in two sets");
        }
    }

    #[test]
    fn the_tags_hold_what_they_say() {
        assert!(in_loom_dyes("minecraft:red_dye"));
        assert!(!in_loom_dyes("minecraft:stick"));
        assert!(in_loom_patterns("minecraft:flower_banner_pattern"));
        assert!(!in_loom_patterns("minecraft:paper"));
    }
}
