//! GENERATED by `tools/gen_mob_effects.py` — do not edit.
//!
//! Source: the decompiled 26.2 client (`MobEffects.java`), in its
//! static-initialiser order — which IS the `minecraft:mob_effect`
//! registry's protocol-id order, and is pinned against the datagen
//! report by the test at the bottom. Re-run after a version bump; the
//! script fails loud on a registration it cannot read.
//!
//! 40 effects.

/// `MobEffectCategory` — the only thing `Hud.extractEffects` asks of an
/// effect is `isBeneficial()`, i.e. `category == BENEFICIAL`, so a NEUTRAL
/// effect (glowing, bad_omen, trial_omen, raid_omen) shares the HARMFUL row.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MobEffectCategory {
    Beneficial,
    Harmful,
    Neutral,
}

impl MobEffectCategory {
    /// `MobEffect.isBeneficial()` — `this.category == MobEffectCategory.BENEFICIAL`.
    pub fn is_beneficial(self) -> bool {
        self == MobEffectCategory::Beneficial
    }
}

/// One registered `minecraft:mob_effect`, in registry order.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct MobEffectDef {
    /// The registry path, without the `minecraft:` namespace.
    pub name: &'static str,
    pub category: MobEffectCategory,
    /// `MobEffect.getColor()` — the constructor's int, the last tie-break
    /// in `MobEffectInstance.compareTo`.
    pub color: u32,
}

/// Indexed by protocol id.
pub const MOB_EFFECTS: [MobEffectDef; 40] = [
    MobEffectDef { name: "speed", category: MobEffectCategory::Beneficial, color: 3402751 },
    MobEffectDef { name: "slowness", category: MobEffectCategory::Harmful, color: 9154528 },
    MobEffectDef { name: "haste", category: MobEffectCategory::Beneficial, color: 14270531 },
    MobEffectDef { name: "mining_fatigue", category: MobEffectCategory::Harmful, color: 4866583 },
    MobEffectDef { name: "strength", category: MobEffectCategory::Beneficial, color: 16762624 },
    MobEffectDef { name: "instant_health", category: MobEffectCategory::Beneficial, color: 16262179 },
    MobEffectDef { name: "instant_damage", category: MobEffectCategory::Harmful, color: 11101546 },
    MobEffectDef { name: "jump_boost", category: MobEffectCategory::Beneficial, color: 16646020 },
    MobEffectDef { name: "nausea", category: MobEffectCategory::Harmful, color: 5578058 },
    MobEffectDef { name: "regeneration", category: MobEffectCategory::Beneficial, color: 13458603 },
    MobEffectDef { name: "resistance", category: MobEffectCategory::Beneficial, color: 9520880 },
    MobEffectDef { name: "fire_resistance", category: MobEffectCategory::Beneficial, color: 16750848 },
    MobEffectDef { name: "water_breathing", category: MobEffectCategory::Beneficial, color: 10017472 },
    MobEffectDef { name: "invisibility", category: MobEffectCategory::Beneficial, color: 16185078 },
    MobEffectDef { name: "blindness", category: MobEffectCategory::Harmful, color: 2039587 },
    MobEffectDef { name: "night_vision", category: MobEffectCategory::Beneficial, color: 12779366 },
    MobEffectDef { name: "hunger", category: MobEffectCategory::Harmful, color: 5797459 },
    MobEffectDef { name: "weakness", category: MobEffectCategory::Harmful, color: 4738376 },
    MobEffectDef { name: "poison", category: MobEffectCategory::Harmful, color: 8889187 },
    MobEffectDef { name: "wither", category: MobEffectCategory::Harmful, color: 7561558 },
    MobEffectDef { name: "health_boost", category: MobEffectCategory::Beneficial, color: 16284963 },
    MobEffectDef { name: "absorption", category: MobEffectCategory::Beneficial, color: 2445989 },
    MobEffectDef { name: "saturation", category: MobEffectCategory::Beneficial, color: 16262179 },
    MobEffectDef { name: "glowing", category: MobEffectCategory::Neutral, color: 9740385 },
    MobEffectDef { name: "levitation", category: MobEffectCategory::Harmful, color: 13565951 },
    MobEffectDef { name: "luck", category: MobEffectCategory::Beneficial, color: 5882118 },
    MobEffectDef { name: "unluck", category: MobEffectCategory::Harmful, color: 12624973 },
    MobEffectDef { name: "slow_falling", category: MobEffectCategory::Beneficial, color: 15978425 },
    MobEffectDef { name: "conduit_power", category: MobEffectCategory::Beneficial, color: 1950417 },
    MobEffectDef { name: "dolphins_grace", category: MobEffectCategory::Beneficial, color: 8954814 },
    MobEffectDef { name: "bad_omen", category: MobEffectCategory::Neutral, color: 745784 },
    MobEffectDef { name: "hero_of_the_village", category: MobEffectCategory::Beneficial, color: 4521796 },
    MobEffectDef { name: "darkness", category: MobEffectCategory::Harmful, color: 2696993 },
    MobEffectDef { name: "trial_omen", category: MobEffectCategory::Neutral, color: 1484454 },
    MobEffectDef { name: "raid_omen", category: MobEffectCategory::Neutral, color: 14565464 },
    MobEffectDef { name: "wind_charged", category: MobEffectCategory::Harmful, color: 12438015 },
    MobEffectDef { name: "weaving", category: MobEffectCategory::Harmful, color: 7891290 },
    MobEffectDef { name: "oozing", category: MobEffectCategory::Harmful, color: 10092451 },
    MobEffectDef { name: "infested", category: MobEffectCategory::Harmful, color: 9214860 },
    MobEffectDef { name: "breath_of_the_nautilus", category: MobEffectCategory::Beneficial, color: 65518 },
];

/// The table row for a protocol id, or `None` past the end — never a
/// substitute, for the reason `MobEffects::id_of` gives.
pub fn def(id: i32) -> Option<&'static MobEffectDef> {
    usize::try_from(id).ok().and_then(|i| MOB_EFFECTS.get(i))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The declaration order is the registry order — graded against the
    /// report rather than assumed, on any machine that has it.
    #[test]
    fn the_table_order_is_the_registrys_protocol_id_order() {
        let Some(paths) = crate::DataPaths::for_version("26.2") else {
            return;
        };
        let Ok(reg) = crate::mob_effects::MobEffects::load(&paths.registries_json())
        else {
            return;
        };
        assert_eq!(
            reg.len(),
            MOB_EFFECTS.len(),
            "the report and the table disagree on the count"
        );
        for (i, d) in MOB_EFFECTS.iter().enumerate() {
            assert_eq!(
                reg.name(i as i32),
                Some(format!("minecraft:{}", d.name).as_str()),
                "slot {i} is {} in the table",
                d.name
            );
        }
    }

    /// Pinned from MobEffects.java by a direct grep (20/16/4), independently of the generator:
    /// the counts, the four NEUTRALs that share the harmful row, and one
    /// colour per category.
    #[test]
    fn the_categories_and_colours_are_the_decompiles() {
        let count = |c: MobEffectCategory| MOB_EFFECTS.iter().filter(|d| d.category == c).count();
        assert_eq!(count(MobEffectCategory::Beneficial), 20);
        assert_eq!(count(MobEffectCategory::Harmful), 16);
        let neutral: Vec<&str> = MOB_EFFECTS
            .iter()
            .filter(|d| d.category == MobEffectCategory::Neutral)
            .map(|d| d.name)
            .collect();
        assert_eq!(neutral, ["glowing", "bad_omen", "trial_omen", "raid_omen"]);
        // Hud.java tests `isBeneficial()` only, so NEUTRAL is not beneficial.
        assert!(!MobEffectCategory::Neutral.is_beneficial());
        assert_eq!(def(0).map(|d| (d.name, d.color)), Some(("speed", 3402751)));
        assert_eq!(def(18).map(|d| (d.name, d.color)), Some(("poison", 8889187)));
        assert_eq!(def(39).map(|d| d.name), Some("breath_of_the_nautilus"));
        assert_eq!(def(40), None);
        assert_eq!(def(-1), None);
    }
}
