//! What each furnace will accept — GENERATED by `tools/gen_smelting_inputs.py`.
//!
//! Do not edit. Re-run the generator after a version bump.
//!
//! `AbstractFurnaceMenu.canSmelt` is `acceptedInputs.test(stack)`, and each
//! furnace passes its own `RecipePropertySet`: `FURNACE_INPUT` (smelting),
//! `BLAST_FURNACE_INPUT` (blasting), `SMOKER_INPUT` (smoking). These are the
//! ingredient sets of the jar's own recipes, with tags expanded.
//!
//! # The caveat
//!
//! On the client those sets really arrive in `update_recipes`, which Rewo does
//! not decode. **A datapack that adds or removes a smelting recipe makes this
//! wrong with no error anywhere** — a shift-clicked item routes to the player's
//! inventory instead of the ingredient slot, or the reverse. This is the
//! vanilla answer, not the server's, and it is the same trade M19 makes reading
//! `ItemTags.SPEARS` from the jar and M42 reading the enchantment tags.

/// `RecipePropertySet.FURNACE_INPUT` — 156 items.
pub static FURNACE_INPUT: &[&str] = &[
    "minecraft:potato",
    "minecraft:black_terracotta",
    "minecraft:blue_terracotta",
    "minecraft:clay_ball",
    "minecraft:brown_terracotta",
    "minecraft:dark_oak_log",
    "minecraft:dark_oak_wood",
    "minecraft:stripped_dark_oak_log",
    "minecraft:stripped_dark_oak_wood",
    "minecraft:pale_oak_log",
    "minecraft:pale_oak_wood",
    "minecraft:stripped_pale_oak_log",
    "minecraft:stripped_pale_oak_wood",
    "minecraft:oak_log",
    "minecraft:oak_wood",
    "minecraft:stripped_oak_log",
    "minecraft:stripped_oak_wood",
    "minecraft:acacia_log",
    "minecraft:acacia_wood",
    "minecraft:stripped_acacia_log",
    "minecraft:stripped_acacia_wood",
    "minecraft:birch_log",
    "minecraft:birch_wood",
    "minecraft:stripped_birch_log",
    "minecraft:stripped_birch_wood",
    "minecraft:jungle_log",
    "minecraft:jungle_wood",
    "minecraft:stripped_jungle_log",
    "minecraft:stripped_jungle_wood",
    "minecraft:spruce_log",
    "minecraft:spruce_wood",
    "minecraft:stripped_spruce_log",
    "minecraft:stripped_spruce_wood",
    "minecraft:mangrove_log",
    "minecraft:mangrove_wood",
    "minecraft:stripped_mangrove_log",
    "minecraft:stripped_mangrove_wood",
    "minecraft:cherry_log",
    "minecraft:cherry_wood",
    "minecraft:stripped_cherry_log",
    "minecraft:stripped_cherry_wood",
    "minecraft:coal_ore",
    "minecraft:deepslate_coal_ore",
    "minecraft:beef",
    "minecraft:chicken",
    "minecraft:cod",
    "minecraft:mutton",
    "minecraft:porkchop",
    "minecraft:rabbit",
    "minecraft:salmon",
    "minecraft:copper_ore",
    "minecraft:deepslate_copper_ore",
    "minecraft:raw_copper",
    "minecraft:copper_pickaxe",
    "minecraft:copper_shovel",
    "minecraft:copper_axe",
    "minecraft:copper_hoe",
    "minecraft:copper_sword",
    "minecraft:copper_spear",
    "minecraft:copper_helmet",
    "minecraft:copper_chestplate",
    "minecraft:copper_leggings",
    "minecraft:copper_boots",
    "minecraft:copper_horse_armor",
    "minecraft:copper_nautilus_armor",
    "minecraft:deepslate_bricks",
    "minecraft:deepslate_tiles",
    "minecraft:nether_bricks",
    "minecraft:polished_blackstone_bricks",
    "minecraft:stone_bricks",
    "minecraft:cyan_terracotta",
    "minecraft:cobbled_deepslate",
    "minecraft:deepslate_diamond_ore",
    "minecraft:diamond_ore",
    "minecraft:kelp",
    "minecraft:deepslate_emerald_ore",
    "minecraft:emerald_ore",
    "minecraft:sand",
    "minecraft:red_sand",
    "minecraft:deepslate_gold_ore",
    "minecraft:gold_ore",
    "minecraft:nether_gold_ore",
    "minecraft:raw_gold",
    "minecraft:golden_pickaxe",
    "minecraft:golden_shovel",
    "minecraft:golden_axe",
    "minecraft:golden_hoe",
    "minecraft:golden_sword",
    "minecraft:golden_spear",
    "minecraft:golden_helmet",
    "minecraft:golden_chestplate",
    "minecraft:golden_leggings",
    "minecraft:golden_boots",
    "minecraft:golden_horse_armor",
    "minecraft:golden_nautilus_armor",
    "minecraft:gray_terracotta",
    "minecraft:cactus",
    "minecraft:green_terracotta",
    "minecraft:deepslate_iron_ore",
    "minecraft:iron_ore",
    "minecraft:raw_iron",
    "minecraft:iron_pickaxe",
    "minecraft:iron_shovel",
    "minecraft:iron_axe",
    "minecraft:iron_hoe",
    "minecraft:iron_sword",
    "minecraft:iron_spear",
    "minecraft:iron_helmet",
    "minecraft:iron_chestplate",
    "minecraft:iron_leggings",
    "minecraft:iron_boots",
    "minecraft:iron_horse_armor",
    "minecraft:chainmail_helmet",
    "minecraft:chainmail_chestplate",
    "minecraft:chainmail_leggings",
    "minecraft:chainmail_boots",
    "minecraft:iron_nautilus_armor",
    "minecraft:deepslate_lapis_ore",
    "minecraft:lapis_ore",
    "minecraft:jungle_leaves",
    "minecraft:oak_leaves",
    "minecraft:spruce_leaves",
    "minecraft:pale_oak_leaves",
    "minecraft:dark_oak_leaves",
    "minecraft:acacia_leaves",
    "minecraft:birch_leaves",
    "minecraft:azalea_leaves",
    "minecraft:flowering_azalea_leaves",
    "minecraft:mangrove_leaves",
    "minecraft:cherry_leaves",
    "minecraft:light_blue_terracotta",
    "minecraft:light_gray_terracotta",
    "minecraft:sea_pickle",
    "minecraft:lime_terracotta",
    "minecraft:magenta_terracotta",
    "minecraft:netherrack",
    "minecraft:ancient_debris",
    "minecraft:orange_terracotta",
    "minecraft:pink_terracotta",
    "minecraft:chorus_fruit",
    "minecraft:purple_terracotta",
    "minecraft:nether_quartz_ore",
    "minecraft:red_terracotta",
    "minecraft:deepslate_redstone_ore",
    "minecraft:redstone_ore",
    "minecraft:resin_clump",
    "minecraft:basalt",
    "minecraft:quartz_block",
    "minecraft:red_sandstone",
    "minecraft:sandstone",
    "minecraft:stone",
    "minecraft:wet_sponge",
    "minecraft:cobblestone",
    "minecraft:clay",
    "minecraft:white_terracotta",
    "minecraft:yellow_terracotta",
];

/// `RecipePropertySet.BLAST_FURNACE_INPUT` — 62 items.
pub static BLAST_FURNACE_INPUT: &[&str] = &[
    "minecraft:coal_ore",
    "minecraft:deepslate_coal_ore",
    "minecraft:copper_ore",
    "minecraft:deepslate_copper_ore",
    "minecraft:raw_copper",
    "minecraft:copper_pickaxe",
    "minecraft:copper_shovel",
    "minecraft:copper_axe",
    "minecraft:copper_hoe",
    "minecraft:copper_sword",
    "minecraft:copper_spear",
    "minecraft:copper_helmet",
    "minecraft:copper_chestplate",
    "minecraft:copper_leggings",
    "minecraft:copper_boots",
    "minecraft:copper_horse_armor",
    "minecraft:copper_nautilus_armor",
    "minecraft:deepslate_diamond_ore",
    "minecraft:diamond_ore",
    "minecraft:deepslate_emerald_ore",
    "minecraft:emerald_ore",
    "minecraft:deepslate_gold_ore",
    "minecraft:gold_ore",
    "minecraft:nether_gold_ore",
    "minecraft:raw_gold",
    "minecraft:golden_pickaxe",
    "minecraft:golden_shovel",
    "minecraft:golden_axe",
    "minecraft:golden_hoe",
    "minecraft:golden_sword",
    "minecraft:golden_spear",
    "minecraft:golden_helmet",
    "minecraft:golden_chestplate",
    "minecraft:golden_leggings",
    "minecraft:golden_boots",
    "minecraft:golden_horse_armor",
    "minecraft:golden_nautilus_armor",
    "minecraft:deepslate_iron_ore",
    "minecraft:iron_ore",
    "minecraft:raw_iron",
    "minecraft:iron_pickaxe",
    "minecraft:iron_shovel",
    "minecraft:iron_axe",
    "minecraft:iron_hoe",
    "minecraft:iron_sword",
    "minecraft:iron_spear",
    "minecraft:iron_helmet",
    "minecraft:iron_chestplate",
    "minecraft:iron_leggings",
    "minecraft:iron_boots",
    "minecraft:iron_horse_armor",
    "minecraft:iron_nautilus_armor",
    "minecraft:chainmail_helmet",
    "minecraft:chainmail_chestplate",
    "minecraft:chainmail_leggings",
    "minecraft:chainmail_boots",
    "minecraft:deepslate_lapis_ore",
    "minecraft:lapis_ore",
    "minecraft:ancient_debris",
    "minecraft:nether_quartz_ore",
    "minecraft:deepslate_redstone_ore",
    "minecraft:redstone_ore",
];

/// `RecipePropertySet.SMOKER_INPUT` — 9 items.
pub static SMOKER_INPUT: &[&str] = &[
    "minecraft:potato",
    "minecraft:beef",
    "minecraft:chicken",
    "minecraft:cod",
    "minecraft:mutton",
    "minecraft:porkchop",
    "minecraft:rabbit",
    "minecraft:salmon",
    "minecraft:kelp",
];

/// Whether a furnace of the given `minecraft:menu` id accepts `item` as an
/// ingredient, or `None` if that menu is not a furnace.
pub fn accepts(menu_protocol_id: i32, item: &str) -> Option<bool> {
    let set: &[&str] = match menu_protocol_id {
        10 => BLAST_FURNACE_INPUT,
        14 => FURNACE_INPUT,
        22 => SMOKER_INPUT,
        _ => return None,
    };
    Some(set.contains(&item))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The menu ids `accepts` dispatches on, from `minecraft:menu`.
    const BLAST: i32 = 10;
    const FURNACE: i32 = 14;
    const SMOKER: i32 = 22;

    #[test]
    fn each_furnace_accepts_its_own_recipe_type() {
        // A smoker takes food and not ore; a blast furnace the reverse. If the
        // three sets were the same the routing would still "work" and be wrong.
        assert_eq!(accepts(SMOKER, "minecraft:beef"), Some(true));
        assert_eq!(accepts(SMOKER, "minecraft:iron_ore"), Some(false));
        assert_eq!(accepts(BLAST, "minecraft:iron_ore"), Some(true));
        assert_eq!(accepts(BLAST, "minecraft:beef"), Some(false));
        // A furnace takes both, being the superset.
        assert_eq!(accepts(FURNACE, "minecraft:beef"), Some(true));
        assert_eq!(accepts(FURNACE, "minecraft:iron_ore"), Some(true));
    }

    #[test]
    fn a_log_is_smeltable_which_is_what_makes_it_route_as_an_ingredient() {
        // The case that decides the whole furnace quick-move: vanilla checks
        // canSmelt BEFORE isFuel, and a log is both — fuel, and smeltable to
        // charcoal — so it goes to the INGREDIENT slot. Routing on isFuel
        // alone puts it in the fuel slot, which is wrong and looks reasonable.
        assert_eq!(accepts(FURNACE, "minecraft:oak_log"), Some(true));
        assert!(crate::fuel_table::is_fuel("minecraft:oak_log"));
    }

    #[test]
    fn coal_is_fuel_and_not_an_ingredient() {
        assert_eq!(accepts(FURNACE, "minecraft:coal"), Some(false));
        assert!(crate::fuel_table::is_fuel("minecraft:coal"));
    }

    #[test]
    fn a_non_furnace_menu_answers_none_not_false() {
        // `None` is "this menu has no accepted-input set", which the caller
        // must not read as "it accepts nothing".
        assert_eq!(accepts(2, "minecraft:iron_ore"), None); // generic_9x3
        assert_eq!(accepts(8, "minecraft:iron_ore"), None); // anvil
    }
}
