//! What a stonecutter accepts and what it offers — GENERATED by
//! `tools/gen_stonecutter_inputs.py`.
//!
//! Do not edit. Re-run the generator after a version bump. (It emits its own
//! tests, so a re-run reproduces this file whole — `smelting_table.rs` used to
//! carry hand-added tests its generator did not emit, which meant following
//! that same instruction silently deleted them.)
//!
//! `StonecutterMenu.quickMoveStack`'s third branch is
//! `level.recipeAccess().stonecutterRecipes().acceptsInput(stack)`, which is a
//! `SelectableRecipe.SingleInputSet` and **not** a `RecipePropertySet` — that
//! registry has seven keys and the stonecutter is not one of them. Membership
//! still reduces to the union of every stonecutting recipe's ingredient,
//! because `Ingredient.test` is `input.is(this.values)`: item identity, no
//! components.
//!
//! # The list's ORDER is part of the wire contract
//!
//! A click sends an **index**, which the server resolves against
//! `selectByInput` — a *filter*, so it preserves the master list's order. That
//! order is `RecipeManager.prepare`'s `SortedMap<Identifier, Recipe<?>> = new
//! TreeMap<>()`, and `Identifier.compareTo` compares the **path first, then
//! the namespace**, not the combined `namespace:path`. Reproduce it wrongly
//! and every click cuts a different block, with no error anywhere.
//!
//! # The caveat
//!
//! The real set arrives in `update_recipes`, which Rewo does not decode. **A
//! datapack that adds, removes or reorders a stonecutting recipe makes this
//! wrong with no error anywhere.** Same trade M19 makes reading
//! `ItemTags.SPEARS` from the jar, M42 the enchantment tags, and M91 the
//! smelting sets. M93b recorded the LIST as blocked on `update_recipes`; it is
//! not, for the same reason M91's furnace recipes were not.

/// One `SelectableRecipe.SingleInputEntry<StonecutterRecipe>`.
///
/// `count` is carried even though the button never draws it: `extractRecipes`
/// calls `graphics.item`, which renders the model alone and never
/// `itemDecorations`. A tooltip needs the whole stack.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Cut {
    /// The ingredient. All 319 vanilla entries are a plain item id —
    /// no tags, no lists — which the generator asserts rather than assumes.
    pub input: &'static str,
    pub result: &'static str,
    pub count: u8,
}

/// Every stonecutting recipe, in `RecipeMap.values()` order — 319
/// entries. **The index a click sends indexes the filtered view of this
/// list**, so this order is part of the wire contract.
pub static STONECUTTER_RECIPES: &[Cut] = &[
    Cut { input: "minecraft:andesite", result: "minecraft:andesite_slab", count: 2 },
    Cut { input: "minecraft:andesite", result: "minecraft:andesite_stairs", count: 1 },
    Cut { input: "minecraft:andesite", result: "minecraft:andesite_wall", count: 1 },
    Cut { input: "minecraft:blackstone", result: "minecraft:blackstone_slab", count: 2 },
    Cut { input: "minecraft:blackstone", result: "minecraft:blackstone_stairs", count: 1 },
    Cut { input: "minecraft:blackstone", result: "minecraft:blackstone_wall", count: 1 },
    Cut { input: "minecraft:bricks", result: "minecraft:brick_slab", count: 2 },
    Cut { input: "minecraft:bricks", result: "minecraft:brick_stairs", count: 1 },
    Cut { input: "minecraft:bricks", result: "minecraft:brick_wall", count: 1 },
    Cut { input: "minecraft:cinnabar", result: "minecraft:chiseled_cinnabar", count: 1 },
    Cut { input: "minecraft:copper_block", result: "minecraft:chiseled_copper", count: 4 },
    Cut { input: "minecraft:cut_copper", result: "minecraft:chiseled_copper", count: 1 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:chiseled_deepslate", count: 1 },
    Cut { input: "minecraft:deepslate", result: "minecraft:chiseled_deepslate", count: 1 },
    Cut { input: "minecraft:nether_bricks", result: "minecraft:chiseled_nether_bricks", count: 1 },
    Cut { input: "minecraft:blackstone", result: "minecraft:chiseled_polished_blackstone", count: 1 },
    Cut { input: "minecraft:polished_blackstone", result: "minecraft:chiseled_polished_blackstone", count: 1 },
    Cut { input: "minecraft:quartz_block", result: "minecraft:chiseled_quartz_block", count: 1 },
    Cut { input: "minecraft:red_sandstone", result: "minecraft:chiseled_red_sandstone", count: 1 },
    Cut { input: "minecraft:resin_bricks", result: "minecraft:chiseled_resin_bricks", count: 1 },
    Cut { input: "minecraft:sandstone", result: "minecraft:chiseled_sandstone", count: 1 },
    Cut { input: "minecraft:stone_bricks", result: "minecraft:chiseled_stone_bricks", count: 1 },
    Cut { input: "minecraft:stone", result: "minecraft:chiseled_stone_bricks", count: 1 },
    Cut { input: "minecraft:sulfur", result: "minecraft:chiseled_sulfur", count: 1 },
    Cut { input: "minecraft:polished_tuff", result: "minecraft:chiseled_tuff_bricks", count: 1 },
    Cut { input: "minecraft:tuff_bricks", result: "minecraft:chiseled_tuff_bricks", count: 1 },
    Cut { input: "minecraft:tuff", result: "minecraft:chiseled_tuff_bricks", count: 1 },
    Cut { input: "minecraft:tuff", result: "minecraft:chiseled_tuff", count: 1 },
    Cut { input: "minecraft:cinnabar_bricks", result: "minecraft:cinnabar_brick_slab", count: 2 },
    Cut { input: "minecraft:cinnabar", result: "minecraft:cinnabar_brick_slab", count: 2 },
    Cut { input: "minecraft:polished_cinnabar", result: "minecraft:cinnabar_brick_slab", count: 2 },
    Cut { input: "minecraft:cinnabar_bricks", result: "minecraft:cinnabar_brick_stairs", count: 1 },
    Cut { input: "minecraft:cinnabar", result: "minecraft:cinnabar_brick_stairs", count: 1 },
    Cut { input: "minecraft:polished_cinnabar", result: "minecraft:cinnabar_brick_stairs", count: 1 },
    Cut { input: "minecraft:cinnabar_bricks", result: "minecraft:cinnabar_brick_wall", count: 1 },
    Cut { input: "minecraft:cinnabar", result: "minecraft:cinnabar_brick_wall", count: 1 },
    Cut { input: "minecraft:polished_cinnabar", result: "minecraft:cinnabar_brick_wall", count: 1 },
    Cut { input: "minecraft:cinnabar", result: "minecraft:cinnabar_bricks", count: 1 },
    Cut { input: "minecraft:polished_cinnabar", result: "minecraft:cinnabar_bricks", count: 1 },
    Cut { input: "minecraft:cinnabar", result: "minecraft:cinnabar_slab", count: 2 },
    Cut { input: "minecraft:cinnabar", result: "minecraft:cinnabar_stairs", count: 1 },
    Cut { input: "minecraft:cinnabar", result: "minecraft:cinnabar_wall", count: 1 },
    Cut { input: "minecraft:deepslate", result: "minecraft:cobbled_deepslate", count: 1 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:cobbled_deepslate_slab", count: 2 },
    Cut { input: "minecraft:deepslate", result: "minecraft:cobbled_deepslate_slab", count: 2 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:cobbled_deepslate_stairs", count: 1 },
    Cut { input: "minecraft:deepslate", result: "minecraft:cobbled_deepslate_stairs", count: 1 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:cobbled_deepslate_wall", count: 1 },
    Cut { input: "minecraft:deepslate", result: "minecraft:cobbled_deepslate_wall", count: 1 },
    Cut { input: "minecraft:stone", result: "minecraft:cobblestone", count: 1 },
    Cut { input: "minecraft:cobblestone", result: "minecraft:cobblestone_slab", count: 2 },
    Cut { input: "minecraft:stone", result: "minecraft:cobblestone_slab", count: 2 },
    Cut { input: "minecraft:cobblestone", result: "minecraft:cobblestone_stairs", count: 1 },
    Cut { input: "minecraft:stone", result: "minecraft:cobblestone_stairs", count: 1 },
    Cut { input: "minecraft:cobblestone", result: "minecraft:cobblestone_wall", count: 1 },
    Cut { input: "minecraft:stone", result: "minecraft:cobblestone_wall", count: 1 },
    Cut { input: "minecraft:copper_block", result: "minecraft:copper_grate", count: 4 },
    Cut { input: "minecraft:copper_block", result: "minecraft:cut_copper", count: 4 },
    Cut { input: "minecraft:copper_block", result: "minecraft:cut_copper_slab", count: 8 },
    Cut { input: "minecraft:cut_copper", result: "minecraft:cut_copper_slab", count: 2 },
    Cut { input: "minecraft:copper_block", result: "minecraft:cut_copper_stairs", count: 4 },
    Cut { input: "minecraft:cut_copper", result: "minecraft:cut_copper_stairs", count: 1 },
    Cut { input: "minecraft:red_sandstone", result: "minecraft:cut_red_sandstone", count: 1 },
    Cut { input: "minecraft:cut_red_sandstone", result: "minecraft:cut_red_sandstone_slab", count: 2 },
    Cut { input: "minecraft:red_sandstone", result: "minecraft:cut_red_sandstone_slab", count: 2 },
    Cut { input: "minecraft:sandstone", result: "minecraft:cut_sandstone", count: 1 },
    Cut { input: "minecraft:cut_sandstone", result: "minecraft:cut_sandstone_slab", count: 2 },
    Cut { input: "minecraft:sandstone", result: "minecraft:cut_sandstone_slab", count: 2 },
    Cut { input: "minecraft:dark_prismarine", result: "minecraft:dark_prismarine_slab", count: 2 },
    Cut { input: "minecraft:dark_prismarine", result: "minecraft:dark_prismarine_stairs", count: 1 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:deepslate_brick_slab", count: 2 },
    Cut { input: "minecraft:deepslate_bricks", result: "minecraft:deepslate_brick_slab", count: 2 },
    Cut { input: "minecraft:deepslate", result: "minecraft:deepslate_brick_slab", count: 2 },
    Cut { input: "minecraft:polished_deepslate", result: "minecraft:deepslate_brick_slab", count: 2 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:deepslate_brick_stairs", count: 1 },
    Cut { input: "minecraft:deepslate_bricks", result: "minecraft:deepslate_brick_stairs", count: 1 },
    Cut { input: "minecraft:deepslate", result: "minecraft:deepslate_brick_stairs", count: 1 },
    Cut { input: "minecraft:polished_deepslate", result: "minecraft:deepslate_brick_stairs", count: 1 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:deepslate_brick_wall", count: 1 },
    Cut { input: "minecraft:deepslate_bricks", result: "minecraft:deepslate_brick_wall", count: 1 },
    Cut { input: "minecraft:deepslate", result: "minecraft:deepslate_brick_wall", count: 1 },
    Cut { input: "minecraft:polished_deepslate", result: "minecraft:deepslate_brick_wall", count: 1 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:deepslate_bricks", count: 1 },
    Cut { input: "minecraft:deepslate", result: "minecraft:deepslate_bricks", count: 1 },
    Cut { input: "minecraft:polished_deepslate", result: "minecraft:deepslate_bricks", count: 1 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:deepslate_tile_slab", count: 2 },
    Cut { input: "minecraft:deepslate_bricks", result: "minecraft:deepslate_tile_slab", count: 2 },
    Cut { input: "minecraft:deepslate", result: "minecraft:deepslate_tile_slab", count: 2 },
    Cut { input: "minecraft:deepslate_tiles", result: "minecraft:deepslate_tile_slab", count: 2 },
    Cut { input: "minecraft:polished_deepslate", result: "minecraft:deepslate_tile_slab", count: 2 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:deepslate_tile_stairs", count: 1 },
    Cut { input: "minecraft:deepslate_bricks", result: "minecraft:deepslate_tile_stairs", count: 1 },
    Cut { input: "minecraft:deepslate", result: "minecraft:deepslate_tile_stairs", count: 1 },
    Cut { input: "minecraft:deepslate_tiles", result: "minecraft:deepslate_tile_stairs", count: 1 },
    Cut { input: "minecraft:polished_deepslate", result: "minecraft:deepslate_tile_stairs", count: 1 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:deepslate_tile_wall", count: 1 },
    Cut { input: "minecraft:deepslate_bricks", result: "minecraft:deepslate_tile_wall", count: 1 },
    Cut { input: "minecraft:deepslate", result: "minecraft:deepslate_tile_wall", count: 1 },
    Cut { input: "minecraft:deepslate_tiles", result: "minecraft:deepslate_tile_wall", count: 1 },
    Cut { input: "minecraft:polished_deepslate", result: "minecraft:deepslate_tile_wall", count: 1 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:deepslate_tiles", count: 1 },
    Cut { input: "minecraft:deepslate_bricks", result: "minecraft:deepslate_tiles", count: 1 },
    Cut { input: "minecraft:deepslate", result: "minecraft:deepslate_tiles", count: 1 },
    Cut { input: "minecraft:polished_deepslate", result: "minecraft:deepslate_tiles", count: 1 },
    Cut { input: "minecraft:diorite", result: "minecraft:diorite_slab", count: 2 },
    Cut { input: "minecraft:diorite", result: "minecraft:diorite_stairs", count: 1 },
    Cut { input: "minecraft:diorite", result: "minecraft:diorite_wall", count: 1 },
    Cut { input: "minecraft:end_stone_bricks", result: "minecraft:end_stone_brick_slab", count: 2 },
    Cut { input: "minecraft:end_stone", result: "minecraft:end_stone_brick_slab", count: 2 },
    Cut { input: "minecraft:end_stone_bricks", result: "minecraft:end_stone_brick_stairs", count: 1 },
    Cut { input: "minecraft:end_stone", result: "minecraft:end_stone_brick_stairs", count: 1 },
    Cut { input: "minecraft:end_stone_bricks", result: "minecraft:end_stone_brick_wall", count: 1 },
    Cut { input: "minecraft:end_stone", result: "minecraft:end_stone_brick_wall", count: 1 },
    Cut { input: "minecraft:end_stone", result: "minecraft:end_stone_bricks", count: 1 },
    Cut { input: "minecraft:exposed_copper", result: "minecraft:exposed_chiseled_copper", count: 4 },
    Cut { input: "minecraft:exposed_cut_copper", result: "minecraft:exposed_chiseled_copper", count: 1 },
    Cut { input: "minecraft:exposed_copper", result: "minecraft:exposed_copper_grate", count: 4 },
    Cut { input: "minecraft:exposed_copper", result: "minecraft:exposed_cut_copper", count: 4 },
    Cut { input: "minecraft:exposed_copper", result: "minecraft:exposed_cut_copper_slab", count: 8 },
    Cut { input: "minecraft:exposed_cut_copper", result: "minecraft:exposed_cut_copper_slab", count: 2 },
    Cut { input: "minecraft:exposed_copper", result: "minecraft:exposed_cut_copper_stairs", count: 4 },
    Cut { input: "minecraft:exposed_cut_copper", result: "minecraft:exposed_cut_copper_stairs", count: 1 },
    Cut { input: "minecraft:granite", result: "minecraft:granite_slab", count: 2 },
    Cut { input: "minecraft:granite", result: "minecraft:granite_stairs", count: 1 },
    Cut { input: "minecraft:granite", result: "minecraft:granite_wall", count: 1 },
    Cut { input: "minecraft:mossy_cobblestone", result: "minecraft:mossy_cobblestone_slab", count: 2 },
    Cut { input: "minecraft:mossy_cobblestone", result: "minecraft:mossy_cobblestone_stairs", count: 1 },
    Cut { input: "minecraft:mossy_cobblestone", result: "minecraft:mossy_cobblestone_wall", count: 1 },
    Cut { input: "minecraft:mossy_stone_bricks", result: "minecraft:mossy_stone_brick_slab", count: 2 },
    Cut { input: "minecraft:mossy_stone_bricks", result: "minecraft:mossy_stone_brick_stairs", count: 1 },
    Cut { input: "minecraft:mossy_stone_bricks", result: "minecraft:mossy_stone_brick_wall", count: 1 },
    Cut { input: "minecraft:mud_bricks", result: "minecraft:mud_brick_slab", count: 2 },
    Cut { input: "minecraft:mud_bricks", result: "minecraft:mud_brick_stairs", count: 1 },
    Cut { input: "minecraft:mud_bricks", result: "minecraft:mud_brick_wall", count: 1 },
    Cut { input: "minecraft:nether_bricks", result: "minecraft:nether_brick_slab", count: 2 },
    Cut { input: "minecraft:nether_bricks", result: "minecraft:nether_brick_stairs", count: 1 },
    Cut { input: "minecraft:nether_bricks", result: "minecraft:nether_brick_wall", count: 1 },
    Cut { input: "minecraft:oxidized_copper", result: "minecraft:oxidized_chiseled_copper", count: 4 },
    Cut { input: "minecraft:oxidized_cut_copper", result: "minecraft:oxidized_chiseled_copper", count: 1 },
    Cut { input: "minecraft:oxidized_copper", result: "minecraft:oxidized_copper_grate", count: 4 },
    Cut { input: "minecraft:oxidized_copper", result: "minecraft:oxidized_cut_copper", count: 4 },
    Cut { input: "minecraft:oxidized_copper", result: "minecraft:oxidized_cut_copper_slab", count: 8 },
    Cut { input: "minecraft:oxidized_cut_copper", result: "minecraft:oxidized_cut_copper_slab", count: 2 },
    Cut { input: "minecraft:oxidized_copper", result: "minecraft:oxidized_cut_copper_stairs", count: 4 },
    Cut { input: "minecraft:oxidized_cut_copper", result: "minecraft:oxidized_cut_copper_stairs", count: 1 },
    Cut { input: "minecraft:andesite", result: "minecraft:polished_andesite", count: 1 },
    Cut { input: "minecraft:andesite", result: "minecraft:polished_andesite_slab", count: 2 },
    Cut { input: "minecraft:polished_andesite", result: "minecraft:polished_andesite_slab", count: 2 },
    Cut { input: "minecraft:andesite", result: "minecraft:polished_andesite_stairs", count: 1 },
    Cut { input: "minecraft:polished_andesite", result: "minecraft:polished_andesite_stairs", count: 1 },
    Cut { input: "minecraft:basalt", result: "minecraft:polished_basalt", count: 1 },
    Cut { input: "minecraft:blackstone", result: "minecraft:polished_blackstone_brick_slab", count: 2 },
    Cut { input: "minecraft:polished_blackstone_bricks", result: "minecraft:polished_blackstone_brick_slab", count: 2 },
    Cut { input: "minecraft:polished_blackstone", result: "minecraft:polished_blackstone_brick_slab", count: 2 },
    Cut { input: "minecraft:blackstone", result: "minecraft:polished_blackstone_brick_stairs", count: 1 },
    Cut { input: "minecraft:polished_blackstone_bricks", result: "minecraft:polished_blackstone_brick_stairs", count: 1 },
    Cut { input: "minecraft:polished_blackstone", result: "minecraft:polished_blackstone_brick_stairs", count: 1 },
    Cut { input: "minecraft:blackstone", result: "minecraft:polished_blackstone_brick_wall", count: 1 },
    Cut { input: "minecraft:polished_blackstone_bricks", result: "minecraft:polished_blackstone_brick_wall", count: 1 },
    Cut { input: "minecraft:polished_blackstone", result: "minecraft:polished_blackstone_brick_wall", count: 1 },
    Cut { input: "minecraft:blackstone", result: "minecraft:polished_blackstone_bricks", count: 1 },
    Cut { input: "minecraft:polished_blackstone", result: "minecraft:polished_blackstone_bricks", count: 1 },
    Cut { input: "minecraft:blackstone", result: "minecraft:polished_blackstone", count: 1 },
    Cut { input: "minecraft:blackstone", result: "minecraft:polished_blackstone_slab", count: 2 },
    Cut { input: "minecraft:polished_blackstone", result: "minecraft:polished_blackstone_slab", count: 2 },
    Cut { input: "minecraft:blackstone", result: "minecraft:polished_blackstone_stairs", count: 1 },
    Cut { input: "minecraft:polished_blackstone", result: "minecraft:polished_blackstone_stairs", count: 1 },
    Cut { input: "minecraft:blackstone", result: "minecraft:polished_blackstone_wall", count: 1 },
    Cut { input: "minecraft:polished_blackstone", result: "minecraft:polished_blackstone_wall", count: 1 },
    Cut { input: "minecraft:cinnabar", result: "minecraft:polished_cinnabar", count: 1 },
    Cut { input: "minecraft:cinnabar", result: "minecraft:polished_cinnabar_slab", count: 2 },
    Cut { input: "minecraft:polished_cinnabar", result: "minecraft:polished_cinnabar_slab", count: 2 },
    Cut { input: "minecraft:cinnabar", result: "minecraft:polished_cinnabar_stairs", count: 1 },
    Cut { input: "minecraft:polished_cinnabar", result: "minecraft:polished_cinnabar_stairs", count: 1 },
    Cut { input: "minecraft:cinnabar", result: "minecraft:polished_cinnabar_wall", count: 1 },
    Cut { input: "minecraft:polished_cinnabar", result: "minecraft:polished_cinnabar_wall", count: 1 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:polished_deepslate", count: 1 },
    Cut { input: "minecraft:deepslate", result: "minecraft:polished_deepslate", count: 1 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:polished_deepslate_slab", count: 2 },
    Cut { input: "minecraft:deepslate", result: "minecraft:polished_deepslate_slab", count: 2 },
    Cut { input: "minecraft:polished_deepslate", result: "minecraft:polished_deepslate_slab", count: 2 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:polished_deepslate_stairs", count: 1 },
    Cut { input: "minecraft:deepslate", result: "minecraft:polished_deepslate_stairs", count: 1 },
    Cut { input: "minecraft:polished_deepslate", result: "minecraft:polished_deepslate_stairs", count: 1 },
    Cut { input: "minecraft:cobbled_deepslate", result: "minecraft:polished_deepslate_wall", count: 1 },
    Cut { input: "minecraft:deepslate", result: "minecraft:polished_deepslate_wall", count: 1 },
    Cut { input: "minecraft:polished_deepslate", result: "minecraft:polished_deepslate_wall", count: 1 },
    Cut { input: "minecraft:diorite", result: "minecraft:polished_diorite", count: 1 },
    Cut { input: "minecraft:diorite", result: "minecraft:polished_diorite_slab", count: 2 },
    Cut { input: "minecraft:polished_diorite", result: "minecraft:polished_diorite_slab", count: 2 },
    Cut { input: "minecraft:diorite", result: "minecraft:polished_diorite_stairs", count: 1 },
    Cut { input: "minecraft:polished_diorite", result: "minecraft:polished_diorite_stairs", count: 1 },
    Cut { input: "minecraft:granite", result: "minecraft:polished_granite", count: 1 },
    Cut { input: "minecraft:granite", result: "minecraft:polished_granite_slab", count: 2 },
    Cut { input: "minecraft:polished_granite", result: "minecraft:polished_granite_slab", count: 2 },
    Cut { input: "minecraft:granite", result: "minecraft:polished_granite_stairs", count: 1 },
    Cut { input: "minecraft:polished_granite", result: "minecraft:polished_granite_stairs", count: 1 },
    Cut { input: "minecraft:sulfur", result: "minecraft:polished_sulfur", count: 1 },
    Cut { input: "minecraft:polished_sulfur", result: "minecraft:polished_sulfur_slab", count: 2 },
    Cut { input: "minecraft:sulfur", result: "minecraft:polished_sulfur_slab", count: 2 },
    Cut { input: "minecraft:polished_sulfur", result: "minecraft:polished_sulfur_stairs", count: 1 },
    Cut { input: "minecraft:sulfur", result: "minecraft:polished_sulfur_stairs", count: 1 },
    Cut { input: "minecraft:polished_sulfur", result: "minecraft:polished_sulfur_wall", count: 1 },
    Cut { input: "minecraft:sulfur", result: "minecraft:polished_sulfur_wall", count: 1 },
    Cut { input: "minecraft:tuff", result: "minecraft:polished_tuff", count: 1 },
    Cut { input: "minecraft:polished_tuff", result: "minecraft:polished_tuff_slab", count: 2 },
    Cut { input: "minecraft:tuff", result: "minecraft:polished_tuff_slab", count: 2 },
    Cut { input: "minecraft:polished_tuff", result: "minecraft:polished_tuff_stairs", count: 1 },
    Cut { input: "minecraft:tuff", result: "minecraft:polished_tuff_stairs", count: 1 },
    Cut { input: "minecraft:polished_tuff", result: "minecraft:polished_tuff_wall", count: 1 },
    Cut { input: "minecraft:tuff", result: "minecraft:polished_tuff_wall", count: 1 },
    Cut { input: "minecraft:prismarine_bricks", result: "minecraft:prismarine_brick_slab", count: 2 },
    Cut { input: "minecraft:prismarine_bricks", result: "minecraft:prismarine_brick_stairs", count: 1 },
    Cut { input: "minecraft:prismarine", result: "minecraft:prismarine_slab", count: 2 },
    Cut { input: "minecraft:prismarine", result: "minecraft:prismarine_stairs", count: 1 },
    Cut { input: "minecraft:prismarine", result: "minecraft:prismarine_wall", count: 1 },
    Cut { input: "minecraft:purpur_block", result: "minecraft:purpur_pillar", count: 1 },
    Cut { input: "minecraft:purpur_block", result: "minecraft:purpur_slab", count: 2 },
    Cut { input: "minecraft:purpur_block", result: "minecraft:purpur_stairs", count: 1 },
    Cut { input: "minecraft:quartz_block", result: "minecraft:quartz_bricks", count: 1 },
    Cut { input: "minecraft:quartz_block", result: "minecraft:quartz_pillar", count: 1 },
    Cut { input: "minecraft:quartz_block", result: "minecraft:quartz_slab", count: 2 },
    Cut { input: "minecraft:quartz_block", result: "minecraft:quartz_stairs", count: 1 },
    Cut { input: "minecraft:red_nether_bricks", result: "minecraft:red_nether_brick_slab", count: 2 },
    Cut { input: "minecraft:red_nether_bricks", result: "minecraft:red_nether_brick_stairs", count: 1 },
    Cut { input: "minecraft:red_nether_bricks", result: "minecraft:red_nether_brick_wall", count: 1 },
    Cut { input: "minecraft:red_sandstone", result: "minecraft:red_sandstone_slab", count: 2 },
    Cut { input: "minecraft:red_sandstone", result: "minecraft:red_sandstone_stairs", count: 1 },
    Cut { input: "minecraft:red_sandstone", result: "minecraft:red_sandstone_wall", count: 1 },
    Cut { input: "minecraft:resin_bricks", result: "minecraft:resin_brick_slab", count: 2 },
    Cut { input: "minecraft:resin_bricks", result: "minecraft:resin_brick_stairs", count: 1 },
    Cut { input: "minecraft:resin_bricks", result: "minecraft:resin_brick_wall", count: 1 },
    Cut { input: "minecraft:sandstone", result: "minecraft:sandstone_slab", count: 2 },
    Cut { input: "minecraft:sandstone", result: "minecraft:sandstone_stairs", count: 1 },
    Cut { input: "minecraft:sandstone", result: "minecraft:sandstone_wall", count: 1 },
    Cut { input: "minecraft:smooth_quartz", result: "minecraft:smooth_quartz_slab", count: 2 },
    Cut { input: "minecraft:smooth_quartz", result: "minecraft:smooth_quartz_stairs", count: 1 },
    Cut { input: "minecraft:smooth_red_sandstone", result: "minecraft:smooth_red_sandstone_slab", count: 2 },
    Cut { input: "minecraft:smooth_red_sandstone", result: "minecraft:smooth_red_sandstone_stairs", count: 1 },
    Cut { input: "minecraft:smooth_sandstone", result: "minecraft:smooth_sandstone_slab", count: 2 },
    Cut { input: "minecraft:smooth_sandstone", result: "minecraft:smooth_sandstone_stairs", count: 1 },
    Cut { input: "minecraft:smooth_stone", result: "minecraft:smooth_stone_slab", count: 2 },
    Cut { input: "minecraft:stone_bricks", result: "minecraft:stone_brick_slab", count: 2 },
    Cut { input: "minecraft:stone", result: "minecraft:stone_brick_slab", count: 2 },
    Cut { input: "minecraft:stone_bricks", result: "minecraft:stone_brick_stairs", count: 1 },
    Cut { input: "minecraft:stone", result: "minecraft:stone_brick_stairs", count: 1 },
    Cut { input: "minecraft:stone_bricks", result: "minecraft:stone_brick_wall", count: 1 },
    Cut { input: "minecraft:stone", result: "minecraft:stone_brick_wall", count: 1 },
    Cut { input: "minecraft:stone", result: "minecraft:stone_bricks", count: 1 },
    Cut { input: "minecraft:stone", result: "minecraft:stone_slab", count: 2 },
    Cut { input: "minecraft:stone", result: "minecraft:stone_stairs", count: 1 },
    Cut { input: "minecraft:polished_sulfur", result: "minecraft:sulfur_brick_slab", count: 2 },
    Cut { input: "minecraft:sulfur_bricks", result: "minecraft:sulfur_brick_slab", count: 2 },
    Cut { input: "minecraft:sulfur", result: "minecraft:sulfur_brick_slab", count: 2 },
    Cut { input: "minecraft:polished_sulfur", result: "minecraft:sulfur_brick_stairs", count: 1 },
    Cut { input: "minecraft:sulfur_bricks", result: "minecraft:sulfur_brick_stairs", count: 1 },
    Cut { input: "minecraft:sulfur", result: "minecraft:sulfur_brick_stairs", count: 1 },
    Cut { input: "minecraft:polished_sulfur", result: "minecraft:sulfur_brick_wall", count: 1 },
    Cut { input: "minecraft:sulfur_bricks", result: "minecraft:sulfur_brick_wall", count: 1 },
    Cut { input: "minecraft:sulfur", result: "minecraft:sulfur_brick_wall", count: 1 },
    Cut { input: "minecraft:polished_sulfur", result: "minecraft:sulfur_bricks", count: 1 },
    Cut { input: "minecraft:sulfur", result: "minecraft:sulfur_bricks", count: 1 },
    Cut { input: "minecraft:sulfur", result: "minecraft:sulfur_slab", count: 2 },
    Cut { input: "minecraft:sulfur", result: "minecraft:sulfur_stairs", count: 1 },
    Cut { input: "minecraft:sulfur", result: "minecraft:sulfur_wall", count: 1 },
    Cut { input: "minecraft:polished_tuff", result: "minecraft:tuff_brick_slab", count: 2 },
    Cut { input: "minecraft:tuff_bricks", result: "minecraft:tuff_brick_slab", count: 2 },
    Cut { input: "minecraft:tuff", result: "minecraft:tuff_brick_slab", count: 2 },
    Cut { input: "minecraft:polished_tuff", result: "minecraft:tuff_brick_stairs", count: 1 },
    Cut { input: "minecraft:tuff_bricks", result: "minecraft:tuff_brick_stairs", count: 1 },
    Cut { input: "minecraft:tuff", result: "minecraft:tuff_brick_stairs", count: 1 },
    Cut { input: "minecraft:polished_tuff", result: "minecraft:tuff_brick_wall", count: 1 },
    Cut { input: "minecraft:tuff_bricks", result: "minecraft:tuff_brick_wall", count: 1 },
    Cut { input: "minecraft:tuff", result: "minecraft:tuff_brick_wall", count: 1 },
    Cut { input: "minecraft:polished_tuff", result: "minecraft:tuff_bricks", count: 1 },
    Cut { input: "minecraft:tuff", result: "minecraft:tuff_bricks", count: 1 },
    Cut { input: "minecraft:tuff", result: "minecraft:tuff_slab", count: 2 },
    Cut { input: "minecraft:tuff", result: "minecraft:tuff_stairs", count: 1 },
    Cut { input: "minecraft:tuff", result: "minecraft:tuff_wall", count: 1 },
    Cut { input: "minecraft:waxed_copper_block", result: "minecraft:waxed_chiseled_copper", count: 4 },
    Cut { input: "minecraft:waxed_cut_copper", result: "minecraft:waxed_chiseled_copper", count: 1 },
    Cut { input: "minecraft:waxed_copper_block", result: "minecraft:waxed_copper_grate", count: 4 },
    Cut { input: "minecraft:waxed_copper_block", result: "minecraft:waxed_cut_copper", count: 4 },
    Cut { input: "minecraft:waxed_copper_block", result: "minecraft:waxed_cut_copper_slab", count: 8 },
    Cut { input: "minecraft:waxed_cut_copper", result: "minecraft:waxed_cut_copper_slab", count: 2 },
    Cut { input: "minecraft:waxed_copper_block", result: "minecraft:waxed_cut_copper_stairs", count: 4 },
    Cut { input: "minecraft:waxed_cut_copper", result: "minecraft:waxed_cut_copper_stairs", count: 1 },
    Cut { input: "minecraft:waxed_exposed_copper", result: "minecraft:waxed_exposed_chiseled_copper", count: 4 },
    Cut { input: "minecraft:waxed_exposed_cut_copper", result: "minecraft:waxed_exposed_chiseled_copper", count: 1 },
    Cut { input: "minecraft:waxed_exposed_copper", result: "minecraft:waxed_exposed_copper_grate", count: 4 },
    Cut { input: "minecraft:waxed_exposed_copper", result: "minecraft:waxed_exposed_cut_copper", count: 4 },
    Cut { input: "minecraft:waxed_exposed_copper", result: "minecraft:waxed_exposed_cut_copper_slab", count: 8 },
    Cut { input: "minecraft:waxed_exposed_cut_copper", result: "minecraft:waxed_exposed_cut_copper_slab", count: 2 },
    Cut { input: "minecraft:waxed_exposed_copper", result: "minecraft:waxed_exposed_cut_copper_stairs", count: 4 },
    Cut { input: "minecraft:waxed_exposed_cut_copper", result: "minecraft:waxed_exposed_cut_copper_stairs", count: 1 },
    Cut { input: "minecraft:waxed_oxidized_copper", result: "minecraft:waxed_oxidized_chiseled_copper", count: 4 },
    Cut { input: "minecraft:waxed_oxidized_cut_copper", result: "minecraft:waxed_oxidized_chiseled_copper", count: 1 },
    Cut { input: "minecraft:waxed_oxidized_copper", result: "minecraft:waxed_oxidized_copper_grate", count: 4 },
    Cut { input: "minecraft:waxed_oxidized_copper", result: "minecraft:waxed_oxidized_cut_copper", count: 4 },
    Cut { input: "minecraft:waxed_oxidized_copper", result: "minecraft:waxed_oxidized_cut_copper_slab", count: 8 },
    Cut { input: "minecraft:waxed_oxidized_cut_copper", result: "minecraft:waxed_oxidized_cut_copper_slab", count: 2 },
    Cut { input: "minecraft:waxed_oxidized_copper", result: "minecraft:waxed_oxidized_cut_copper_stairs", count: 4 },
    Cut { input: "minecraft:waxed_oxidized_cut_copper", result: "minecraft:waxed_oxidized_cut_copper_stairs", count: 1 },
    Cut { input: "minecraft:waxed_weathered_copper", result: "minecraft:waxed_weathered_chiseled_copper", count: 4 },
    Cut { input: "minecraft:waxed_weathered_cut_copper", result: "minecraft:waxed_weathered_chiseled_copper", count: 1 },
    Cut { input: "minecraft:waxed_weathered_copper", result: "minecraft:waxed_weathered_copper_grate", count: 4 },
    Cut { input: "minecraft:waxed_weathered_copper", result: "minecraft:waxed_weathered_cut_copper", count: 4 },
    Cut { input: "minecraft:waxed_weathered_copper", result: "minecraft:waxed_weathered_cut_copper_slab", count: 8 },
    Cut { input: "minecraft:waxed_weathered_cut_copper", result: "minecraft:waxed_weathered_cut_copper_slab", count: 2 },
    Cut { input: "minecraft:waxed_weathered_copper", result: "minecraft:waxed_weathered_cut_copper_stairs", count: 4 },
    Cut { input: "minecraft:waxed_weathered_cut_copper", result: "minecraft:waxed_weathered_cut_copper_stairs", count: 1 },
    Cut { input: "minecraft:weathered_copper", result: "minecraft:weathered_chiseled_copper", count: 4 },
    Cut { input: "minecraft:weathered_cut_copper", result: "minecraft:weathered_chiseled_copper", count: 1 },
    Cut { input: "minecraft:weathered_copper", result: "minecraft:weathered_copper_grate", count: 4 },
    Cut { input: "minecraft:weathered_copper", result: "minecraft:weathered_cut_copper", count: 4 },
    Cut { input: "minecraft:weathered_copper", result: "minecraft:weathered_cut_copper_slab", count: 8 },
    Cut { input: "minecraft:weathered_cut_copper", result: "minecraft:weathered_cut_copper_slab", count: 2 },
    Cut { input: "minecraft:weathered_copper", result: "minecraft:weathered_cut_copper_stairs", count: 4 },
    Cut { input: "minecraft:weathered_cut_copper", result: "minecraft:weathered_cut_copper_stairs", count: 1 },
];

/// Every item a stonecutter accepts in its input slot — 65 items.
///
/// Derived from [`STONECUTTER_RECIPES`] by the same generator walk, so the two
/// cannot drift; `acceptsInput` is `entries.stream().anyMatch(…)` over exactly
/// that list.
pub static STONECUTTER_INPUT: &[&str] = &[
    "minecraft:andesite",
    "minecraft:blackstone",
    "minecraft:bricks",
    "minecraft:cinnabar",
    "minecraft:copper_block",
    "minecraft:cut_copper",
    "minecraft:cobbled_deepslate",
    "minecraft:deepslate",
    "minecraft:nether_bricks",
    "minecraft:polished_blackstone",
    "minecraft:quartz_block",
    "minecraft:red_sandstone",
    "minecraft:resin_bricks",
    "minecraft:sandstone",
    "minecraft:stone_bricks",
    "minecraft:stone",
    "minecraft:sulfur",
    "minecraft:polished_tuff",
    "minecraft:tuff_bricks",
    "minecraft:tuff",
    "minecraft:cinnabar_bricks",
    "minecraft:polished_cinnabar",
    "minecraft:cobblestone",
    "minecraft:cut_red_sandstone",
    "minecraft:cut_sandstone",
    "minecraft:dark_prismarine",
    "minecraft:deepslate_bricks",
    "minecraft:polished_deepslate",
    "minecraft:deepslate_tiles",
    "minecraft:diorite",
    "minecraft:end_stone_bricks",
    "minecraft:end_stone",
    "minecraft:exposed_copper",
    "minecraft:exposed_cut_copper",
    "minecraft:granite",
    "minecraft:mossy_cobblestone",
    "minecraft:mossy_stone_bricks",
    "minecraft:mud_bricks",
    "minecraft:oxidized_copper",
    "minecraft:oxidized_cut_copper",
    "minecraft:polished_andesite",
    "minecraft:basalt",
    "minecraft:polished_blackstone_bricks",
    "minecraft:polished_diorite",
    "minecraft:polished_granite",
    "minecraft:polished_sulfur",
    "minecraft:prismarine_bricks",
    "minecraft:prismarine",
    "minecraft:purpur_block",
    "minecraft:red_nether_bricks",
    "minecraft:smooth_quartz",
    "minecraft:smooth_red_sandstone",
    "minecraft:smooth_sandstone",
    "minecraft:smooth_stone",
    "minecraft:sulfur_bricks",
    "minecraft:waxed_copper_block",
    "minecraft:waxed_cut_copper",
    "minecraft:waxed_exposed_copper",
    "minecraft:waxed_exposed_cut_copper",
    "minecraft:waxed_oxidized_copper",
    "minecraft:waxed_oxidized_cut_copper",
    "minecraft:waxed_weathered_copper",
    "minecraft:waxed_weathered_cut_copper",
    "minecraft:weathered_copper",
    "minecraft:weathered_cut_copper",
];

/// `SelectableRecipe.SingleInputSet.selectByInput` — the entries whose
/// ingredient matches, **in master-list order**.
///
/// ```java
/// return new SingleInputSet<>(this.entries.stream().filter(e -> e.input.test(input)).toList());
/// ```
///
/// `Ingredient.test` is `input.is(this.values)`: item identity, no components.
pub fn select_by_input(item: &str) -> Vec<&'static Cut> {
    STONECUTTER_RECIPES.iter().filter(|c| c.input == item).collect()
}

/// `SingleInputSet.acceptsInput` — whether a stonecutter routes this item to
/// its input slot on a shift-click.
///
/// Note this is **not** the input slot's `mayPlace`: that slot is a bare
/// `Slot` with no override, so an ordinary click can put anything in it. The
/// predicate exists only in `quickMoveStack`.
pub fn accepts_input(item: &str) -> bool {
    STONECUTTER_INPUT.contains(&item)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_obvious_stonecuttable_blocks_are_accepted() {
        assert!(accepts_input("minecraft:stone"));
        assert!(accepts_input("minecraft:andesite"));
        assert!(accepts_input("minecraft:copper_block"));
    }

    #[test]
    fn an_item_with_no_stonecutting_recipe_is_refused() {
        // The negative is what the routing actually turns on: a false here is
        // what sends the stack to the hotbar instead of the input slot.
        assert!(!accepts_input("minecraft:stick"));
        assert!(!accepts_input("minecraft:beef"));
        // A stonecutter RESULT is not itself an input — quartz stairs are cut
        // from the block, and cutting the stairs again is not a recipe.
        assert!(!accepts_input("minecraft:andesite_wall"));
    }

    #[test]
    fn the_stonecutter_set_is_not_the_furnace_set() {
        // If the two tables were wired to the same data the routing would
        // still "work" and be wrong in both menus. The pair must be genuinely
        // disjoint, which `stone` is NOT — it cuts into slabs and smelts into
        // smooth stone, so the first draft of this test asserted stone was
        // unsmeltable and failed against correct code.
        assert!(accepts_input("minecraft:andesite"));
        assert_eq!(crate::smelting_table::accepts(14, "minecraft:andesite"), Some(false));
        assert!(!accepts_input("minecraft:beef"));
        assert_eq!(crate::smelting_table::accepts(14, "minecraft:beef"), Some(true));
    }

    #[test]
    fn an_item_that_is_both_is_routed_by_the_MENU_not_by_the_item() {
        // M91's log — fuel AND smeltable — one menu over. Cobblestone cuts
        // into stairs and smelts into stone, so a single "what is this item
        // for" flag could not route it: the furnace sends it to the ingredient
        // slot and the stonecutter to the input slot, and both are right.
        assert!(accepts_input("minecraft:cobblestone"));
        assert_eq!(crate::smelting_table::accepts(14, "minecraft:cobblestone"), Some(true));
    }

    #[test]
    fn the_two_tables_cannot_disagree() {
        // Both come from one generator walk, and this is the guard M93r's
        // sweep says to write anyway: a derived table with nothing asserting
        // the derivation is one edit away from silently diverging.
        let mut derived: Vec<&str> = Vec::new();
        for c in STONECUTTER_RECIPES {
            if !derived.contains(&c.input) {
                derived.push(c.input);
            }
        }
        assert_eq!(derived, STONECUTTER_INPUT);
    }

    #[test]
    fn select_by_input_preserves_master_order() {
        // The click sends an index into THIS list, so a filter that reordered
        // — grouping by result, say, or sorting by name — would select a
        // different recipe than the one drawn, silently.
        let cuts = select_by_input("minecraft:andesite");
        assert!(cuts.len() > 1, "andesite cuts several ways");
        let mut it = STONECUTTER_RECIPES.iter();
        for c in &cuts {
            assert!(it.any(|m| std::ptr::eq(m, *c)), "out of master order");
        }
        assert!(cuts.iter().all(|c| c.input == "minecraft:andesite"));
    }

    #[test]
    fn an_unaccepted_item_offers_nothing() {
        assert!(select_by_input("minecraft:dirt").is_empty());
        // …and cutting is one-directional: a result is not thereby an input.
        assert!(select_by_input("minecraft:andesite_stairs").is_empty());
    }

    #[test]
    fn results_carry_their_count_even_though_the_button_hides_it() {
        // `extractRecipes` calls `graphics.item`, which draws the model and
        // nothing else. A naive reuse of the inventory's slot draw would put a
        // "2" on every slab button.
        assert_eq!(STONECUTTER_RECIPES.iter().filter(|c| c.count == 2).count(), 84);
        let counts: std::collections::BTreeSet<u8> =
            STONECUTTER_RECIPES.iter().map(|c| c.count).collect();
        assert_eq!(counts.into_iter().collect::<Vec<_>>(), vec![1, 2, 4, 8]);
    }
}
