//! What a stonecutter will accept — GENERATED by
//! `tools/gen_stonecutter_inputs.py`.
//!
//! Do not edit. Re-run the generator after a version bump. (It emits its own
//! tests, so a re-run reproduces this file whole — `smelting_table.rs` used to
//! carry hand-added tests its generator did not emit, which meant following
//! that same instruction silently deleted them.)
//!
//! `StonecutterMenu.quickMoveStack`'s third branch is
//! `level.recipeAccess().stonecutterRecipes().acceptsInput(stack)`, which is a
//! `SelectableRecipe.SingleInputSet` and **not** a `RecipePropertySet` — that
//! registry has seven keys and the stonecutter is not one of them. Membership
//! still reduces to the union of every stonecutting recipe's ingredient,
//! because `Ingredient.test` is `input.is(this.values)`: item identity, no
//! components.
//!
//! # The caveat
//!
//! The real set arrives in `update_recipes`, which Rewo does not decode. **A
//! datapack that adds or removes a stonecutting recipe makes this wrong with
//! no error anywhere.** Same trade M19 makes reading `ItemTags.SPEARS` from the
//! jar, M42 the enchantment tags, and M91 the smelting sets.

/// Every item a stonecutter accepts in its input slot — 65 items,
/// the union of 319 recipes' ingredients, in recipe-file order.
pub static STONECUTTER_INPUT: &[&str] = &[
    "minecraft:andesite",
    "minecraft:blackstone",
    "minecraft:bricks",
    "minecraft:cinnabar",
    "minecraft:copper_block",
    "minecraft:cut_copper",
    "minecraft:cobbled_deepslate",
    "minecraft:deepslate",
    "minecraft:nether_bricks",
    "minecraft:polished_blackstone",
    "minecraft:quartz_block",
    "minecraft:red_sandstone",
    "minecraft:resin_bricks",
    "minecraft:sandstone",
    "minecraft:stone_bricks",
    "minecraft:stone",
    "minecraft:sulfur",
    "minecraft:polished_tuff",
    "minecraft:tuff_bricks",
    "minecraft:tuff",
    "minecraft:cinnabar_bricks",
    "minecraft:polished_cinnabar",
    "minecraft:cobblestone",
    "minecraft:cut_red_sandstone",
    "minecraft:cut_sandstone",
    "minecraft:dark_prismarine",
    "minecraft:deepslate_bricks",
    "minecraft:polished_deepslate",
    "minecraft:deepslate_tiles",
    "minecraft:diorite",
    "minecraft:end_stone_bricks",
    "minecraft:end_stone",
    "minecraft:exposed_copper",
    "minecraft:exposed_cut_copper",
    "minecraft:granite",
    "minecraft:mossy_cobblestone",
    "minecraft:mossy_stone_bricks",
    "minecraft:mud_bricks",
    "minecraft:oxidized_copper",
    "minecraft:oxidized_cut_copper",
    "minecraft:polished_andesite",
    "minecraft:basalt",
    "minecraft:polished_blackstone_bricks",
    "minecraft:polished_diorite",
    "minecraft:polished_granite",
    "minecraft:polished_sulfur",
    "minecraft:prismarine_bricks",
    "minecraft:prismarine",
    "minecraft:purpur_block",
    "minecraft:red_nether_bricks",
    "minecraft:smooth_quartz",
    "minecraft:smooth_red_sandstone",
    "minecraft:smooth_sandstone",
    "minecraft:smooth_stone",
    "minecraft:sulfur_bricks",
    "minecraft:waxed_copper_block",
    "minecraft:waxed_cut_copper",
    "minecraft:waxed_exposed_copper",
    "minecraft:waxed_exposed_cut_copper",
    "minecraft:waxed_oxidized_copper",
    "minecraft:waxed_oxidized_cut_copper",
    "minecraft:waxed_weathered_copper",
    "minecraft:waxed_weathered_cut_copper",
    "minecraft:weathered_copper",
    "minecraft:weathered_cut_copper",
];

/// `SingleInputSet.acceptsInput` — whether a stonecutter routes this item to
/// its input slot on a shift-click.
///
/// Note this is **not** the input slot's `mayPlace`: that slot is a bare
/// `Slot` with no override, so an ordinary click can put anything in it. The
/// predicate exists only in `quickMoveStack`.
pub fn accepts_input(item: &str) -> bool {
    STONECUTTER_INPUT.contains(&item)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_obvious_stonecuttable_blocks_are_accepted() {
        assert!(accepts_input("minecraft:stone"));
        assert!(accepts_input("minecraft:andesite"));
        assert!(accepts_input("minecraft:copper_block"));
    }

    #[test]
    fn an_item_with_no_stonecutting_recipe_is_refused() {
        // The negative is what the routing actually turns on: a false here is
        // what sends the stack to the hotbar instead of the input slot.
        assert!(!accepts_input("minecraft:stick"));
        assert!(!accepts_input("minecraft:beef"));
        // A stonecutter RESULT is not itself an input — quartz stairs are cut
        // from the block, and cutting the stairs again is not a recipe.
        assert!(!accepts_input("minecraft:andesite_wall"));
    }

    #[test]
    fn the_stonecutter_set_is_not_the_furnace_set() {
        // If the two tables were wired to the same data the routing would
        // still "work" and be wrong in both menus. The pair must be genuinely
        // disjoint, which `stone` is NOT — it cuts into slabs and smelts into
        // smooth stone, so the first draft of this test asserted stone was
        // unsmeltable and failed against correct code.
        assert!(accepts_input("minecraft:andesite"));
        assert_eq!(crate::smelting_table::accepts(14, "minecraft:andesite"), Some(false));
        assert!(!accepts_input("minecraft:beef"));
        assert_eq!(crate::smelting_table::accepts(14, "minecraft:beef"), Some(true));
    }

    #[test]
    fn an_item_that_is_both_is_routed_by_the_MENU_not_by_the_item() {
        // M91's log — fuel AND smeltable — one menu over. Cobblestone cuts
        // into stairs and smelts into stone, so a single "what is this item
        // for" flag could not route it: the furnace sends it to the ingredient
        // slot and the stonecutter to the input slot, and both are right.
        assert!(accepts_input("minecraft:cobblestone"));
        assert_eq!(crate::smelting_table::accepts(14, "minecraft:cobblestone"), Some(true));
    }
}
