//! GENERATED by `tools/gen_swing_animations.py` — do not edit.
//!
//! Source: the 26.2 datagen item-component report
//! (`reports/minecraft/components/item/*.json`), field
//! `minecraft:swing_animation`, cross-checked against the decompiled
//! `SwingAnimation.DEFAULT` and `SwingAnimationType` wire ids.
//!
//! The component is a *prototype* value: `DataComponents`
//! `COMMON_ITEM_COMPONENTS` sets it on every item, so it is not in the
//! `DataComponentPatch` a server sends — the client resolves it from the
//! item id. That is why this table exists.
//!
//! 1537 items scanned, 7 non-default.

/// Items present in the report this table was generated from. A runtime
/// registry with a wildly different size means the pin has drifted.
pub const SCANNED_ITEMS: usize = 1537;

/// `SwingAnimation.DEFAULT.type()` as its wire id
/// (`SwingAnimationType.WHACK`).
pub const DEFAULT_TYPE_ID: u8 = 1;

/// `SwingAnimation.DEFAULT.duration()`, in ticks.
pub const DEFAULT_DURATION: i32 = 6;

/// Every item whose prototype `swing_animation` differs from the default:
/// `(registry name, SwingAnimationType wire id, duration ticks)`.
pub const NON_DEFAULT: &[(&str, u8, i32)] = &[
    ("minecraft:copper_spear", 2, 17),
    ("minecraft:diamond_spear", 2, 21),
    ("minecraft:golden_spear", 2, 19),
    ("minecraft:iron_spear", 2, 19),
    ("minecraft:netherite_spear", 2, 23),
    ("minecraft:stone_spear", 2, 15),
    ("minecraft:wooden_spear", 2, 13),
];
