//! GENERATED by `tools/gen_use_items.py` — do not edit.
//!
//! Source: the 26.2 datagen item-component report
//! (`reports/minecraft/components/item/*.json`) resolved through
//! decompiled `Item.getUseDuration` / `getUseAnimation`, plus the
//! eight item classes that override either method.
//!
//! Like `swing_anim_table`, this is a *prototype* resolution: the values
//! come from the item id, because the components they read are not in the
//! `DataComponentPatch` a server sends for an ordinary stack.
//!
//! 1537 items scanned, 74 usable.

/// Items present in the report this table was generated from.
pub const SCANNED_ITEMS: usize = 1537;

/// `ItemUseAnimation` wire ids, as declared by the enum.
pub mod anim {
    /// `ItemUseAnimation.NONE`
    pub const NONE: u8 = 0;
    /// `ItemUseAnimation.EAT`
    pub const EAT: u8 = 1;
    /// `ItemUseAnimation.DRINK`
    pub const DRINK: u8 = 2;
    /// `ItemUseAnimation.BLOCK`
    pub const BLOCK: u8 = 3;
    /// `ItemUseAnimation.BOW`
    pub const BOW: u8 = 4;
    /// `ItemUseAnimation.TRIDENT`
    pub const TRIDENT: u8 = 5;
    /// `ItemUseAnimation.CROSSBOW`
    pub const CROSSBOW: u8 = 6;
    /// `ItemUseAnimation.SPYGLASS`
    pub const SPYGLASS: u8 = 7;
    /// `ItemUseAnimation.TOOT_HORN`
    pub const TOOT_HORN: u8 = 8;
    /// `ItemUseAnimation.BRUSH`
    pub const BRUSH: u8 = 9;
    /// `ItemUseAnimation.BUNDLE`
    pub const BUNDLE: u8 = 10;
    /// `ItemUseAnimation.SPEAR`
    pub const SPEAR: u8 = 11;
}

/// `Item.getUseDuration`'s non-consumable branch, in ticks —
/// effectively "until released".
pub const BLOCKING_DURATION: i32 = 72000;

/// Every item that can actually be used: `(registry name, use duration
/// ticks, ItemUseAnimation wire id)`. An item absent from this table
/// resolves to `(0, NONE)` — it cannot be used, so it can never reach a
/// use-driven arm pose.
pub const USABLE: &[(&str, i32, u8)] = &[
    ("minecraft:apple", 32, 1), // eat
    ("minecraft:baked_potato", 32, 1), // eat
    ("minecraft:beef", 32, 1), // eat
    ("minecraft:beetroot", 32, 1), // eat
    ("minecraft:beetroot_soup", 32, 1), // eat
    ("minecraft:black_bundle", 200, 10), // bundle
    ("minecraft:blue_bundle", 200, 10), // bundle
    ("minecraft:bow", 72000, 4), // bow
    ("minecraft:bread", 32, 1), // eat
    ("minecraft:brown_bundle", 200, 10), // bundle
    ("minecraft:brush", 200, 9), // brush
    ("minecraft:bundle", 200, 10), // bundle
    ("minecraft:carrot", 32, 1), // eat
    ("minecraft:chicken", 32, 1), // eat
    ("minecraft:chorus_fruit", 32, 1), // eat
    ("minecraft:cod", 32, 1), // eat
    ("minecraft:cooked_beef", 32, 1), // eat
    ("minecraft:cooked_chicken", 32, 1), // eat
    ("minecraft:cooked_cod", 32, 1), // eat
    ("minecraft:cooked_mutton", 32, 1), // eat
    ("minecraft:cooked_porkchop", 32, 1), // eat
    ("minecraft:cooked_rabbit", 32, 1), // eat
    ("minecraft:cooked_salmon", 32, 1), // eat
    ("minecraft:cookie", 32, 1), // eat
    ("minecraft:copper_spear", 72000, 11), // spear
    ("minecraft:crossbow", 72000, 6), // crossbow
    ("minecraft:cyan_bundle", 200, 10), // bundle
    ("minecraft:diamond_spear", 72000, 11), // spear
    ("minecraft:dried_kelp", 16, 1), // eat
    ("minecraft:enchanted_golden_apple", 32, 1), // eat
    ("minecraft:glow_berries", 32, 1), // eat
    ("minecraft:goat_horn", 140, 8), // toot_horn
    ("minecraft:golden_apple", 32, 1), // eat
    ("minecraft:golden_carrot", 32, 1), // eat
    ("minecraft:golden_spear", 72000, 11), // spear
    ("minecraft:gray_bundle", 200, 10), // bundle
    ("minecraft:green_bundle", 200, 10), // bundle
    ("minecraft:honey_bottle", 40, 2), // drink
    ("minecraft:iron_spear", 72000, 11), // spear
    ("minecraft:light_blue_bundle", 200, 10), // bundle
    ("minecraft:light_gray_bundle", 200, 10), // bundle
    ("minecraft:lime_bundle", 200, 10), // bundle
    ("minecraft:magenta_bundle", 200, 10), // bundle
    ("minecraft:melon_slice", 32, 1), // eat
    ("minecraft:milk_bucket", 32, 2), // drink
    ("minecraft:mushroom_stew", 32, 1), // eat
    ("minecraft:mutton", 32, 1), // eat
    ("minecraft:netherite_spear", 72000, 11), // spear
    ("minecraft:ominous_bottle", 32, 2), // drink
    ("minecraft:orange_bundle", 200, 10), // bundle
    ("minecraft:pink_bundle", 200, 10), // bundle
    ("minecraft:poisonous_potato", 32, 1), // eat
    ("minecraft:porkchop", 32, 1), // eat
    ("minecraft:potato", 32, 1), // eat
    ("minecraft:potion", 32, 2), // drink
    ("minecraft:pufferfish", 32, 1), // eat
    ("minecraft:pumpkin_pie", 32, 1), // eat
    ("minecraft:purple_bundle", 200, 10), // bundle
    ("minecraft:rabbit", 32, 1), // eat
    ("minecraft:rabbit_stew", 32, 1), // eat
    ("minecraft:red_bundle", 200, 10), // bundle
    ("minecraft:rotten_flesh", 32, 1), // eat
    ("minecraft:salmon", 32, 1), // eat
    ("minecraft:shield", 72000, 3), // block
    ("minecraft:spider_eye", 32, 1), // eat
    ("minecraft:spyglass", 1200, 7), // spyglass
    ("minecraft:stone_spear", 72000, 11), // spear
    ("minecraft:suspicious_stew", 32, 1), // eat
    ("minecraft:sweet_berries", 32, 1), // eat
    ("minecraft:trident", 72000, 5), // trident
    ("minecraft:tropical_fish", 32, 1), // eat
    ("minecraft:white_bundle", 200, 10), // bundle
    ("minecraft:wooden_spear", 72000, 11), // spear
    ("minecraft:yellow_bundle", 200, 10), // bundle
];
