"""Generate crates/rewo-data/src/stonecutter_table.rs from the jar's recipes.

`StonecutterMenu.quickMoveStack` routes a player stack into the input slot when

    this.level.recipeAccess().stonecutterRecipes().acceptsInput(stack)

and that is **not** a `RecipePropertySet`. `RecipePropertySet` has seven keys —
SMITHING_BASE / SMITHING_TEMPLATE / SMITHING_ADDITION / FURNACE_INPUT /
BLAST_FURNACE_INPUT / SMOKER_INPUT / CAMPFIRE_INPUT — and none of them is the
stonecutter. `RecipeAccess` exposes it as its own accessor returning a
`SelectableRecipe.SingleInputSet<StonecutterRecipe>`, whose membership test is

    entries.stream().anyMatch(e -> e.input.test(input))

The distinction is real and does not reach this table: a furnace's set is a
flat `Set<Holder<Item>>` built by flat-mapping ingredients, the stonecutter's
keeps one entry per recipe so `selectByInput` can offer the matching results —
but `Ingredient.test` is `input.is(this.values)`, item identity with no
components, so *membership* is the same union either way. The per-entry
structure matters for the recipe LIST widget, which is separate work and
blocked on `update_recipes`.

**The caveat is M91's, unchanged:** these sets really arrive in
`update_recipes`, which Rewo does not decode. A datapack that adds or removes a
stonecutting recipe makes this table wrong with no error anywhere — a
shift-clicked block routes to the player's inventory instead of the input slot,
or the reverse. This is the vanilla answer, not the server's.

Run:  python tools/gen_stonecutter_inputs.py
"""

from __future__ import annotations

import os
import sys

from recipe_ingredients import accepted_inputs  # tools/ is sys.path[0]

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "crates", "rewo-data", "src", "stonecutter_table.rs",
)

TOOL = "gen_stonecut"
# 319 in 26.2. Floored just under, so a collapse fails and a handful of new
# vanilla recipes do not. See gen_smelting_inputs.py for why the guard is here
# rather than as a `.len()` assertion in the generated file.
FLOOR = 300


def main() -> int:
    acc, found = accepted_inputs(TOOL, "minecraft:stonecutting", FLOOR)
    print(f"[{TOOL}] {found} recipes -> {len(acc)} accepted inputs")

    rows = "\n".join(f'    "{i}",' for i in acc)
    out = f'''//! What a stonecutter will accept — GENERATED by
//! `tools/gen_stonecutter_inputs.py`.
//!
//! Do not edit. Re-run the generator after a version bump. (It emits its own
//! tests, so a re-run reproduces this file whole — `smelting_table.rs` used to
//! carry hand-added tests its generator did not emit, which meant following
//! that same instruction silently deleted them.)
//!
//! `StonecutterMenu.quickMoveStack`'s third branch is
//! `level.recipeAccess().stonecutterRecipes().acceptsInput(stack)`, which is a
//! `SelectableRecipe.SingleInputSet` and **not** a `RecipePropertySet` — that
//! registry has seven keys and the stonecutter is not one of them. Membership
//! still reduces to the union of every stonecutting recipe's ingredient,
//! because `Ingredient.test` is `input.is(this.values)`: item identity, no
//! components.
//!
//! # The caveat
//!
//! The real set arrives in `update_recipes`, which Rewo does not decode. **A
//! datapack that adds or removes a stonecutting recipe makes this wrong with
//! no error anywhere.** Same trade M19 makes reading `ItemTags.SPEARS` from the
//! jar, M42 the enchantment tags, and M91 the smelting sets.

/// Every item a stonecutter accepts in its input slot — {len(acc)} items,
/// the union of {found} recipes' ingredients, in recipe-file order.
pub static STONECUTTER_INPUT: &[&str] = &[
{rows}
];

/// `SingleInputSet.acceptsInput` — whether a stonecutter routes this item to
/// its input slot on a shift-click.
///
/// Note this is **not** the input slot's `mayPlace`: that slot is a bare
/// `Slot` with no override, so an ordinary click can put anything in it. The
/// predicate exists only in `quickMoveStack`.
pub fn accepts_input(item: &str) -> bool {{
    STONECUTTER_INPUT.contains(&item)
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn the_obvious_stonecuttable_blocks_are_accepted() {{
        assert!(accepts_input("minecraft:stone"));
        assert!(accepts_input("minecraft:andesite"));
        assert!(accepts_input("minecraft:copper_block"));
    }}

    #[test]
    fn an_item_with_no_stonecutting_recipe_is_refused() {{
        // The negative is what the routing actually turns on: a false here is
        // what sends the stack to the hotbar instead of the input slot.
        assert!(!accepts_input("minecraft:stick"));
        assert!(!accepts_input("minecraft:beef"));
        // A stonecutter RESULT is not itself an input — quartz stairs are cut
        // from the block, and cutting the stairs again is not a recipe.
        assert!(!accepts_input("minecraft:andesite_wall"));
    }}

    #[test]
    fn the_stonecutter_set_is_not_the_furnace_set() {{
        // If the two tables were wired to the same data the routing would
        // still "work" and be wrong in both menus. The pair must be genuinely
        // disjoint, which `stone` is NOT — it cuts into slabs and smelts into
        // smooth stone, so the first draft of this test asserted stone was
        // unsmeltable and failed against correct code.
        assert!(accepts_input("minecraft:andesite"));
        assert_eq!(crate::smelting_table::accepts(14, "minecraft:andesite"), Some(false));
        assert!(!accepts_input("minecraft:beef"));
        assert_eq!(crate::smelting_table::accepts(14, "minecraft:beef"), Some(true));
    }}

    #[test]
    fn an_item_that_is_both_is_routed_by_the_MENU_not_by_the_item() {{
        // M91's log — fuel AND smeltable — one menu over. Cobblestone cuts
        // into stairs and smelts into stone, so a single "what is this item
        // for" flag could not route it: the furnace sends it to the ingredient
        // slot and the stonecutter to the input slot, and both are right.
        assert!(accepts_input("minecraft:cobblestone"));
        assert_eq!(crate::smelting_table::accepts(14, "minecraft:cobblestone"), Some(true));
    }}
}}
'''
    open(OUT, "w", encoding="utf-8", newline="\n").write(out)
    print(f"[{TOOL}] wrote {os.path.relpath(OUT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
