# Generates crates/rewo-gpu/src/anim_defs.rs from the decompiled 26.2
# AnimationDefinition sources (vanilla keyframe rigs). Values are baked to
# runtime units: degreeVec -> radians, posVec -> (x, -y, z) model px,
# scale channels skipped (renderer has no per-part scale).
#
#   powershell -File tools/gen_anim_defs.ps1
#
# Deterministic output; re-run after a version bump and diff.

$dec = Join-Path $env:APPDATA "EwoClient/rewo/26.2/decompiled/net/minecraft/client/animation/definitions"
$targets = @(
    @{ File = "FrogAnimation.java";        Const = "FROG_WALK" },
    @{ File = "CamelAnimation.java";       Const = "CAMEL_WALK" },
    @{ File = "SnifferAnimation.java";     Const = "SNIFFER_WALK" },
    @{ File = "ArmadilloAnimation.java";   Const = "ARMADILLO_WALK" },
    @{ File = "BatAnimation.java";         Const = "BAT_FLYING" },
    @{ File = "CreakingAnimation.java";    Const = "CREAKING_WALK" },
    @{ File = "CopperGolemAnimation.java"; Const = "COPPER_GOLEM_WALK" },
    @{ File = "CopperGolemAnimation.java"; Const = "COPPER_GOLEM_IDLE" },
    @{ File = "NautilusAnimation.java";    Const = "SWIMMING"; Rename = "NAUTILUS_SWIMMING" },
    @{ File = "BreezeAnimation.java";      Const = "IDLE"; Rename = "BREEZE_IDLE" },
    @{ File = "RabbitAnimation.java";      Const = "HOP"; Rename = "RABBIT_HOP" }
)

$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine('//! GENERATED by tools/gen_anim_defs.ps1 from the decompiled 26.2')
[void]$out.AppendLine('//! AnimationDefinitions - do not edit by hand; re-run the script.')
[void]$out.AppendLine('//! Rotations are radians, positions model px with the vanilla posVec')
[void]$out.AppendLine('//! y-negation baked in. Scale channels are omitted (unsupported).')
[void]$out.AppendLine('')
[void]$out.AppendLine('use crate::mobs::{KfChannel, KfDef, KfFrame, KfTarget};')
[void]$out.AppendLine('')

function Parse-Def($path, $const, $emitName) {
    $lines = Get-Content $path
    $inDef = $false; $depth = 0
    $length = "0.0"; $looping = $false
    $channels = @()   # list of @{ Part; Target; Frames = @(...) }
    $curPart = $null; $curTarget = $null; $curFrames = $null
    foreach ($line in $lines) {
        if (-not $inDef) {
            if ($line -match "AnimationDefinition\s+$const\s*=\s*AnimationDefinition\.Builder\.withLength\(([-0-9.Ee]+)F?\)") {
                $inDef = $true
                $length = $Matches[1]
            }
            continue
        }
        if ($line -match "\.looping\(\)") { $looping = $true }
        if ($line -match '^\s*"([a-z_0-9]+)",\s*$' -or $line -match '\.addAnimation\(\s*"([a-z_0-9]+)",') {
            # Close the previous channel.
            if ($null -ne $curPart -and $null -ne $curTarget -and $curFrames.Count -gt 0) {
                $channels += @{ Part = $curPart; Target = $curTarget; Frames = $curFrames }
            }
            $curPart = $Matches[1]; $curTarget = $null; $curFrames = @()
        }
        if ($line -match "AnimationChannel\.Targets\.(ROTATION|POSITION|SCALE)") {
            $curTarget = $Matches[1]
        }
        if ($line -match "new Keyframe\(([-0-9.Ee]+)F?,\s*KeyframeAnimations\.(degreeVec|posVec|scaleVec)\(([^)]*)\),\s*AnimationChannel\.Interpolations\.(LINEAR|CATMULLROM)\)") {
            $t = [double]$Matches[1]
            $kind = $Matches[2]
            $raw = $Matches[3].Split(",")
            $interp = $Matches[4]
            $n0 = [double]$raw[0].Trim().TrimEnd("F")
            $n1 = [double]$raw[1].Trim().TrimEnd("F")
            $n2 = [double]$raw[2].Trim().TrimEnd("F")
            $d2r = [math]::PI / 180.0
            if ($kind -eq "degreeVec") {
                $v0 = $n0 * $d2r; $v1 = $n1 * $d2r; $v2 = $n2 * $d2r
            } elseif ($kind -eq "posVec") {
                $v0 = $n0; $v1 = - $n1; $v2 = $n2
            } else {
                $v0 = $n0 - 1.0; $v1 = $n1 - 1.0; $v2 = $n2 - 1.0
            }
            $curFrames += , @{ T = $t; V0 = $v0; V1 = $v1; V2 = $v2; Cat = ($interp -eq "CATMULLROM") }
        }
        if ($line -match "\.build\(\);") {
            if ($null -ne $curPart -and $null -ne $curTarget -and $curFrames.Count -gt 0) {
                $channels += @{ Part = $curPart; Target = $curTarget; Frames = $curFrames }
            }
            break
        }
    }
    if (-not $inDef) { throw "const $const not found in $path" }

    $kept = @($channels | Where-Object { $_.Target -ne "SCALE" })
    $skipped = $channels.Count - $kept.Count
    [void]$out.AppendLine("/// $const ($path | $($kept.Count) channels, $skipped scale skipped)")
    [void]$out.AppendLine("pub static ${emitName}: KfDef = KfDef {")
    [void]$out.AppendLine("    length: ${length},")
    [void]$out.AppendLine("    looping: $(if ($looping) { "true" } else { "false" }),")
    [void]$out.AppendLine("    channels: &[")
    foreach ($ch in $kept) {
        $tgt = if ($ch.Target -eq "ROTATION") { "Rot" } else { "Pos" }
        [void]$out.AppendLine("        KfChannel {")
        [void]$out.AppendLine("            part: `"$($ch.Part)`",")
        [void]$out.AppendLine("            target: KfTarget::$tgt,")
        [void]$out.AppendLine("            frames: &[")
        foreach ($f in $ch.Frames) {
            $fmt = {
                param($x)
                $s = "{0:G9}" -f $x
                if ($s -notmatch "[.eE]") { $s = $s + ".0" }
                $s
            }
            $vals = (& $fmt $f.V0) + ", " + (& $fmt $f.V1) + ", " + (& $fmt $f.V2)
            $t = "{0:G9}" -f $f.T
            if ($t -notmatch "[.eE]") { $t = $t + ".0" }
            $cat = if ($f.Cat) { "true" } else { "false" }
            [void]$out.AppendLine("                KfFrame { t: $t, v: [$vals], catmullrom: $cat },")
        }
        [void]$out.AppendLine("            ],")
        [void]$out.AppendLine("        },")
    }
    [void]$out.AppendLine("    ],")
    [void]$out.AppendLine("};")
    [void]$out.AppendLine("")
}

foreach ($t in $targets) {
    $emit = if ($t.Rename) { $t.Rename } else { $t.Const }
    Parse-Def (Join-Path $dec $t.File) $t.Const $emit
}

$dst = Join-Path $PSScriptRoot "../crates/rewo-gpu/src/anim_defs.rs"
$out.ToString() | Out-File -Encoding utf8 $dst
Write-Output "wrote $dst"
