"""Machine-extract, from the decompiled 26.2 jar, the per-effect facts the HUD
needs and the wire never carries — into `crates/rewo-data/src/mob_effect_table.rs`.

Why this exists
---------------
`Hud.extractEffects` (Hud.java:486-526) lays an icon out by
`effect.value().isBeneficial()` — BENEFICIAL on the top row, everything else
(HARMFUL **and NEUTRAL**) 26 px lower — and `MobEffectInstance.compareTo`
(MobEffectInstance.java:339-351) breaks its ties on `effect.getColor()`. Both
facts live in the `MobEffect` constructor call in `MobEffects.java` and in
nothing else: the datagen report's `minecraft:mob_effect` registry carries
only `protocol_id` (measured: 40 entries, key set `{protocol_id}`), and the
registry is a `BuiltInRegistries` entry the server never syncs (M92c). So the
category and the colour are a jar-derived table, exactly as `entity_classes`
and `entity_attributes` are.

The order is load-bearing
-------------------------
`MobEffects.register` is `Registry.registerForHolder(BuiltInRegistries
.MOB_EFFECT, ...)` in static-initialiser order, so the declaration order in
`MobEffects.java` **is** the registry's protocol-id order. The table below is
emitted in that order and a unit test in `mob_effect_table.rs` grades it
against `registries.json` on any machine that has the report — a version that
inserts an effect mid-list fails that test rather than silently shifting every
icon one slot along (M64's trap, in a table rather than a map).

Fail loud
---------
Every `register("...")` in the file must match the constructor pattern, or the
script refuses to emit. A registration the regex cannot read is more likely a
changed constructor shape than a new kind of effect, and a short table would
be green in every gate until a real server sent the missing id.

Usage: python tools/gen_mob_effects.py
"""

import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DECOMP = os.path.join(
    os.environ.get("APPDATA", ""), "EwoClient", "rewo", "26.2", "decompiled",
    "net", "minecraft", "world", "effect", "MobEffects.java",
)
OUT = os.path.join(ROOT, "crates", "rewo-data", "src", "mob_effect_table.rs")

# `register("name", new <AnyMobEffectSubclass>(MobEffectCategory.CAT, colour`
# — the category and colour are always the first two constructor arguments,
# whatever the subclass (`PoisonMobEffect`, `HealOrHarmMobEffect`, ...).
PATTERN = re.compile(
    r'register\(\s*"([a-z_]+)",\s*new\s+(\w+)\(\s*MobEffectCategory\.(\w+),\s*(\d+)',
    re.S,
)
ANY_REGISTER = re.compile(r'\bregister\(\s*"')

CAT_RS = {"BENEFICIAL": "Beneficial", "HARMFUL": "Harmful", "NEUTRAL": "Neutral"}


def main():
    src = io.open(DECOMP, encoding="utf-8").read()
    rows = PATTERN.findall(src)
    total = len(ANY_REGISTER.findall(src))
    if len(rows) != total or not rows:
        sys.exit(
            f"gen_mob_effects: matched {len(rows)} constructor patterns against "
            f"{total} register(...) calls - a registration the pattern cannot "
            f"read; refusing to emit a short table"
        )
    cats = {c for _, _, c, _ in rows}
    if not cats <= set(CAT_RS):
        sys.exit(f"gen_mob_effects: unknown category in {cats}")

    out = []
    w = out.append
    w("//! GENERATED by `tools/gen_mob_effects.py` — do not edit.")
    w("//!")
    w("//! Source: the decompiled 26.2 client (`MobEffects.java`), in its")
    w("//! static-initialiser order — which IS the `minecraft:mob_effect`")
    w("//! registry's protocol-id order, and is pinned against the datagen")
    w("//! report by the test at the bottom. Re-run after a version bump; the")
    w("//! script fails loud on a registration it cannot read.")
    w("//!")
    w(f"//! {len(rows)} effects.")
    w("")
    w("/// `MobEffectCategory` — the only thing `Hud.extractEffects` asks of an")
    w("/// effect is `isBeneficial()`, i.e. `category == BENEFICIAL`, so a NEUTRAL")
    w("/// effect (glowing, bad_omen, trial_omen, raid_omen) shares the HARMFUL row.")
    w("#[derive(Clone, Copy, Debug, PartialEq, Eq)]")
    w("pub enum MobEffectCategory {")
    w("    Beneficial,")
    w("    Harmful,")
    w("    Neutral,")
    w("}")
    w("")
    w("impl MobEffectCategory {")
    w("    /// `MobEffect.isBeneficial()` — `this.category == MobEffectCategory.BENEFICIAL`.")
    w("    pub fn is_beneficial(self) -> bool {")
    w("        self == MobEffectCategory::Beneficial")
    w("    }")
    w("}")
    w("")
    w("/// One registered `minecraft:mob_effect`, in registry order.")
    w("#[derive(Clone, Copy, Debug, PartialEq, Eq)]")
    w("pub struct MobEffectDef {")
    w("    /// The registry path, without the `minecraft:` namespace.")
    w("    pub name: &'static str,")
    w("    pub category: MobEffectCategory,")
    w("    /// `MobEffect.getColor()` — the constructor's int, the last tie-break")
    w("    /// in `MobEffectInstance.compareTo`.")
    w("    pub color: u32,")
    w("}")
    w("")
    w("/// Indexed by protocol id.")
    w(f"pub const MOB_EFFECTS: [MobEffectDef; {len(rows)}] = [")
    for name, _cls, cat, colour in rows:
        w(
            f'    MobEffectDef {{ name: "{name}", '
            f"category: MobEffectCategory::{CAT_RS[cat]}, color: {int(colour)} }},"
        )
    w("];")
    w("")
    w("/// The table row for a protocol id, or `None` past the end — never a")
    w("/// substitute, for the reason `MobEffects::id_of` gives.")
    w("pub fn def(id: i32) -> Option<&'static MobEffectDef> {")
    w("    usize::try_from(id).ok().and_then(|i| MOB_EFFECTS.get(i))")
    w("}")
    w("")
    w("/// The protocol id of a registry path (without `minecraft:`), or `None`")
    w("/// for a name this version does not register. Valid as an id because the")
    w("/// table order is pinned against the report (the test below).")
    w("pub fn id_of(name: &str) -> Option<i32> {")
    w("    MOB_EFFECTS.iter().position(|d| d.name == name).map(|i| i as i32)")
    w("}")
    w("")
    w("#[cfg(test)]")
    w("mod tests {")
    w("    use super::*;")
    w("")
    w("    /// The declaration order is the registry order — graded against the")
    w("    /// report rather than assumed, on any machine that has it.")
    w("    #[test]")
    w("    fn the_table_order_is_the_registrys_protocol_id_order() {")
    w('        let Some(paths) = crate::DataPaths::for_version("26.2") else {')
    w("            return;")
    w("        };")
    w("        let Ok(reg) = crate::mob_effects::MobEffects::load(&paths.registries_json())")
    w("        else {")
    w("            return;")
    w("        };")
    w("        assert_eq!(")
    w("            reg.len(),")
    w("            MOB_EFFECTS.len(),")
    w('            "the report and the table disagree on the count"')
    w("        );")
    w("        for (i, d) in MOB_EFFECTS.iter().enumerate() {")
    w("            assert_eq!(")
    w("                reg.name(i as i32),")
    w('                Some(format!("minecraft:{}", d.name).as_str()),')
    w('                "slot {i} is {} in the table",')
    w("                d.name")
    w("            );")
    w("        }")
    w("    }")
    w("")
    w("    /// Pinned from MobEffects.java by a direct grep (20/16/4), independently of the generator:")
    w("    /// the counts, the four NEUTRALs that share the harmful row, and one")
    w("    /// colour per category.")
    w("    #[test]")
    w("    fn the_categories_and_colours_are_the_decompiles() {")
    w("        let count = |c: MobEffectCategory| MOB_EFFECTS.iter().filter(|d| d.category == c).count();")
    w("        assert_eq!(count(MobEffectCategory::Beneficial), 20);")
    w("        assert_eq!(count(MobEffectCategory::Harmful), 16);")
    w("        let neutral: Vec<&str> = MOB_EFFECTS")
    w("            .iter()")
    w("            .filter(|d| d.category == MobEffectCategory::Neutral)")
    w("            .map(|d| d.name)")
    w("            .collect();")
    w('        assert_eq!(neutral, ["glowing", "bad_omen", "trial_omen", "raid_omen"]);')
    w("        // Hud.java tests `isBeneficial()` only, so NEUTRAL is not beneficial.")
    w("        assert!(!MobEffectCategory::Neutral.is_beneficial());")
    w('        assert_eq!(def(0).map(|d| (d.name, d.color)), Some(("speed", 3402751)));')
    w('        assert_eq!(def(18).map(|d| (d.name, d.color)), Some(("poison", 8889187)));')
    w('        assert_eq!(def(39).map(|d| d.name), Some("breath_of_the_nautilus"));')
    w("        assert_eq!(def(40), None);")
    w("        assert_eq!(def(-1), None);")
    w("    }")
    w("}")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print(f"wrote {OUT}: {len(rows)} effects")


if __name__ == "__main__":
    main()
