"""Generate crates/rewo-data/src/smelting_table.rs from the jar's own recipes.

`AbstractFurnaceMenu.canSmelt` is `acceptedInputs.test(stack)`, where
`acceptedInputs` is `recipeAccess.propertySet(allowedInputs)` and each furnace
passes its own:

    FurnaceMenu       -> RecipePropertySet.FURNACE_INPUT       (smelting)
    BlastFurnaceMenu  -> RecipePropertySet.BLAST_FURNACE_INPUT (blasting)
    SmokerMenu        -> RecipePropertySet.SMOKER_INPUT        (smoking)

On the client those sets arrive in `update_recipes`, which Rewo does not decode
— but for **vanilla** their contents are exactly the ingredient sets of the
jar's own `data/minecraft/recipe/*.json`, and the jar is already the source for
`ItemTags.SPEARS` (M19) and the enchantment tags (M42).

**The caveat that comes with that, and it is the same one M19 and M42 carry:**
a datapack that adds or removes a smelting recipe makes this table wrong, with
no error anywhere — a shift-clicked item would route to the player's inventory
instead of the ingredient slot, or the reverse. `update_recipes` is the
authoritative source and is class C. This is the vanilla answer, not the
server's.

Ingredients are either an item id or a `#tag`, and tags nest, so expansion
recurses — the same shape `gen_fuel_values.py` handles.

Run:  python tools/gen_smelting_inputs.py
Exit: 0 on success; 1 on an unresolvable tag or item, or on a recipe count that
      has collapsed — a short set is invisible, since the item simply refuses
      to route to the ingredient slot.
"""

from __future__ import annotations

import json
import os
import sys

from recipe_ingredients import accepted_inputs  # tools/ is sys.path[0]

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "crates", "rewo-data", "src", "smelting_table.rs",
)

# (recipe type, the RecipePropertySet it feeds, a floor the count must clear)
#
# The floors are the guard against the data moving, and they live HERE rather
# than as a `.len()` assertion in the generated file on purpose. A length test
# the generator emits asserts the table equals itself — it passes at 156 and at
# 6 alike — which is the self-calibrating witness M92 records. A literal in the
# generator cannot recalibrate itself on a re-run.
#
# Set just under the observed 73 / 25 / 9 so a collapse fails and a single new
# vanilla recipe does not.
KINDS = [
    ("minecraft:smelting", "FURNACE", 70),
    ("minecraft:blasting", "BLAST_FURNACE", 24),
    ("minecraft:smoking", "SMOKER", 8),
]


def main() -> int:
    sets: dict[str, list[str]] = {}
    for kind, name, floor in KINDS:
        acc, found = accepted_inputs("gen_smelt", kind, floor)
        sets[name] = acc
        print(f"[gen_smelt] {name}: {found} recipes -> {len(acc)} accepted inputs")

    def block(name: str) -> str:
        rows = "\n".join(f'    "{i}",' for i in sets[name])
        return (
            f"/// `RecipePropertySet.{name}_INPUT` — {len(sets[name])} items.\n"
            f"pub static {name}_INPUT: &[&str] = &[\n{rows}\n];\n"
        )

    out = f'''//! What each furnace will accept — GENERATED by `tools/gen_smelting_inputs.py`.
//!
//! Do not edit. Re-run the generator after a version bump.
//!
//! `AbstractFurnaceMenu.canSmelt` is `acceptedInputs.test(stack)`, and each
//! furnace passes its own `RecipePropertySet`: `FURNACE_INPUT` (smelting),
//! `BLAST_FURNACE_INPUT` (blasting), `SMOKER_INPUT` (smoking). These are the
//! ingredient sets of the jar's own recipes, with tags expanded.
//!
//! # The caveat
//!
//! On the client those sets really arrive in `update_recipes`, which Rewo does
//! not decode. **A datapack that adds or removes a smelting recipe makes this
//! wrong with no error anywhere** — a shift-clicked item routes to the player's
//! inventory instead of the ingredient slot, or the reverse. This is the
//! vanilla answer, not the server's, and it is the same trade M19 makes reading
//! `ItemTags.SPEARS` from the jar and M42 reading the enchantment tags.

{block("FURNACE")}
{block("BLAST_FURNACE")}
{block("SMOKER")}
/// Whether a furnace of the given `minecraft:menu` id accepts `item` as an
/// ingredient, or `None` if that menu is not a furnace.
pub fn accepts(menu_protocol_id: i32, item: &str) -> Option<bool> {{
    let set: &[&str] = match menu_protocol_id {{
        10 => BLAST_FURNACE_INPUT,
        14 => FURNACE_INPUT,
        22 => SMOKER_INPUT,
        _ => return None,
    }};
    Some(set.contains(&item))
}}

#[cfg(test)]
mod tests {{
    use super::*;

    /// The menu ids `accepts` dispatches on, from `minecraft:menu`.
    const BLAST: i32 = 10;
    const FURNACE: i32 = 14;
    const SMOKER: i32 = 22;

    #[test]
    fn each_furnace_accepts_its_own_recipe_type() {{
        // A smoker takes food and not ore; a blast furnace the reverse. If the
        // three sets were the same the routing would still "work" and be wrong.
        assert_eq!(accepts(SMOKER, "minecraft:beef"), Some(true));
        assert_eq!(accepts(SMOKER, "minecraft:iron_ore"), Some(false));
        assert_eq!(accepts(BLAST, "minecraft:iron_ore"), Some(true));
        assert_eq!(accepts(BLAST, "minecraft:beef"), Some(false));
        // A furnace takes both, being the superset.
        assert_eq!(accepts(FURNACE, "minecraft:beef"), Some(true));
        assert_eq!(accepts(FURNACE, "minecraft:iron_ore"), Some(true));
    }}

    #[test]
    fn a_log_is_smeltable_which_is_what_makes_it_route_as_an_ingredient() {{
        // The case that decides the whole furnace quick-move: vanilla checks
        // canSmelt BEFORE isFuel, and a log is both — fuel, and smeltable to
        // charcoal — so it goes to the INGREDIENT slot. Routing on isFuel
        // alone puts it in the fuel slot, which is wrong and looks reasonable.
        assert_eq!(accepts(FURNACE, "minecraft:oak_log"), Some(true));
        assert!(crate::fuel_table::is_fuel("minecraft:oak_log"));
    }}

    #[test]
    fn coal_is_fuel_and_not_an_ingredient() {{
        assert_eq!(accepts(FURNACE, "minecraft:coal"), Some(false));
        assert!(crate::fuel_table::is_fuel("minecraft:coal"));
    }}

    #[test]
    fn a_non_furnace_menu_answers_none_not_false() {{
        // `None` is "this menu has no accepted-input set", which the caller
        // must not read as "it accepts nothing".
        assert_eq!(accepts(2, "minecraft:iron_ore"), None); // generic_9x3
        assert_eq!(accepts(8, "minecraft:iron_ore"), None); // anvil
    }}
}}
'''
    open(OUT, "w", encoding="utf-8", newline="\n").write(out)
    print(f"[gen_smelt] wrote {os.path.relpath(OUT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
