"""Generate crates/rewo-data/src/loom_pattern_table.rs — what a loom offers.

`LoomMenu.getSelectablePatterns`:

    if (patternStack.isEmpty())
       return patternGetter.get(BannerPatternTags.NO_ITEM_REQUIRED)...;
    HolderSet<BannerPattern> itemPatterns = patternStack.get(PROVIDES_BANNER_PATTERNS);
    return itemPatterns != null ? copyOf(itemPatterns) : of();

# Two of M93h's three blockers were wrong, and this is why

M93h recorded that the occupied-pattern-slot case needs the
`PROVIDES_BANNER_PATTERNS` **HolderSet value off the wire** and the
`minecraft:banner_pattern` **registry** to resolve its ids. Neither is true:

  * the component is on the item's **PROTOTYPE**, set by
    `.delayedComponent(PROVIDES_BANNER_PATTERNS, ctx -> ctx.getOrThrow(
    BannerPatternTags.PATTERN_ITEM_FLOWER))`. A prototype never crosses the
    wire, so there is nothing to decode.
  * and its value is a **named** HolderSet — a tag — so even on the wire it
    would be a *name*, not a list of registry ids. The ids only exist inside
    the tag file, which is jar data.

So the whole thing is jar-derivable. The one blocker that was real is that
`expand_tag` hardcoded `tags/item`; it now takes a registry.

# Why the mapping is extracted and not guessed

`flower_banner_pattern` -> `pattern_item/flower` looks like a rule, and
`bordure_indented_banner_pattern` -> `pattern_item/bordure_indented` looks like
the same rule. It is not a rule, it is a coincidence of naming: the mapping
lives in `Items.java` as an explicit constant per item, and a version that
renamed either side would leave a guesser silently offering the wrong pattern.
Both sides are read here — the item->constant from `Items.java`, the
constant->tag id from `BannerPatternTags.java` — and the generator fails if
they do not line up.

Run:  python tools/gen_loom_patterns.py
"""

from __future__ import annotations

import os
import re
import sys

from recipe_ingredients import BASE, die, expand_tag  # tools/ is sys.path[0]

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "crates", "rewo-data", "src", "loom_pattern_table.rs",
)
TOOL = "gen_loompat"
SRC = os.path.join(BASE, "decompiled/net/minecraft")


def read(rel: str) -> str:
    p = os.path.join(SRC, rel)
    if not os.path.exists(p):
        die(TOOL, f"no decompiled source at {p}")
    return open(p, encoding="utf-8").read()


def main() -> int:
    # 1. constant -> tag id, from BannerPatternTags.
    tags_src = read("tags/BannerPatternTags.java")
    const_to_tag = dict(
        re.findall(r'TagKey<BannerPattern>\s+(\w+)\s*=\s*create\("([^"]+)"\)', tags_src)
    )
    if "NO_ITEM_REQUIRED" not in const_to_tag:
        die(TOOL, "BannerPatternTags has no NO_ITEM_REQUIRED — the shape moved")

    # 2. item -> constant, from Items.java. The registration spans several
    #    lines, so the item id is the nearest `registerItem(ItemIds.X,` ABOVE
    #    each delayedComponent.
    items_src = read("world/item/Items.java")
    item_to_const: list[tuple[str, str]] = []
    for m in re.finditer(
        r"PROVIDES_BANNER_PATTERNS,\s*context\s*->\s*context\.getOrThrow\(BannerPatternTags\.(\w+)\)",
        items_src,
    ):
        const = m.group(1)
        before = items_src[: m.start()]
        ids = re.findall(r"registerItem\(\s*ItemIds\.(\w+)", before)
        if not ids:
            die(TOOL, f"no registerItem above the {const} registration")
        item_to_const.append((ids[-1].lower(), const))
    if len(item_to_const) < 10:
        die(TOOL, f"{len(item_to_const)} pattern items, expected at least 10")

    # 3. resolve each side, failing loudly rather than guessing.
    rows: list[tuple[str, list[str]]] = []
    for item, const in item_to_const:
        tag = const_to_tag.get(const)
        if tag is None:
            die(TOOL, f"{const} is used by Items.java and absent from BannerPatternTags")
        patterns = expand_tag(TOOL, tag, registry="banner_pattern")
        if not patterns:
            die(TOOL, f"{tag} expanded to nothing")
        rows.append((f"minecraft:{item}", patterns))

    no_item = expand_tag(TOOL, const_to_tag["NO_ITEM_REQUIRED"], registry="banner_pattern")
    if len(no_item) < 16:
        die(TOOL, f"no_item_required is {len(no_item)} entries, expected at least 16")

    def lit(v: list[str]) -> str:
        return "&[" + ", ".join(f'"{x}"' for x in v) + "]"

    pairs = "\n".join(f'    ("{i}", {lit(p)}),' for i, p in rows)
    none = "\n".join(f'    "{x}",' for x in no_item)

    out = f'''//! What a loom offers to stamp — GENERATED by
//! `tools/gen_loom_patterns.py`. Do not edit; re-run after a version bump.
//!
//! `LoomMenu.getSelectablePatterns` is two cases: an **empty** pattern slot
//! offers `BannerPatternTags.NO_ITEM_REQUIRED`, and an occupied one offers
//! whatever that item's `PROVIDES_BANNER_PATTERNS` names.
//!
//! # Both are jar data, which M93h got wrong
//!
//! M93h recorded the occupied case as blocked on decoding a HolderSet **value**
//! off the wire and on the `minecraft:banner_pattern` **registry**. Neither is
//! needed: the component lives on the item's **prototype**, which never crosses
//! the wire at all, and its value is a **named** HolderSet — a tag id, whose
//! contents are in the jar. The only real blocker was that the tag expander
//! hardcoded `tags/item`.
//!
//! # The mapping is extracted, not inferred
//!
//! `flower_banner_pattern -> pattern_item/flower` looks like a rule. It is a
//! naming coincidence: `Items.java` names an explicit constant per item and
//! `BannerPatternTags` maps that constant to a tag id. Both sides are read.
//!
//! # The caveat
//!
//! A datapack may retag these, and `update_tags` reaches no consumer — the same
//! trade M19, M42, M91 and M93a make.

/// `BannerPatternTags.NO_ITEM_REQUIRED` — what an EMPTY pattern slot offers,
/// {len(no_item)} patterns.
pub static NO_ITEM_REQUIRED: &[&str] = &[
{none}
];

/// Each pattern item and the patterns it offers, in `Items.java` order.
pub static PATTERN_ITEMS: &[(&str, &[&str])] = &[
{pairs}
];

/// `LoomMenu.getSelectablePatterns` — what the loom offers for this pattern
/// slot.
///
/// `None` is an **empty** slot, which offers the no-item-required set. An
/// occupied slot offers only its own item's patterns, and an item with no
/// `PROVIDES_BANNER_PATTERNS` offers **nothing at all** — `ImmutableList.of()`,
/// not the default set. Falling back to `NO_ITEM_REQUIRED` there would let any
/// junk in the pattern slot unlock every pattern.
pub fn selectable_patterns(pattern_slot: Option<&str>) -> &'static [&'static str] {{
    match pattern_slot {{
        None => NO_ITEM_REQUIRED,
        Some(item) => PATTERN_ITEMS
            .iter()
            .find(|(i, _)| *i == item)
            .map_or(&[][..], |(_, p)| *p),
    }}
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn an_empty_slot_offers_the_no_item_required_set() {{
        assert_eq!(selectable_patterns(None), NO_ITEM_REQUIRED);
        assert!(NO_ITEM_REQUIRED.len() >= 16, "and it is the big one");
    }}

    #[test]
    fn a_pattern_item_offers_only_its_own() {{
        let flower = selectable_patterns(Some("minecraft:flower_banner_pattern"));
        assert_eq!(flower.len(), 1);
        // ...and it is NOT a subset of the free set: a pattern that needs an
        // item is exactly one the empty slot does not offer.
        assert!(!NO_ITEM_REQUIRED.contains(&flower[0]), "{{:?}}", flower[0]);
    }}

    #[test]
    fn an_item_with_no_patterns_offers_NOTHING_not_the_default() {{
        // `ImmutableList.of()`, not the no-item-required set. Falling back
        // would let any junk in the pattern slot unlock every pattern.
        assert!(selectable_patterns(Some("minecraft:stick")).is_empty());
        assert!(selectable_patterns(Some("minecraft:white_banner")).is_empty());
    }}

    #[test]
    fn every_pattern_item_maps_to_a_distinct_pattern() {{
        // Two items offering the same pattern would make the loom's index
        // ambiguous in a way vanilla's data never is.
        let mut seen = std::collections::BTreeSet::new();
        for (item, pats) in PATTERN_ITEMS {{
            for p in *pats {{
                assert!(seen.insert(*p), "{{p}} offered by two items, one is {{item}}");
            }}
        }}
        assert_eq!(PATTERN_ITEMS.len(), {len(rows)});
    }}
}}
'''
    open(OUT, "w", encoding="utf-8", newline="\n").write(out)
    print(f"[{TOOL}] no_item_required {len(no_item)}, pattern items {len(rows)} "
          f"-> {os.path.relpath(OUT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
