"""Generate crates/rewo-data/src/loom_table.rs — the loom's three input sets.

`LoomMenu` routes a shift-clicked stack by three predicates, in this order:

    stack.getItem() instanceof BannerItem
    isDyeItem(stack)     = is(ItemTags.LOOM_DYES)     && has(DataComponents.DYE)
    isPatternItem(stack) = is(ItemTags.LOOM_PATTERNS) && has(PROVIDES_BANNER_PATTERNS)

and the same three are the `mayPlace` of its three input slots.

# Why the banner set is the TAG and not the component

`instanceof BannerItem` is a Java class test, and the obvious data stand-in is
`minecraft:banner_patterns` — which every banner's prototype carries, because
the very lambda that constructs the `BannerItem` also sets it:

    ColorCollection.registerBlockItems(BlockItemIds.BANNER, Blocks.BANNER,
        (id, block, color) -> registerBlock(id, block,
            (b, p) -> new BannerItem(b, Blocks.WALL_BANNER.pick(color), p),
            new Item.Properties().stacksTo(16)
                .component(DataComponents.BANNER_PATTERNS, BannerPatternLayers.EMPTY)))

**But the SHIELD carries it too** (`Items.java`, `ItemIds.SHIELD`), so the
component over-approximates the class by exactly one item — and that one item
is a plausible thing to try to put in a loom. `#minecraft:banners` is the
faithful set: `BannerItem` is constructed in exactly ONE place, the 16-colour
`ColorCollection` above, and the tag holds exactly those 16.

The generator checks that rather than trusting it: 16 entries, every one ending
`_banner`. A version that adds a seventeenth banner, or puts something else in
the tag, stops here instead of silently widening the slot.

# The conjunctions are conjunctions

`isDyeItem` needs BOTH terms. Every vanilla item satisfies them together, so a
tag-only test looks correct and diverges the moment a datapack tags an item
without the component — the same shape as M93e's `max_damage`-without-`damage`.
The tag half is emitted here; the component half is `prototype_has_component`
(M56) and the patch half rides on the stack.

**The M91 caveat applies to the tags, as always:** `update_tags` is the
authoritative source and Rewo does not plumb it, so a datapack that retags
makes this wrong with no error anywhere.

Run:  python tools/gen_loom_items.py
"""

from __future__ import annotations

import os
import sys

from recipe_ingredients import die, expand_tag  # tools/ is sys.path[0]

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "crates", "rewo-data", "src", "loom_table.rs",
)
TOOL = "gen_loom"


def main() -> int:
    banners = expand_tag(TOOL, "minecraft:banners")
    dyes = expand_tag(TOOL, "minecraft:loom_dyes")
    patterns = expand_tag(TOOL, "minecraft:loom_patterns")

    # The one check that is not a count: the banner tag must be the 16-colour
    # ColorCollection and nothing else, because it is standing in for a class.
    if len(banners) != 16 or not all(b.endswith("_banner") for b in banners):
        die(TOOL, f"#minecraft:banners is {len(banners)} entries {banners!r} — "
                  f"expected the 16 colours; it is standing in for "
                  f"`instanceof BannerItem` and must not drift from it")
    for name, got, want in [("loom_dyes", dyes, 16), ("loom_patterns", patterns, 10)]:
        if len(got) < want:
            die(TOOL, f"#{name} expanded to {len(got)}, expected at least {want} — "
                      f"a short set silently sends the item to the hotbar instead")

    def block(ident: str, doc: str, rows: list[str]) -> str:
        body = "\n".join(f'    "{r}",' for r in rows)
        return f"/// {doc} — {len(rows)} items.\npub static {ident}: &[&str] = &[\n{body}\n];\n"

    out = f'''//! The loom's three input sets — GENERATED by `tools/gen_loom_items.py`.
//!
//! Do not edit. Re-run the generator after a version bump; it emits its own
//! tests, so a re-run reproduces this file whole.
//!
//! # `BANNERS` is a tag standing in for a class, and that is checked
//!
//! `LoomMenu`'s banner slot is `getItem() instanceof BannerItem`. The obvious
//! data stand-in — the `minecraft:banner_patterns` prototype component — is
//! **wrong by exactly one item**: the SHIELD carries it too, and a shield is a
//! plausible thing to try to put in a loom. `BannerItem` is constructed in one
//! place only, the 16-colour `ColorCollection`, and `#minecraft:banners` holds
//! exactly those 16 — which the generator asserts rather than assumes.
//!
//! # The other two are CONJUNCTIONS
//!
//! ```java
//! isDyeItem     = is(ItemTags.LOOM_DYES)     && has(DataComponents.DYE)
//! isPatternItem = is(ItemTags.LOOM_PATTERNS) && has(PROVIDES_BANNER_PATTERNS)
//! ```
//!
//! Only the tag half is here. The component half is
//! `item_components_table::prototype_has_component` (M56) plus the stack's own
//! patch, because a patch can **remove** a component the prototype carries.
//! Every vanilla item satisfies both terms together, so a tag-only test looks
//! correct — the same trap as M93e's `max_damage` without `damage`.
//!
//! # The caveat
//!
//! `update_tags` is the authoritative source and Rewo does not plumb it into
//! any consumer, so a datapack that retags these makes the table wrong with no
//! error anywhere. Same trade M19 makes for `ItemTags.SPEARS`, M42 for the
//! enchantment tags, M91 for the smelting sets and M93a for the beacon's.

{block("BANNERS", "`#minecraft:banners`, standing in for `instanceof BannerItem`", banners)}
{block("LOOM_DYES", "`ItemTags.LOOM_DYES` (which nests `#minecraft:dyes`)", dyes)}
{block("LOOM_PATTERNS", "`ItemTags.LOOM_PATTERNS`", patterns)}
/// `getItem() instanceof BannerItem`.
pub fn is_banner(item: &str) -> bool {{
    BANNERS.contains(&item)
}}

/// The **tag half** of `isDyeItem`. The caller must still check
/// `has(DataComponents.DYE)` — see the module docs.
pub fn in_loom_dyes(item: &str) -> bool {{
    LOOM_DYES.contains(&item)
}}

/// The **tag half** of `isPatternItem`. The caller must still check
/// `has(PROVIDES_BANNER_PATTERNS)`.
pub fn in_loom_patterns(item: &str) -> bool {{
    LOOM_PATTERNS.contains(&item)
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn the_banner_set_is_the_sixteen_colours_and_not_the_shield() {{
        assert_eq!(BANNERS.len(), 16);
        assert!(is_banner("minecraft:white_banner"));
        assert!(is_banner("minecraft:black_banner"));
        // THE case this table exists for. A shield carries
        // `minecraft:banner_patterns` on its prototype exactly as a banner
        // does, so deriving the set from that component instead of from the
        // tag would let a shield into the loom's banner slot.
        assert!(!is_banner("minecraft:shield"));
        assert!(!is_banner("minecraft:white_wall_banner"));
    }}

    #[test]
    fn the_dye_and_pattern_sets_are_disjoint_from_each_other_and_from_banners() {{
        // The loom tests the three in order, and an item in two sets would
        // make that order load-bearing in a way vanilla's data never is.
        for d in LOOM_DYES {{
            assert!(!is_banner(d), "{{d}} is in two sets");
            assert!(!in_loom_patterns(d), "{{d}} is in two sets");
        }}
        for p in LOOM_PATTERNS {{
            assert!(!is_banner(p), "{{p}} is in two sets");
        }}
    }}

    #[test]
    fn the_tags_hold_what_they_say() {{
        assert!(in_loom_dyes("minecraft:red_dye"));
        assert!(!in_loom_dyes("minecraft:stick"));
        assert!(in_loom_patterns("minecraft:flower_banner_pattern"));
        assert!(!in_loom_patterns("minecraft:paper"));
    }}
}}
'''
    open(OUT, "w", encoding="utf-8", newline="\n").write(out)
    print(f"[{TOOL}] banners {len(banners)}, dyes {len(dyes)}, patterns {len(patterns)} "
          f"-> {os.path.relpath(OUT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
