"""Generate `crates/rewo-data/src/beacon_payment_table.rs` from the client jar.

`BeaconMenu`'s payment slot is

    public boolean mayPlace(final ItemStack itemStack) {
       return itemStack.is(ItemTags.BEACON_PAYMENT_ITEMS);
    }

and that tag is data, not code: `data/minecraft/tags/item/beacon_payment_items.json`
inside the client jar, which is the vanilla datapack the jar ships. Same source
`ItemTags.SPEARS` (M19) and the enchantment tags (M42) are read from, and the
same caveat applies and is repeated in the generated file: a **server datapack**
that retags it makes the table wrong with no error anywhere.

Tags nest — an entry may be `#minecraft:other_tag` — so the expansion recurses,
exactly as `gen_fuel_values.py` does. 26.2's beacon tag happens to be five flat
entries, but keying the generator on that would break silently on a version that
introduces a nested one.

Usage:  python tools/gen_beacon_payment.py
"""

import json
import os
import sys
import zipfile

JAR = os.path.expandvars(
    r"%APPDATA%/EwoClient/shared/versions/26.2/26.2.jar"
)
OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "crates",
    "rewo-data",
    "src",
    "beacon_payment_table.rs",
)
TAG = "minecraft:beacon_payment_items"


def tag_path(name):
    """`minecraft:foo` -> the jar path of `data/minecraft/tags/item/foo.json`."""
    ns, _, path = name.partition(":")
    if not path:
        ns, path = "minecraft", ns
    return f"data/{ns}/tags/item/{path}.json"


def expand(jar, name, seen):
    """Every item id in a tag, following `#`-references. Order is the file's."""
    if name in seen:
        raise SystemExit(f"tag cycle through {name}")
    seen.add(name)
    try:
        raw = jar.read(tag_path(name)).decode("utf-8")
    except KeyError:
        raise SystemExit(
            f"{tag_path(name)} missing from the jar — the beacon's payment "
            f"predicate cannot be inferred from anything else"
        )
    out = []
    for entry in json.loads(raw)["values"]:
        # An entry may be a bare string or `{"id": ..., "required": false}`.
        value = entry["id"] if isinstance(entry, dict) else entry
        if value.startswith("#"):
            out.extend(expand(jar, value[1:], seen))
        else:
            out.append(value)
    return out


def main():
    if not os.path.exists(JAR):
        sys.exit(f"client jar not found: {JAR}")
    with zipfile.ZipFile(JAR) as jar:
        items = expand(jar, TAG, set())
    if not items:
        sys.exit(
            f"{TAG} expanded to nothing — an empty table would silently make "
            f"every beacon shift-click cross-move instead"
        )

    rows = "".join(f'    "{i}",\n' for i in items)
    n = len(items)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(
            f"""//! `ItemTags.BEACON_PAYMENT_ITEMS` — GENERATED by
//! `tools/gen_beacon_payment.py`.
//!
//! Do not edit. Re-run the generator after a version bump.
//!
//! `BeaconMenu`'s payment slot is `mayPlace = itemStack.is(BEACON_PAYMENT_ITEMS)`,
//! and its `quickMoveStack` guard asks the same question, so this is the one
//! item fact the beacon's shift-click needs.
//!
//! Read out of the client jar's `data/minecraft/tags/item/beacon_payment_items.json`
//! — the vanilla datapack the jar carries — which is the same source `ItemTags.SPEARS`
//! (M19) and the enchantment tags (M42) come from. **The caveat those carry
//! applies here too:** a server datapack that retags this makes the table wrong
//! with no error anywhere, because a tag override arrives on `update_tags`
//! (decoded by M69, deliberately not plumbed into any consumer).

/// Every item in the tag, in the file's own order, {n} entries.
pub static BEACON_PAYMENT: &[&str] = &[
{rows}];

/// Whether an item id is accepted by a beacon's payment slot.
pub fn is_beacon_payment(name: &str) -> bool {{
    BEACON_PAYMENT.contains(&name)
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn the_tag_is_the_five_vanilla_payment_metals() {{
        // Pinned by name rather than by count: a version that adds a sixth
        // should fail here and be looked at, not silently widen the slot.
        assert_eq!(
            BEACON_PAYMENT,
            &[
                "minecraft:netherite_ingot",
                "minecraft:emerald",
                "minecraft:diamond",
                "minecraft:gold_ingot",
                "minecraft:iron_ingot",
            ]
        );
    }}

    #[test]
    fn an_ordinary_item_is_not_payment() {{
        // The negative matters more than the positive: `mayPlace` defaulting
        // to true is what would let a stick into the slot.
        assert!(!is_beacon_payment("minecraft:stick"));
        assert!(!is_beacon_payment("minecraft:iron_block"));
        assert!(!is_beacon_payment("minecraft:gold_nugget"));
        assert!(is_beacon_payment("minecraft:iron_ingot"));
    }}
}}
"""
        )
    print(f"wrote {OUT}: {len(items)} entries")


if __name__ == "__main__":
    main()
